### ISSUE TITLE
WCF unusable behind reverse proxy (too many redirects)

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#1099]
Using this setup:

nginx:

```
server {
        listen 80 default;
        server_name node42;

        location / {
                proxy_pass http://127.0.0.1:8080/wbb/wbb4/;
#               proxy_redirect default;
        }
}
```

lighttpd running on 8080 with a WCF available under:
`/wcf/wcf2`
and Burning Board available under:
`/wbb/wbb4`

Error: Too many redirects.

The issue lies in RequestHandler::buildRequest():
`if (StringUtil::replace(RouteHandler::getHost(), '', $redirectURL) == $_SERVER['REQUEST_URI']) {`

Because: `$redirectURL` is `http://node42/` and `REQUEST_URI` is: `wbb/wbb4`

Excerpt of PHPInfo (served by lighttpd and lying in /wbb/wbb4/phpinfo.php`:

```
_SERVER["PATH"] /sbin:/bin:/usr/sbin:/usr/bin
_SERVER["PHP_FCGI_CHILDREN"]    4
_SERVER["PHP_FCGI_MAX_REQUESTS"]    10000
_SERVER["HTTP_COOKIE"]  wcf_cookieHash=e449127ae8e8dc2056deb026f5d0dba408fc7651
_SERVER["HTTP_ACCEPT_CHARSET"]  ISO-8859-1,utf-8;q=0.7,*;q=0.3
_SERVER["HTTP_ACCEPT_LANGUAGE"] de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
_SERVER["HTTP_ACCEPT_ENCODING"] gzip,deflate,sdch
_SERVER["HTTP_USER_AGENT"]  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17
_SERVER["HTTP_ACCEPT"]  text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
_SERVER["HTTP_CACHE_CONTROL"]   max-age=0
_SERVER["HTTP_CONNECTION"]  close
_SERVER["HTTP_HOST"]    127.0.0.1:8080
_SERVER["SERVER_PROTOCOL"]  HTTP/1.0
_SERVER["REDIRECT_STATUS"]  200
_SERVER["REQUEST_METHOD"]   GET
_SERVER["QUERY_STRING"] no value
_SERVER["REQUEST_URI"]  /wbb/wbb4/phpinfo.php
_SERVER["DOCUMENT_ROOT"]    /data/webroot
_SERVER["SCRIPT_FILENAME"]  /data/webroot/wbb/wbb4/phpinfo.php
_SERVER["PATH_INFO"]    no value
_SERVER["SCRIPT_NAME"]  /wbb/wbb4/phpinfo.php
_SERVER["REMOTE_ADDR"]  127.0.0.1
_SERVER["REMOTE_PORT"]  53758
_SERVER["SERVER_ADDR"]  127.0.0.1
_SERVER["SERVER_PORT"]  8080
_SERVER["GATEWAY_INTERFACE"]    CGI/1.1
_SERVER["SERVER_NAME"]  127.0.0.1
_SERVER["SERVER_SOFTWARE"]  lighttpd/1.4.28
_SERVER["FCGI_ROLE"]    RESPONDER
_SERVER["PHP_SELF"] /wbb/wbb4/phpinfo.php
_SERVER["REQUEST_TIME_FLOAT"]   1358517612.2721
_SERVER["REQUEST_TIME"] 1358517612
```

cf. #944

**Comment by stephtr** [comment]
For those landing on this page using Google or similar: I had the same problem and "circumvented" it by including the following lines in `config.inc.php`:
```
if(strpos($_SERVER['HTTP_HOST'], ':') > 0){ // Fix WCF issue behind reverse proxy
  $_SERVER['HTTP_HOST'] = strstr($_SERVER['HTTP_HOST'], ':', true);
}
if($_SERVER['REMOTE_ADDR'] == '127.0.0.1'){ // Reverse Proxy
  $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];
}
```
The first `if` looks for the port number being included in the host-header and removes it.
The other one tries to correct the reported client ip.
The additional nginx settings necessary are:
```
proxy_set_header Host $host:$server_port;
proxy_set_header X-Forwarded-For $remote_addr;
```

**Comment by TheHades** [comment]
Hello,

that doesn't work either
Chrome keeps saying "too many redirects".

NGINX: Port 80
Apache: 127.0.0.1 and Port 8080.

nginx-vhost:
`server {
    listen   80;

    root /var/www/virtual/USERNAME/html;
    index index.php index.html index.htm;

    server_name domain.tld;

    location / {
    try_files $uri $uri/ /index.php;
    }

    location ~ \.php$ {

    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:8080;
     }

     location ~ /\.ht {
            deny all;
    }
}
`

Apache-VHost-Config:
`<IfModule mod_fastcgi.c>
   AddHandler php5.fcgi .php
   Action php5.fcgi /php5.fcgi
   Alias /php5.fcgi /usr/lib/cgi-bin/php5.fcgi
   FastCgiExternalServer /usr/lib/cgi-bin/php5.fcgi -socket /var/run/php5-fpm-domain.sock -pass-header Authorization -idle-timeout 3600
   <Directory /usr/lib/cgi-bin>
       Require all granted
   </Directory>
</IfModule>

<VirtualHost 127.0.0.1:8080>

	ServerAdmin webmaster@domain.tld
	ServerName domain.tld
	ServerAlias www.domain.tld
	DocumentRoot /var/www/virtual/domain/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`

the adminpanel (/acp) is still accessible, the forums not.
Any idea?

**Comment by GorlikItsMe** [comment]
If you use cloudflare you can add this code to `config.inc.php`

```php
if (array_key_exists('HTTP_CF_CONNECTING_IP', $_SERVER)) {
    $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];
}
```
