### ISSUE TITLE
CLI - Uninstall - Install - Uninstall

### ISSUE THREAD

**Issue by MeinAccount** [WoltLab/WCF#1578]
A package cannot be uninstalled, installed and then uninstalled within the same session.

```
[ERROR] package.invalidUninstallation:[]
wcf.acp.package.error.invalidUninstallation
Usage: /home/magnus/Internet/WCF/Dummy-App/wcf/cli.php [ options ]
```

![bildschirmfoto vom 2013-12-01 11 38 00](https://f.cloud.github.com/assets/918457/1650242/ad1357f2-5a74-11e3-96be-7cc25e49ab80.png)

**Comment by mutec** [comment]
please reopen that issue, it's still present: https://community.woltlab.com/thread/270911-cli-package-uninstall-direkt-nach-installation-nicht-nutzbar/
