### ISSUE TITLE
Bad design of mail handling

### ISSUE THREAD

**Issue by schlimpf** [WoltLab/WCF#1748]
Hi,

i cannot correct this on my own without changing the API of the Mail class, so I post this here:
The design of the receivers, cc and bb has multiple flaws.

When enabling the MAIL_USE_FORMATTED_ADDRESS setting, the email addresses are saved in the "Name" &lt;email> schema into the class variables ($this->to, cc, bcc).
If you use the SMTP sender, it will fail sending the messages due to the fact that the RCPT TO command used in SMTP expects the plain email address, not the formatted one.

The second problem I see is that due to the fact of using the indices of the array as the name of the receiver, e.g. when calling the addTo() function of the Mail class, you cannot have two recipients with the same name without calling the function twice.
Although this is no real problem, I consider this as a bad design.
Maybe it would be better to have the function addTo() to expect two parameters "name" and "email" and only add one recipient at a time.

I think the best would be to not save the formatted addresses, but the name and emails in separate fields. It may be nice to have a class like "MailAddress" that holds the name and email and provides a function "getFormattedAddress" which returns the formatted address when needed.

Best
M

**Comment by TimWolla** [comment]
7a7c9ea47e437ade552cf31610d17b3e6714a2e9
