### ISSUE TITLE
Add missing Spiders

### ISSUE THREAD

**Issue by MpsForum** [WoltLab/WCF#1789]
Mozilla/5.0 (compatible; Tapatalk CloudSearch Platform/1.0; http://www.tapatalk.com/bot.html)

Mozilla/5.0 (compatible; linkdexbot/2.0; +http://www.linkdex.com/about/bots/)

Pixray-Seeker/2.0 (Pixray-Seeker; http://www.pixray.com/pixraybot; crawler@pixray.com)

Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.8.0.11) Gecko/20070312 Firefox/1.5.0.11; 360Spider

HRCrawler/2.0 (XF86; MacOS x86_64) AppleWebKit/537.31 (KHTML, like Gecko)

**Comment by CobbleCity** [comment]
FeedlyBot/1.0 (http://feedly.com)

**Comment by MpsForum** [comment]
Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots)

Mozilla/5.0 (compatible; savetheworldheritage.org/1.0; +crawl@savetheworldheritage.org)
