### ISSUE TITLE
Fatal error when clicking on Moderation in Menu Bar

### ISSUE THREAD

**Issue by dominicstellwag** [WoltLab/WCF#1875]
![fjjihiac](https://cloud.githubusercontent.com/assets/9445818/6063581/8f90f134-ad58-11e4-8287-c45e70e9fdf2.jpg)

**Comment by Gravatronics** [comment]
Can you please click on "Alle Einträge anzeigen" and then check if there is also an error message?

Please post error message as text, not as images :)

**Comment by dominicstellwag** [comment]
The error when clicking on 'Moderation' in the menu: 
Fatal error: Call to a member function getUserID() on a non-object in /homepages/12/d331454681/htdocs/forum/wcf/lib/data/moderation/queue/ViewableModerationQueueList.class.php on line 91

The error that is shown when clicking in 'Alle Einträge': 
Fatal error: Call to a member function getAvatar() on a non-object in /homepages/12/d331454681/htdocs/forum/wcf/templates/compiled/0_wcf_1_moderationList.php on line 196
![screen](https://cloud.githubusercontent.com/assets/9445818/6063748/f639ce1e-ad59-11e4-93f3-ffa6a571aed4.jpg)

Btw, I'm logged in as Administrator

**Comment by dominicstellwag** [comment]
Maybe this one helps:
The error only shows when selecting 'Alle Einträge' or 'Niemand' in the sidebar.
![screen2](https://cloud.githubusercontent.com/assets/9445818/6063846/8ac0f800-ad5a-11e4-8919-cfa07bd99964.jpg)

**Comment by Gravatronics** [comment]
Can you please execute the following query:

```sql
SELECT	*
FROM	wcf1_object_type
WHERE 	objectTypeID = (
	SELECT 	objectTypeID
	FROM 	wcf1_moderation_queue
	WHERE 	queueID = 1
)
```

**Comment by dominicstellwag** [comment]
Result is this single row:
![screen3](https://cloud.githubusercontent.com/assets/9445818/6064308/613f9948-ad5d-11e4-9a6b-f566f859810d.jpg)

**Comment by Gravatronics** [comment]
The error is caused by the link list.
