### ISSUE TITLE
Fatal error, when number of posts is set to -1 on the dashboard sidebar

### ISSUE THREAD

**Issue by CobbleCity** [WoltLab/WCF#1877]
Fatal error: Could not execute prepared statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1#

Setting to 0 is infinite

**Comment by joshuaruesweg** [comment]
This isn't a WCF issue. This is a WBB issue.

**Comment by CobbleCity** [comment]
Oh, i think so. I don't think on it :)
