### ISSUE TITLE
WCF.Location.js

### ISSUE THREAD

**Issue by UdoZa** [WoltLab/WCF#1911]
null (for icon) in line 554 prevents (easy) customizing the marker's icon in getMapMarkers function.
Would like $markerInfo.title instead.

**Comment by Gravatronics** [comment]
What prevents you from overwriting `addMarker()`?

**Comment by UdoZa** [comment]
The "(easy)" above.
I'd simply expect a 100% useable API function and not a - obviously for no essential reason - crippled one, which requires me to overwrite it to have it do its job.
