### ISSUE TITLE
SQLParser does not support fulltext and unique indices

### ISSUE THREAD

**Issue by ramiusGitHub** [WoltLab/WCF#1919]
https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/database/util/SQLParser.class.php

The SQLParser (to be accurate: the PackageInstallationSQLParser) class is used in the SQLPackageInstallationPlugin to parse the SQL statements in the package. The SQLParser does not support FULLTEXT or UNIQUE indices. Consequence: A package cannot add unique or fulltext indices with the sql pip.

Reason: The execute() method in the SQLParser only matches "CREATE\s+INDEX" as regular expression but does not support UNIQUE or FULLTEXT indices. The executeStatement() method in the SQLParser uses as regular expression "CREATE\s+(?:(UNIQUE|FULLTEXT)\s+)?INDEX[....]".

**Comment by Stricted** [comment]
and whats with line 104 ? https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/database/util/SQLParser.class.php#L104

**Comment by ramiusGitHub** [comment]
Line104 is only executed when the sql statement is a 'CREATE TABLE' statement.
What I mean is a statement like:

CREATE (FULLTEXT|UNIQUE) INDEX abc ON wcf1_test (text);

But now that you mentioned it: I discovered in ALTER TABLE on line 119 a way to add a fulltext or unique index. The sql statement then has to be like:

ALTER TABLE wcf1_test ADD (FULLTEXT|UNIQUE) INDEX abc (text)

So SQLParser can add fulltext and unique indices, but the regular expression on line 170 contains an unnecessary "(?:(UNIQUE|FULLTEXT)\s+)?".

**Comment by NetzwergX** [comment]
From the MySQL docs:
> CREATE INDEX is mapped to an ALTER TABLE statement to create indexes

So WCF just implemented `ALTER TABLE` as a way to add indices, and not the alternate `CREATE INDEX` syntax. But it is very well possible to create `UNIQUE` indices with WCF ;)
