### ISSUE TITLE
File type filter in AttachmentListPage

### ISSUE THREAD

**Issue by UdoZa** [WoltLab/WCF#1927]
The filter discards "0" although it is a valid first char of a file name in WCF. 
Reason: !empty(...) in readParameters and initObjectList.

**Comment by dtdesign** [comment]
`empty("0")` is `true`, but `empty("01234")` is not. What is your point?

**Comment by ShatteredMotion** [comment]
Just inserting `0` as file name should list all attachments whose file name starts with `0`. However, as @UdoZa described, that value is discarded because it is considered empty.
