### ISSUE TITLE
Allow changing html <=> bbcode translation by registering wbbcode.js events.

### ISSUE THREAD

**Issue by eis-os** [WoltLab/WCF#1959]
The wbbcode.js / Redactor events:

* beforeConvertFromHtml
* ConvertFromHtml
* afterConvertFromHtml
* beforeConvertToHtml
* afterConvertToHtml

will pass the relevant BBCode string or HTML string to event handlers,
but currently it is not possible to modify the actually string in them.

WCF should allow modifying the passed string data.
BBCode tags could implement HTML <-> BBCode translation logic then.

**Comment by dtdesign** [comment]
Fixed in ae5eb74bb46343e7b1e9dfb391e99c3f75736472
