### ISSUE TITLE
After update from WCF 1: No login possible if password contains german umlaut

### ISSUE THREAD

**Issue by 01-Scripts** [WoltLab/WCF#1974]
Hello,

I recognized the following problem after I upgraded a WCF 1 installation to WCF 2.1.9:
The old WCF1/WBB installation was running with ISO-8859 encoding:

    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />

Now if a user was choosing a password that contains i.e. a german umlaut or some other multi byte characters that user was not able to log in after I upgraded the installation to WCF 2.1.9.
Reason: The login page is now served with UTF 8 encoding and so is the submitted form data:

    <meta charset="utf-8" />

An example: The **SHA-1** hash of german umlaut 'ä' is in LATIN encoding `961fa22f61a56e19f3f5f8867901ac8cf5e6d11f` but in UTF-8 it is `89d39ea0600180286a2f794d8b2c4d5b02450ed9`.

So when the user created a password containing a german umlaut within WCF 1 there was a different SHA-1 hash calculated as it is done after the upgrade when the same user is trying to login with his same credentials.

I'm not sure if all WCF 1 installation had a fixed charset=ISO-8859-1 encoding. But if that is the case I would suggest to do the following before calculating the SHA-1 hash values [See Code](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L535):

	protected static function wcf1($username, $password, $salt, $dbHash) {
		return self::secureCompare($dbHash, sha1($salt . sha1($salt . sha1(utf8_decode($password)))));
	}

For reference I'll also link the related topic in the WBB support forum:
https://community.woltlab.com/thread/245591-login-nach-update-von-wbb-3-1-8-nicht-möglich/

I'm open for any comments and discussion.

Regards,
Michael

**Comment by TimWolla** [comment]
> I'm not sure if all WCF 1 installation had a fixed charset=ISO-8859-1 encoding.

It did not. One could choose during installation, depending on the languages that should be installed, with UTF 8 being the default selection if multibyte was supported by PHP.

**Comment by 01-Scripts** [comment]
Thanks for the information. Then my suggestion can't be used that way so easy.
Is it possible in any way to determine what character encoding was chosen during the WCF1 installation after the update process to WCF2 has finished?

Because without that information I have no idea in how to solve that special issue in a general way. For my own installation I will go with a manual change of the PasswordUtil.class.php-file.
