### ISSUE TITLE
Multilingual ACP forms allow input of template tags

### ISSUE THREAD

**Issue by UdoZa** [WoltLab/WCF#1987]
Various ACP forms (WCF and applications) with multilingual input fields, e.g. LabelAdd (title) or BoardAdd (title, description), do allow template tags like {xyz} as content. After saving content with template tags, the forms are no longer useable: Template compilation failed: unknown tag {xyz} in template 'languagevariable'. Users have to manipulate wcf1_language_item (column languageItemValue) to get rid of the problem.

**Comment by BurntimeX** [comment]
Fixed in 59962aa7173334d9d8386afa31097967f3ae93c5
