### ISSUE TITLE
Impossible to insert code after the opening <body> tag

### ISSUE THREAD

**Issue by NBZ4live** [WoltLab/WCF#2017]
Hi,

it seems to be impossible to add custom HTML code directly after the opening <body> tag.
There is no template event.
It is even impossible to preg_replace you code into the template after the <body> tag because there are no events in the template engine.

The only clean solution (without editing core files) is to override all the templates (54 in WCF only) which is uncomfortable. Especially when you're writing a module.

But this place is sometimes important for own code. Or for example is the place where you put Google Tag Manager code to.

The best solution would be to add an event to this position. But this would require all plugin maintainers to add it to their templates, too. This is not very reliable.

Additionally an event must fire in the template engine which would allow to alter the template before or/and after it is compiled.

**Comment by dtdesign** [comment]
The `header` template is always included right after the `<body>` element and right at the very top is `{event name='beforePageHeader'}`, this should be exactly what you're looking for.

**Comment by NBZ4live** [comment]
Ok. Thank you. Overseen this in the first templates because of the `userMenuSidebar`

**Comment by dtdesign** [comment]
The [tt]*Sidebar[/tt] templates only capture/assign content, but don't generate anything in place. But I can see where your confusion came from, I double-checked it before replying ;)
