### ISSUE TITLE
Json API

### ISSUE THREAD

**Issue by chris579** [WoltLab/WCF#2030]
Is there a Json API available? I read about a Rest API which got removed long time ago and it was mentioned that a Json API is planned. This was back in 2013.
Is there now a Json API? 
I couldn't find much on the internet about this topic.

**Comment by dtdesign** [comment]
There is no JSON-API at this time, it was intended back then but dropped for various reasons. You can still access quite a lot of actions through `AJAXProxy` and `AbstractDatabaseObjectAction`, but this requires simulating a logged-in user to work.
