### ISSUE TITLE
Worker in frontend

### ISSUE THREAD

**Issue by joshuaruesweg** [WoltLab/WCF#2064]
Currently the worker in the frontend is unusable. 

[The implementation](https://github.com/WoltLab/WCF/blob/c6aed51a95eb1787c5489e49e85cbeb30d4345d0/wcfsetup/install/files/js/WCF.js#L8433) misses a `WorkerProxyAction`-class (and a reference in the proxy action).

And it uses outdated "functions" (change color of icon) [here](https://github.com/WoltLab/WCF/blob/c6aed51a95eb1787c5489e49e85cbeb30d4345d0/wcfsetup/install/files/js/WCF.js#L8556). 

Maybe we should remove this relict, because the WCF doesn't use this implementation OR (a think a better solution, because I need this implementation for a plugin) fix it with a 2.1.* version. 

Feedback would be very nice! :) 

If PR for the `master`-tree is welcome, I can tinker some.

**Comment by dtdesign** [comment]
Actually it is a working implementation and is actively used in Burning Board, e.g. when copying threads.

**Comment by joshuaruesweg** [comment]
This is really not intuitive that sometimes this is make with a DBO-action and sometimes with a worker class.  :/

**Comment by dtdesign** [comment]
Honestly, I was simply to lazy to implement the whole worker stuff for the frontend, so I picked the cheap route. Not that fancy, but does the job ;)
