### ISSUE TITLE
Dialog position in Internet Explorer

### ISSUE THREAD

**Issue by woouki** [WoltLab/WCF#2065]
The Position for the dialog windows are on the top left corner, not on the correct position. Testet with the current version of Internet Explorer 11, Windows 7. With other browsers, the dialog windows appears correctly.

![dialog1](https://cloud.githubusercontent.com/assets/19870259/17165705/a03a8032-53d2-11e6-96fe-db0364632842.PNG)
![dialog2](https://cloud.githubusercontent.com/assets/19870259/17165706/a06e76a8-53d2-11e6-8938-63beb6b1eeb4.PNG)

**Comment by woouki** [comment]
Sorry, but your commit fix not the error for me. And yes, i deleted the browser cache.

**Comment by dtdesign** [comment]
@woouki Can't confirm that, I've tested it with Internet Explorer 11 on Windows 10 (IE 11.494.10586.0, Updateversion 11.0.33).

Please be advised that the JavaScript might be outdated when running in non-debug mode as I had to disable the automatic process a few days ago due to issues.

**Comment by woouki** [comment]
@dtdesign Thanks for your answer and the notice. Unfortunately it doesn't works for me , but i keep one eye on. Thanks anyway!

**Comment by woouki** [comment]
@dtdesign I saw, you testet it on Windows 10 and i have this error with Windows 7. Maybe the issue comes from the different Internet Explorer Versions by the operatation systems.

**Comment by dtdesign** [comment]
@woouki I doubt that, especially since the entire issue was caused by relying on the properties `screenX` and `screenY` which are not available in Internet Explorer. Instead I'm now using `pageXOffset` and `pageYOffset` which are supported since Internet Explorer 9.

Please make sure to use the latest files from git and clear the browser cache to make sure it isn't using the old version.

**Comment by woouki** [comment]
@dtdesign I have take another look at that to test it. It's curious…

I have installed on my private PC at home a completely (!) new VM with Windows 7 (All current updates) and the Internet Explorer with the current version provided by Microsoft via the update process. In addition, i have reinstalled the WSC 3 from git with the latest files.

It is the same. In Windows 7, it will be displayed in the top left corner.

I 've checked that in the console from the browser developer settings and from my server logs. No errors are logged there.

It looks as if there's something wrong in your code, when the same error appears on two completely different PCs and -settings, and a clean installation with WSC.

**Comment by woouki** [comment]
So. I have now made ​​the effort and have installed Windows 10 as VM.

All tested with the same WSC version, with the latest git files:
**Windows 7, IE 11:** wrong position
**Windows 10, IE 11:** correct (!) position
**Windows 10, Edge:** wrong position

In my opinion, it is up to the different interpretations of IE on different Windows versions (7 and 10).

**Comment by dtdesign** [comment]
I made some changes and it now works in:

* IE 11 (Windows 7 + Windows 10)
* Edge (Windows 10)

Interestingly IE11 has a slightly different version on Windows 7 compared to Windows 10. But yeah, now I have a working VM for Windows 7 again :)
