### ISSUE TITLE
typo in AbstractXMLPackageInstallation.class.php?

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2076]
see https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/package/plugin/AbstractXMLPackageInstallationPlugin.class.php#L360

Should \SystemException be SystemException instead? I think this try catch couldn't work.

**Comment by Stricted** [comment]
https://github.com/WoltLab/WCF/commit/870b0938ec20bb875c2aa2211f299a0c97f963b1
thats the commit where it was added, on some other places the same as above
