### ISSUE TITLE
Guessing of acpTemplates file on installation goes wrong

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2085]
```
Die Installations-Anweisungen geben für das Package Installation Plugin „acpTemplate“ die Datei „“ an, diese ist jedoch nicht im Archiv enthalten. Mögliche Ursachen:
Die Datei wurde dem Archiv nicht hinzugefügt
Die Datei existiert, jedoch sind der Dateiname und die Angabe in den Anweisungen abweichend (Tippfehler)
```
when I use the following:
```xml
<instructions type="install">
	<instruction type="acpTemplate" />
	<instruction type="file" />
	<instruction type="template" />
</instructions>
```

As you can see the system is searching for an empty filename file. So i think guessing the name goes already wrong.

**Comment by mutec** [comment]
Hmm, I checked the code and found, that it has to be `acptemplates.tar` instead of being camelcase like the PIP is. Fixed this in my packaging script now. Maybe you should note that behavior in https://community.woltlab.com/thread/239949/

**Comment by Gravatronics** [comment]
> For file-based package installation plugins like to install ACP templates, files and templates, `s.tar` is appended to the lower case PIP name.
