### ISSUE TITLE
Missing language items

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2087]
- [ ] `wcf.acp.article.views`
- [ ] `wcf.acp.article.i18n.none.description`
- [ ] `wcf.acp.article.i18n.i18n.description`
- [ ] `wcf.acl.option.com.woltlab.wcf.article.category.canReadArticle`
- [ ] `wcf.acp.style.globals.pageLogo.width`
- [ ] `wcf.acp.style.globals.pageLogo.height`
- [ ] `wcf.acp.style.globals.pageLogoMobile`
- [ ] `wcf.acp.style.globals.pageLogoMobile.description`
- [ ] `wcf.acp.style.globals.fontSizeDefault`
- [ ] `wcf.acp.style.globals.fontSizeSmall`
- [ ] `wcf.acp.style.globals.fontSizeHeadline`
- [ ] `wcf.acp.style.globals.fontSizeSection`
- [ ] `wcf.acp.style.globals.fontSizeTitle`
- [ ] `wcf.acp.style.globals.useGoogleFont`
- [ ] `wcf.acp.style.globals.fontFamilyGoogle`
- [ ] `wcf.acp.style.globals.fontFamilyFallback`
- [ ] `wcf.acp.exceptionLog.exception.memory`

**Comment by woouki** [comment]
Your variables are now all available
