### ISSUE TITLE
Problem with writing installed files into the db with more than one instance

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2099]
see https://community.woltlab.com/thread/250155-can-t-install-woltlab-suite-3-0-0-alpha-1/?postID=1540031#post1540031 for more debug information

target directory: `/target/`
old installation backup in: `/target/old/`

WSC wants to write `/target/acp/templates/__boxAddContent.tpl` and `/target/old/acp/templates/__boxAddContent.tpl` into the database which both get shortened to `(acp/templates/)__boxAddContent.tpl`. And that causes an DatabaseQueryExecutionException (MySQL error 23000 `Duplicate entry '...' for key 'applicationTemplate'`) which is not in a `catch` during the installation.

**Comment by dtdesign** [comment]
This has already been the case since WCF 1.0 and does only occur during WCFSetup.

**Comment by mutec** [comment]
But why don't improve that strange bug by using a file structure from the archive or the temporary folder? That shouldn't be a huge fix.

**Comment by dtdesign** [comment]
I'm not going to make changes to the most fundamental parts of the installation process just for some rare issue that surfaced the first time in 7 years. I do understand that you would rather see that fixed, but the potential side-effects of any changes to the setup are simply  not worth it.

**Comment by 0xLeon** [comment]
Also, this probably isn't the (only) problem regarding the bug in the linked thread. I got the same result as described in the thread with a completely clean installation in an empty database. Next week I'll have a look what has caused this error for me.

**Comment by mutec** [comment]
@0xLeon the problem in my case is not the database, it is the filesystem.
You can try adding a try-catch-block on the new WCFSetup() (end of install.php). That gave me my error-message. However Exceptions from WCFSetup are party not catched and will end in a white blank page.
Maybe at least that could be changed, Alexander? There shouldn't be any side effects on catching exceptions.
And could my problem be rechecked within WSC 3.1 or 4.0 or is there no chance anyway?
