### ISSUE TITLE
Add template event for the forum post attributes

### ISSUE THREAD

**Issue by NBZ4live** [WoltLab/WCF#2105]
Hi,

it would be good to have events which allow to add custom classes or custom data attributes to articles (like forum posts in the WBB)

**Comment by jens1o** [comment]
You can do this via jQuery.

**Comment by dtdesign** [comment]
What exactly are you looking to accomplish?

**Comment by NBZ4live** [comment]
I want to add special data attributes conditionally.
In the current case, to be able to mark special posts of users in a special user group.

Doing this through jQuery by checking against a list of userIDs is just wrong.

Such a template variable would allow a variety of additional cases.

**Comment by NBZ4live** [comment]
Why was this closed without even providing reasons against this? As described jQuery is not an option.

**Comment by dtdesign** [comment]
I can't see why you are unable to use JavaScript to solve this, after all modifying the DOM is a core feature and purpose of JavaScript.

**Comment by NBZ4live** [comment]
Because in the data attribute is currently only the ID of the user. And not of his group(s).
This way if you want to apply anything for a group, you need to generate a list of all userIDs who belong to the group and store that in an javascript object.

This would be wrong design.
And if the particular group has thousands of users this would be an unneeded overhead in data sent to the client on every page request.
Requesting the list through AJAX would lead to senseless additional request.

Adding some group identifier somewhere else inside the post and transforming this to an additional class with JS is a bad solution.

**Comment by joshuaruesweg** [comment]
You can check the user (and the user groups of the user) of the article in PHP and assign the additional class to the template, which assigns these to the article.

**Comment by NBZ4live** [comment]
That's the point. There is no way to add additional classes. For example in threadPostList.tpl of WBB you can't add anything to the <li> or <article> of the post.

**Comment by dtdesign** [comment]
```
{if $theFancyGroup|in_array:$post->getUserProfile()->getGroupIDs()}
    <script>
        document.querySelector('.wbbPost[data-object-id="{@$post->postID}"]').classList.add('myFancyCSSClass');
    </script>
{/if}
```

The code above can be used in events such as `afterPost@threadPostList` and applies the CSS class as early as possible, avoiding any flicker caused by premature browser paints/layout.
