### ISSUE TITLE
HTML emails may look distorted on mobile phones

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2196]
Fixed table layouts can cause display issues on handheld devices due to a restricted screen width.

See https://community.woltlab.com/thread/254010-e-mail-benachrichtigungen-lassen-sich-am-handy-nur-schwer-lesen/

**Comment by jens1o** [comment]
How do you plan do solve it differently? Afaik, html in emails is a pretty bad combination.

**Comment by TimWolla** [comment]
> Afaik, html in emails is a pretty bad combination.

What do you mean?

**Comment by jens1o** [comment]
You're quite limited in what email reader allow, so you can't do something like (native) css grid or something like that.

**Comment by TimWolla** [comment]
I am aware of that.

**Comment by jens1o** [comment]
I know, but I'm interested how do you want to that without using tables. Sorry for the inconvenience.

**Comment by TimWolla** [comment]
There is a reason this issue still is open …
