### ISSUE TITLE
Import larger avatars when registering via Google Plus / Facebook

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2217]
Pull larger avatars from:
* [x] Google Plus
* [ ] Facebook

See https://community.woltlab.com/thread/247134-profilbilder-aus-g-und-facebook-in-gr%C3%B6%C3%9Ferer-gr%C3%B6%C3%9Fe/

**Comment by TimWolla** [comment]
As stated in the thread: Facebook seems to be fine in my tests and I don't really have control over the image anyway.
