### ISSUE TITLE
(Lightweight) WYSIWYG support for comments

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2222]
* [x] Support WYSIWYG input for comments
* [x] Add permission for disallowed bbcodes
* [x] Implement editing support
* [x] Add worker to rebuild comments: BBCode -> HTML

See https://community.woltlab.com/thread/245849-bbcode-unterst%C3%BCtzung-bzw-formatierungen-f%C3%BCr-kommentare/

**Comment by dtdesign** [comment]
4e84b0eeb6b8d3fd221c67e361e27d23d82a5d95

**Comment by jens1o** [comment]
Why did you decided not to provide wysiwyg support for comment-comments?
