### ISSUE TITLE
Ajax/Request does not call the failure callback for network errors

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#2244]
When a network error occurs (i.e. stopped webserver, firewalled port) the failure callback is not called.

The reason for this is that Ajax/Request checks whether a responseText with valid JSON as it's content: https://github.com/WoltLab/WCF/blob/4d73840a9a21927bb16a737241a8b4a4ce4a6946/wcfsetup/install/files/js/WoltLabSuite/Core/Ajax/Request.js#L275

The check for `data !== null` should be removed.

**Comment by dtdesign** [comment]
Removing the check itself is only half the story, as it's unclear what to pass in as `data` parameter w/o breaking existing code? Also is there even a `responseText` value?

**Comment by TimWolla** [comment]
> as it's unclear what to pass in as data parameter w/o breaking existing code?

An empty object. After all anything that comes from the network is undefined anyway, the server could return a value that's valid JSON, but not valid JSON according to the failure handler.

> Also is there even a responseText value?

Google Chrome passes an empty string.

**Comment by TimWolla** [comment]
Fixed as of 617c075be8a4342baaf7d1cab7a72a2528ca1410.
