### ISSUE TITLE
gracefully handle box exceptions

### ISSUE THREAD

**Issue by derikson** [WoltLab/WCF#2246]
It has been my experience that exceptions in boxes break the page on which the boxes are displayed. It would be preferable that the box display an error or be hidden, but have the page render as it would otherwise. The error could still be logged as normal.

**Comment by dtdesign** [comment]
Exceptions are designed to halt the program execution, unless it was explicitly catched. If you're confident that a particular error could happen, such as an external service failing to respond (in time), then the exception in question should rather be catched and manually handled, including yielding an empty content string for that box.
