### ISSUE TITLE
Menus should inherit the permission settings of boxes

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2255]
n/t

See https://community.woltlab.com/thread/256572-benutzergruppenabh%C3%A4ngigkeit-f%C3%BCr-men%C3%BCs/
See https://community.woltlab.com/thread/258811-menus-driven-by-group-membership/

**Comment by Morik** [comment]
You do realize that at least the first topic wasn't really about the menus itself and instead about the MenuItems ?

**Comment by jens1o** [comment]
I would be happy when both is possible.

**Comment by dtdesign** [comment]
Page handler can already restrict their visibility, which in return makes the corresponding menu item(s) disappear. External links are an exception, because they're just plain URLs, but this can be covered to some extend by restricting the overall menu visibility.

A more fine-grained control over particular links has been mentioned somewhere in the first thread, but this was neither the core of the suggestion itself nor was it the intention behind this issue. At this point there are absolutely no intentions of extending the permission system to cover individual items.

**Comment by Morik** [comment]
But this is currently not supportet by system controllers, so if a page doesn't provide a proper option to achieve this there is no way to hide a system controller.
