### ISSUE TITLE
Add a selection dialog for FontAwesome icons

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2274]
Required for WoltLab/com.woltlab.wbb#245

**Comment by Morik** [comment]
As the link isn't public, i just wonder if this means that WSF5.1 will have the option to deliver custom forum icons ?

**Comment by SoftCreatR** [comment]
Exactly.

**Comment by Morik** [comment]
Just wondering:
Wouldn't it be much more efficient to deliver the icon list within the js file (as we do in our plugin) as the file will be stored in the browser cache while the current version requires to load the complete icon list with every request ?

**Comment by dtdesign** [comment]
I thought about it, but embedding it into the the JavaScript it has two particular down-sides:
* The whole JavaScript is compiled into a single file that is loaded at all times, increasing the raw filesize even if it's not required most of the time.
* It can easily get out-of-sync and would require me to setup some additional post-commit processing (similar to the minification pipeline).

I could've went with an optional JavaScript file that is only included when required, but this requires another request (first load) and is subject to the same out-of-sync issue.

**Comment by Morik** [comment]
I'll see, but sadly gives it for 3th party developers who want to include it on many pages (like for the lexikon, the clan administration and a couple of others) or every one (as our bbcode) the downside of larger page size for many requests instead of only a single one.

**Comment by dtdesign** [comment]
Nobody holds you back from using a slightly different approach of piping these class names through a PHP request that will masquerade as a plain JSON file with cache headers, similar to the font delivery mechanism.

There is also the stylesheet API, which lets you examine the rules and extract the FontAwesome icon names from there, so you wouldn't even need to provide them in the template or using an additional file.

**Comment by Morik** [comment]
Well, in that case i'll stick with our API, was just thinking about to switch over.
