### ISSUE TITLE
Implement simple desktop notifications

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2279]
Desktop notifications are widely supported now and provide a decent way to keep users posted.

It would work best with push notifications, but this comes with server-side requirements that aren't available for the absolute majority, hence we'll have to fall back to polling. We should observe this feature and see how we can expand it in the future, including but not limited to server-side push support.

* [x] Add global option to enable desktop notifications.
* [x] Request notification permissions on page load (ahead of time!) for logged-in users only, guests are excluded.
* [x] Poll every 5 minutes, avoids spamming the server with requests and thus avoids being treated as chat-like application, making it work on hosting environments.
* [x] Decrease poll interval based on the activity, based on how long the tab is hidden/suspended.
  * [x] Last activity was more than 30 minutes ago: Decrease interval to once every 10 minutes.
  * [x] Last activity was more than one hour ago: Decrease interval to once every 15 minutes.
  * [x] Actual maximum interval is based on the session keep alive timer, for example if the session expire after 10 minutes, we'll stick with "Every 5 minutes" regardless of the time of last activity.
* [x] Keep track of the last poll time, avoiding stacked notifications from popping up again and again
* [x] If there is more than one new notification, display them with a generic phrase ("X new notifications") to keep notifications on point and to avoid being annoying
* [x] On successful requests, reset the session's keep-alive timer
* [x] Add `window.sessionStorage` based tab communication to avoid parallel requests.
* [x] Store last poll time in user storage and return it with each poll request, avoids cross-origin tabs (e.g. `community.woltlab.com` and `pluginstore.woltlab.com`) from firing notifications in parallel. They should still update all counters, but do not trigger an actual notification.

**Comment by Morik** [comment]
Would be nice to also implement a cross tab communication system to avoid unnecessary requests from multiple tabs.
This way you could synchronize pulling while data is available in all tabs.
In combination with the ability to register server side notifications and listen to them client side it would be a powerful system to combine all kind of polling into a single request.

**Comment by LKDevelopment** [comment]
You could implement Googles Firebase or https://onesignal.com/webpush as an alternative for the notification polling
