### ISSUE TITLE
Add debug method for emails

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2313]
Implementing and testing new emails is a bit cumbersome, the existing methods aren't always helpful as they're designed around sending emails rather than viewing them for debugging purposes.

* [x] Add `Email::debugDump()` to trigger the email build process without actually sending it out, regardless of the email settings.
  * [x] Does not intercept any exceptions, similar to `Email::getEmail()`.
  * [x] Discards the content in the output buffer, similar to the default exception handler.
  * [x] Uses a very simple HTML output with `<h1>` for sections, it needs to be readable, not fancy.
  * [x] Prints the headers in a linear list using `<pre>`.
  * [x] Output thes plain text mime part using `<pre>` (optional).
  * [x] Shows the HTML part rendered in the browser, ideally inside a `<div>` with width limitations to mimic the mail client behavior. It doesn't need to be perfect, but give a general idea on the visual appearance.
  * [x] Terminate the request using `exit;` to avoid any further output being generated.

**Comment by TimWolla** [comment]
646a71d389ddf7ff2370a3deb32905b88363c306
