### ISSUE TITLE
Trophies

### ISSUE THREAD

**Issue by joshuaruesweg** [WoltLab/WCF#2315]
* [x] add trophy module
* [x] add trophy permissions 
    * [x] can view trophies 
    * [x] can manage trophies 
    * [x] can award trophies
    * [x] max sidebar trophies 
* [x] add trophy categories 
* [x] add trophy privacy for users (users can select, whether other users can see their trophies)
* [x] add `earned trophies` overlay for users 
* [x] auto assign trophies feature
    * [x] add user conditions to assign trophies  
* [x] add possibility to add certain trophies to the message sidebar
* [x] add custom trophy descriptions 
* [x] add activity event for receiving a trophy
* [x] add trophy conditions
    * [x] condition for trophy points 
    * [x] condition whether the user have a certain trophy  
* [x] add user trophy box type 
* [x] add receive trophy notification 
* [x] add trophy list page
* [x] add user trophy list page
* [x] font size is to big for `.trophyIcon.icon48`

**Comment by darkwood-studios** [comment]
really great to see this here. Good job josh!

**Comment by jens1o** [comment]
You may want to add a notice, so if you want to create a trophy without a category, you're forced to create a category first(like the label warning).
