### ISSUE TITLE
Missing recognition of legacy controllers

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2323]
Legacy controllers such as `index.php/FooBar/` are currently not recognized and cause a strange redirection behavior. These links should be rewritten internally before passing them to the routing system.

**Comment by jens1o** [comment]
which versions are affected by this? Both 3.0 and 3.1?

**Comment by dtdesign** [comment]
The routing system remained unchanged for 3.1, therefore this affects both versions alike.
