### ISSUE TITLE
Disallow search for updates when benchmark is enabled

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2326]
The performance penalty is far too high and causes the operation to fail on less powerful webspace accounts.

**Comment by mutec** [comment]
Please add a warning-message for that case (acp-index e.g.). I think at least 50% of the users won't remember this situation.

**Comment by KittBlog** [comment]
Alternatively, why not just disable the benchmark in this case? You have to chose to disable one option and personally I think the search for updates is much much more important than the benchmark.

**Comment by dtdesign** [comment]
The benchmark shouldn't really be enabled at all in production, its main purpose is to quickly identify (potential) bottlenecks. Its use is also somewhat limited unless the debug mode is enabled, which causes the benchmark to track even more data.

Besides that, the benchmark (as well as the debug mode) option has been moved into the new development options section anyway, potentially keeping users from flipping that switch at all.
