### ISSUE TITLE
Add developer tools

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2331]
* [x] Add an additional option and option category, and move both, the debug mode and the benchmark, into that category too.
* [x] Implement a project management system to register repositories.
* [x] Add a sync feature for projects, allowing for quick imports of individual PIPs, most notably XML-based PIPs.
* [x] Introduce a bulk sync operation to invoke all PIPs one after another.
  * [x] Add explicit dependencies for PIPs to influence the execution order.
* [x] Implement a dedicated interface to mark PIPs in an opt-in-manner to be available for quick import, requiring them to be idempotent.
* [x] Validate the repository for compatibility:
  * [x] `excludepackage` must be present and exclude the next release.
  * [x] May not exclude the current version, avoiding issues with incorrect branch selection with VCS.
* [x] Include JavaScript CLI-based tools to ease certain development aspects:
  * [x] Disable editor autosave (using localStorage) for testing.
  * [x] Enable logging when events are fired.
  * [x] Whatever could be useful too!

**Comment by Morik** [comment]
Would be nice to have some helpful development output, like fired events etc over the console.
This way you could simply look which events fire to check wether you can use them or not.

**Comment by dtdesign** [comment]
You're talking about JavaScript events (`WCF.System.Event` / `EventHandler`), right?

**Comment by Morik** [comment]
Yes, as there is no clear structure when and where an event gets fired, its quite useful to have an output to actually see them firing.
