### ISSUE TITLE
Generic wrapper for `parse_url()`

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2336]
`parse_url()` has some quite annoying quirks when it comes to the presence of certain components, making code extra complex. Instead of leaving out some array keys, the wrapper should be far more reliable and consistent:

```
// returns true if the provided url can be parsed by `parse_url()` at all (basic check)
\wcf\util\Url::is($url) : bool

// parses an url and returns an Url object that can be accessed like an array, containing all possible components
// values may be empty and `isset()` returns false for empty values
\wcf\util\Url::parse(string $url) : \wcf\util\Url

// returns true if all provided components exist and are non-empty
\wcf\util\Url::contains(string $url, mixed[] $components) : bool
```

Possible components are represented through ~class constants~ generic `PHP_URL_*`-constants. Also supports string based array offsets.

**Comment by jens1o** [comment]
Why did you decided not to deprecate https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/util/FileUtil.class.php#L304-L312 or change the usages of it?
