### ISSUE TITLE
Sending a smylie in the contact form results into an awkward reading for the admin

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2353]
![image](https://user-images.githubusercontent.com/11234139/28637680-ace805ae-7242-11e7-9943-325b32239ba3.png)
Well... Meh. Maybe you can use the alt-text, or add the smylie as an attachment and include it there?

btw, why is the subject `Neue Nachricht über das Kontakt-Formular`, while the hole message is in English?

I typed in `Hello World :)` with the `<textarea>` field shipped with the default installation.

**Comment by jacboy** [comment]
"btw, why is the subject Neue Nachricht über das Kontakt-Formular, while the hole message is in English?"

Because the translations haven't been finished yet. This is still alpha.
