### ISSUE TITLE
Add additional default media providers

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#2357]
* [x] Instagram
* [x] Imgur
* [x] Spotify
* [ ] Google Docs
* [ ] Facebook
* [ ] Twitter
* [x] Twitch
...

**Comment by jens1o** [comment]
What about Smashcast, Mixer, and all these other streaming platforms?

**Comment by LKDevelopment** [comment]
@BurntimeX Why did you implement the providers hardcoded? Would'nt be better to make it with an editable table? So any User can add there own or any plugin?

**Comment by dtdesign** [comment]
@LKDevelopment The media provider are already editable through the ACP, this feature is available since WCF 2.0.

**Comment by jens1o** [comment]
What about Giphy? I'd love to see this. Would be quite funny in some communities :)

**Comment by jens1o** [comment]
Is this still on deck?
