### ISSUE TITLE
Use passive listeners to improve scroll performance

### ISSUE THREAD

**Issue by LucaDev** [WoltLab/WCF#2374]
The usage of passive scroll and touch listeners could improve the scroll performance (especially on mobile devices) by a big degree

https://blog.chromium.org/2016/05/new-apis-to-help-developers-improve.html
https://developers.google.com/web/updates/2016/06/passive-event-listeners

**Comment by dtdesign** [comment]
Thanks for bringing this up.

This is very well known to us, but passive listeners disable the ability to use `event.preventDefault()`, something that the few `scroll` listeners we have are actively using.
