### ISSUE TITLE
Force `display_errors = On` with opt-out

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2375]
The already famous "white page" has been around far too long, and users are still struggling to retrieve the actual error message due to bad error-log configurations. This causes otherwise simple fixes to turn into a lengthy process before the user is finally able to find the related error message.

* [ ] Invoke `ini_set('display_errors', 'on')` before establishing a connection to the database, if the constant `WSC_FORCE_DISPLAY_ERRORS` is defined and set to `true`.
* [ ] Add the line `define('WSC_FORCE_DISPLAY_ERRORS', true);` to the end of the `config.inc.php` in the Core's directory, allowing users to opt-out without having their changes overwritten.

**Comment by jens1o** [comment]
Can we instead opt-in? I don't would like to toggle it off again. It's like the `Normal` setting in setup programs, where all data will be transferred to the owner, regardless whether I want that or not. I know, there is some reason, but still modifying a bit of the software's code is quite easier than trying to find log files.
