### ISSUE TITLE
PasswordUtil::secureRandomNumber does not use `random_int` when it is available

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2379]
https://github.com/WoltLab/WCF/blob/ab0e86f5b214190a3e55f53f773d740da7aef73a/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L251-L274

Maybe you can consider letting php generate the random number(using `random_int`), because it looks to be quite solid, powerful and provides real randomness.

Offtopic: Why is that method in `PasswordUtil` rather than in `CryptoUtil`?

**Comment by jens1o** [comment]
will this be merged into 3.0, too?

**Comment by TimWolla** [comment]
> will this be merged into 3.0, too?

I opted not to, because the patch neither is critical, nor fixes a bug.
