### ISSUE TITLE
Try ... catch missing

### ISSUE THREAD

**Issue by ChristopherWalz** [WoltLab/WCF#2384]
https://github.com/WoltLab/WCF/blob/1145bd7aa0c4dc57ad859dce3641c01ec390ba5e/wcfsetup/install/files/lib/form/LostPasswordForm.class.php#L102

**Comment by ChristopherWalz** [comment]
Also:
https://github.com/WoltLab/WCF/blob/cb955f4e3b9d7283d5593696982860249f7003d9/wcfsetup/install/files/lib/system/cronjob/DailyMailNotificationCronjob.class.php#L205
https://github.com/WoltLab/WCF/blob/cb955f4e3b9d7283d5593696982860249f7003d9/wcfsetup/install/files/lib/system/user/notification/UserNotificationHandler.class.php#L672

**Comment by dtdesign** [comment]
The raised `CryptoException` is intended to abort the execution.
