### ISSUE TITLE
Comment Editor does not have an `accesskey` attribute

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2394]
https://github.com/WoltLab/WCF/blob/5797d648bc8084bc47442518b94e8f2356005c69/com.woltlab.wcf/templates/commentEditor.tpl#L9

**Comment by dtdesign** [comment]
Doesn't matter, the access key is stripped on runtime anyway, because it is handled via JS instead.

**Comment by jens1o** [comment]
Thanks :)
