### ISSUE TITLE
Add CSS and new variables for the new content container

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2406]
* [x] Add basic styles
  * [x] Handle visuals for empty pages (e. g. ACP login)
* [x] Add new style variables for:
  * [x] `containerBackground`
  * [x] `containerBorder`
* [x] Adjust visual style editor

The changes are only partially backwards-compatible, requiring an optional toggle to enable these modifications per style. The default CSS is not modified, instead a new SCSS file is added which holds the difference to the previous version. This comes at the price of overwriting existing styles, but gives us more freedom to advance the style without interfering with legacy styles.

* [x] Add `<apiVersion>` to styles that allows for the values `3.0` and `3.1`.
  * [x] New styles should default to `3.1`.

**Comment by jens1o** [comment]
Can you make it optional, pleeeaaaassseeeee? 😗
