### ISSUE TITLE
Introduce limited forward-compatibility for plugins

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2427]
Plugin compatibility is always a bit of an issue and a common source of frustration. There are two distinc safe-guards in place that limit the compatibility through the `<requiredpackages>` and `<excludedpackages>` elements, and especially the later one can become a real issue.

Plugins can set a maximum version by excluding the next version of a plugin/app/the core itself through `<excludedpackages>`, but this declares the next version to be incompatible no matter what. There is nothing wrong with it, when the next version comes with breaking changes that (will most likely) prevent the plugin from working, because it was designed for exactly this purpose.

However, this mechanic does not factor in that the next version may be fully backwards-compatible, that is, without breaking the existing API. In this particular case, it is desirable to allow the installation with the next version, because there is no need for an updated version of the plugin. While this restriction can be removed for actively maintained plugins in little to no time, things become more and more a problem with unmaintained and/or less-active plugins.

These plugins do not necessarily become incompatible or unsafe to use, which makes them ideal candidate for limited forward-compatibility, that is merely a promise that the plugin will keep working if the existing API does match the previous one for which the plugin was originally created.

We'll fill this gap by introducing an additional mechanic called "API version" that can be defined in the `package.xml` to indicate the compatibility with specific versions of the core API. Additionally, plugins have access to the API version through a PHP- and JavaScript-constant to allow for conditionals when accessing newer API features.

* [x] Implement the `<compatibility>` element for the `package.xml`.
* [x] Validate the provided versions during installation.
  * [x] Reject packages that lack these data if (and only if!) the developer tools are enabled.
* [x] Expose the API version through a PHP- and JavaScript-constant, dubbed as the `2018` API (backwards-compatible with the `2017` API).
  * ~[ ] Backport the constants to WoltLab Suite 3.0 for compatibility, dubbed as the `2017` API.~
* [ ] Implement support for compatible API versions other than the current one.
* [x] Update the update server API to include the compatibility versions.

**Update 2017-09-29:** Decided against a backport of the API version constant to the 3.0 series, because it would require backporting the entire `<compatibility>` processing. This is caused by the fact that the compatibility data is only present during an installation/update, causing it to be not present when upgrading to 3.1, because the data was never collected in the first place.

**Comment by jens1o** [comment]
> ` Implement support for compatible API versions other than the current one.`

What's going on with this?

**Comment by dtdesign** [comment]
This isn't relevant at this time.

**Comment by jens1o** [comment]
Which means that there is more additional work needed once you publish a newer version. :/

**Comment by dtdesign** [comment]
I'm sorry?
