### ISSUE TITLE
Implement a generic key/value storage

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2467]
The key/value storage is designed for values that need to be stored, but are rarely ever requested. Values will be read per package id and on request, so using it has the performance penalty of querying the database. Caching is explicitly not available.

* [ ] Use a simple string-based table layout: `packageID`, `key` and `value` (using `mediumtext`).
* [ ] Content is never deleted, unless explicitly requested or package was uninstalled.
* [ ] Requesting data will always load all data from the same package into a runtime cache.
* [ ] There is no persistent cache, requesting data will always cause one database query per package.
* [ ] No database object implementation is available, all requests go through a single handler object.

**Comment by LKDevelopment** [comment]
@dtdesign Why no caching? And why do you query it once per package instead of once per Application Init? (1 Query instead of 1*Count of Packages). You could cache it on a Request Cache Basis, (like an Array)

**Comment by dtdesign** [comment]
Caching makes no sense, because retrieving a cache file (especially from the filesystem) is always slower than fetching it from the database. Additionally, there is no pre-processing involved, causing the potentially cached values to be identical to the data received from the database. That said, the cache would decrease the performance in this particular case.

In regards to the number of queries, it doesn't make sense to load the entire table contents, because you'll only need a fraction of it. For example, the individual CSS/SCSS currently reads the value directly from the file, which does have a few potential drawbacks. Saving it in a generic key/value storage is a more reliant and persistent solution, but retrieving this particular value is almost never required.

I'm even somewhat leaning towards querying each value separately, with the option to request them in bulk. The important point here is that "at worst" using multiple database queries could actually be the fastest solution. The total query count on its own is a nice looking, but worthless metric.

**Comment by jens1o** [comment]
The documentation for this is still missing, unfortunately. Am I supposed to file an issue?
