### ISSUE TITLE
Adding/editing boxes is broken due to a faulty merge

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2470]
See https://github.com/WoltLab/WCF/commit/8ca34496b315ef46e6259df164dc8d89cfed0bfa#commitcomment-25531116

**Comment by Gravatronics** [comment]
@dtdesign https://github.com/WoltLab/WCF/commit/be3a8e90cb326f1805d94a8ec802535c2cb87a21 ?

**Comment by dtdesign** [comment]
Thanks, looks like I used a slightly outdated version for testing.
