### ISSUE TITLE
Improve the unattended installation process for developers

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2477]
The currently existing developer mode for the WCFSetup process is still somewhat manual and requires more manual interaction than there really should. There are some short-cuts using environment variables, but they don't solve it completely, or at least have limitations when it comes to fully automated customizations.

* [x] Add support for a configuration file that is placed in the document root: `wsc-dev-config-<version>.json`.
* [x] Automatic database configuration:
  * [x] Generate the database name based on the install path (for example, `https://localhost/w/547/` becomes `w_547`).
  * [x] Create the database on-the-fly.
  * [x] Non-default value for `WCF_N` to detect hard-coded `wcf1_`-table references.
* [x] Skip the install path configuration by using the suggesting values automatically.
* [x] Allow custom option overrides that will be applied at the end of the installation.
* [x] Create a set of new users with regular permissions for testing purposes.

The example configuration below will be added to the `extra/examples/` directory in the repository root:
```json
{
    "setup": {
        "database": {
            "auto": true,
            "host": "localhost",
            "password": "root",
            "username": "root",
            "dbNumber": "2"
        },
        "useDefaultInstallPath": true
    },
    "configuration": {
        "option": {
            "captcha_type": "",
            "module_cookie_policy_page": "0"
        }
    },
    "user": [
        {
            "username": "test",
            "password": "test",
            "email": "test@example.com"
        },
        {
            "username": "test2",
            "password": "test",
            "email": "test2@example.com"
        }
    ]
}

```

**Comment by jens1o** [comment]
Is this being used in the future by WoltLab's demo system?

**Comment by dtdesign** [comment]
No, the demo system is based on a template-style approach where a cleaned-up installation exists on disk and is duplicated and adjusted for each new installation.

This change is about easing the deployment process for development. I've lost count of the total number of installations I've run, but I'm more than confident that this number is north of 2k. At some point I started giving continuous numbers to the installations, and whenever I reinstall the system I start off with 1 again. Currently I'm working with `/w/547/` since the upgrade to Windows 10 :)
