### ISSUE TITLE
Implement user cover photos

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2484]
* [x] Add a module setting to disable cover photos entirely, also add a CSS class to indicate cover photo support in the user profile/popover when enabled.
* [x] Images need be sufficiently wide (at least 5:1) to scale nicely on all screen sizes, enforce a set of minimum and maximum dimensions.
  * [x] Support only JPG, PNG and GIF to allow for server-side processing.
* [x] Image is always centered and scaled using `background-size: cover`, provides the most reliable appearance across all screen sizes.
* [x] Editing takes place inside the user profile using a dialog overlay.
* [x] Add a permission to view the photos, fallback to the default image.
  * [x] Store photos similar to user avatars by utilizing a random SHA-1-hash in order to prevent filename guessing.
* [x] Allow the feature to be temporarily restricted per user, similar to the avatar or signature.
* [x] Each style can define its own default cover photo.
  * [x] Include the cover photo in the style export.

**Comment by jens1o** [comment]
It's sure that this is 3.1?

**Comment by jacboy** [comment]
Nice to see this is back again after over a year. Would be a great thing if you could share some screenshots in the community when it's ready :P
