### ISSUE TITLE
Enhance guest UI for comments

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2502]
* [ ] Creating a response to a comment will bring up the username dialog again but displays the input field to be erroneous.
* [x] The overlay is missing any sort of cancel button.
  * [x] It is currently possible to close the dialog by pressing `[Esc]`, but this leaves a stray loading indicator.
* [x] Submitting a reply to a comment causes the editor not to be hidden.

**Comment by Gravatronics** [comment]
See #2505 regarding closing the dialog via `[ESC]`.
