### ISSUE TITLE
Form Builder API

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2509]
> Creating forms requires quite a redundant set of HTML tags and template scripting in order to provide a consistent UI/UX. This repetitive task is prone to errors and can easily lead to code duplicates that gradually become out-of-sync when changes are made.

In addition, the PHP code is also very similar for many form fields and not infrequently, the same exact for field is used in more than one place.

**Disclaimer:** This issue, at this point in time, contains early ideas about a form builder API. Nothing mentioned in this issue is guaranteed to be implemented at all or in the described way.

See https://github.com/WoltLab/WCF/tree/formBuilder

## Idea

Every form field is represented by a PHP object of an appropriate class that handles reading and validating the field value and outputting the field using a template. Fields can be grouped by containers. The implementation of the form nodes is inspired by JavaScript’s DOM.

## API

A first draft of the API can be found [in this Gist](https://gist.github.com/Gravatronics/7ac3f332ca0f570aadee1370380cc5fb).

![formbuilderapi](https://user-images.githubusercontent.com/917663/34421181-159b5b06-ec0e-11e7-8814-a83432fff592.png)

### Form Structure

The three interfaces `IFormDocument`, `IFormContainer`, and `IFormField` represent the (tree) structure of the form with `IFormDocument` being the root and `IFormField` being the leafs.

In addition to a simple form container, a more complex example of a form container is a tabbed container whose (container) children are interpreted as tabs.

For each relevant "simple" input type (single-line text, multi-line text, booleans, selections, …), a field (type) has to be implemented (`TextFormField`, …) but fields can also represent more complex inputs like tags or ACL settings.

### Validators and Validation Errors

Each field will support intrinsic validation handled by the `IFormNode::validate()` method. As a specific field might require validations specific for this field only, instead of creating a new form field class, a new `IFormFieldValidator` can be added to the field via `IFormField::addValidator()`.

If a validation step, be it an intrinsic one or one by an external validator, a new `IFormFieldValidationError` object representing the occurred error is added to the form field via `IFormField::addValidationError()`.

### Dependencies

Simple forms show all available fields to the user. More complex forms, however, might have “components” (`IFormElement`s) that should only be visible if a certain field has a specific value. For example, when creating a box, the box title can be linked. The field to enter an extern link will only be shown if the box title should be linked and “External Link” is selected as link type.

### Data Processors

Forms work with instance of database object actions that require a `$parameters` array with a certain structure. Most data is in the `data` sub-array whose keys are the names of the database table's columns and whose values are the new values of the database object's table cells. This default structure is provided by the `DefaultFormFieldDataProcessor` class that checks each field if it has data to save (`IFormField::hasSaveValue()`) and than retrieves the data (`IFormField::getSaveValue()`).

More complex data, for example tags, has to be passed as another entry of the `$parameters` array (and not in the `data` sub-array). This cannot be achieved by the `DefaultFormFieldDataProcessor` class so that a form field that handle tags can register its own data processor that adds a `tags` entry directly into the `$parameters` array. This data processor is best registered as soon as the field's parent element is set because then, the field can access the form document and thereby also the data handler.

It is now expected that database object actions are able to save all relevant data associated with the created/updated object, including i18n values and acl settings, for example.

To retrieve the data, `IFormDocument::getData()` should be used, not `IFormDocument::getDataHandler()->getData()`.

### Loading Existing Data

When editing objects, existing field values need to be added to the fields. To avoid having to call `IFormField::value()` on each field and manually set the value, `IFormDocument::loadValuesFromObject(IStorableObject $object)` that internally calls `IFormField::loadValueFromObject(IStorableObject $object)` for each field. As the default behavior, `IFormField::loadValueFromObject(IStorableObject $object` will check if the passed object has a property with the same name as the field's id and if so, uses that property's value as field value. Fields with more complex data, for example tags (see above), can overwrite this method to fetch the field values from another API, for example.

## Details

- There is no `cleanup()` method to clear the fields after creating a new object. It is expected that the same new `IFormDocument` is created as for the first request.
- Data that is not saved in a column of the database object's table is expected to be passed as "direct" parameters to the database object action, i.e. not in the `data` sub-array, so that the object action itself should take care of saving this data. Example:

  ```php
    <?php
    // …
    [
      'data' => [
        // `data` sub-array
      ],
      'additionalParameter' => 'someValue'
    ]
- [x] Add an `objectProperty` property to form fields that allows having multiple form fields that read from and save into the same property of a database object. This property is only used when setting the value in `loadValueFromObject()` (note: here, `\InvalidArgumentException` should be ignored if `objectProperty` is used) and when the data processor is collecting the data.
  One use case is using `ShowOrderFormField` on a nested structure. A nested structure generally has a `parentID`. Each parent has different children so that the sibling/option list of the `showOrder` field would have to be updated depending on the selected parent. Implementing this conditional availability of sibling options depending on the selected parent requires quite a bit of additional logic that is already available via the form field dependencies.
  Using form field dependencies, for each parent, a distinct `showOrder` field is created with id `showOrder_{parentID}`. Without `objectProperty`, the database object action would be passed a data array element with key `showOrder_{parentID}` instead of the expected `showOrder`. Giving all `showOrder` fields the same id, on the other hand, is impossible as node ids must be unique. With `objectProperty`, however, all `showOrder` fields get `objectProperty = 'showOrder'` so that the database object action will be passed a data array element with key `showOrder` – as expected.
- [x] The API should not only be usable for normal requests but also for AJAX requests. To support such requests, the fields may not directly dependent on reading their data from `$_POST` as for AJAX requests, the relevant data is generally stored in either `$_POST['parameters']` or `$_POST['parameters']['data']`. Instead, a method of `IFormDocument` like `getRequestData(string $field = null)` should be used.
- [x] Filtering of `SingleSelectionFormFields` that are indented does not work properly. Indentation has to be realized using CSS instead of multiple `&nbsp;`s. The form field has to be explicitly informed about the indentation levels of the available options (with no indentation being the default).
- [x] `ValueFormFieldDependency::values()` should allow functions as parameter values (see `ISelectionFormField::options()`).


## Form Fields

The following form fields should be supported:

- [X] `acl`
- [X] `boolean`
- [x] `captcha`
- [x] `date`
- [X] `float`
- [x] ~~`file` / `image`~~ (moved to #2825)
- [x] `icon`
- [X] `integer`
- [x] `itemList`
- [X] `multilineText`
- [x] `multiSelection`
- [x] `radioButtons`
- [x] `simpleAcl`
- [X] `singleSelection`
- [x] `tags`
- [X] `text`
- [x] `wysiwyg`

### Commonly Used Form Fields

For commonly used form fields, there should be own classes with presets so that only the object needs to be created without calling methods for setting it up.

Examples:

- [x] `username` (for non-existing usernames)
- [x] `user` (for existing users)
- [x] `title`
- [x] `description`
- [x] `isDisabled`
- [x] `showOrder` (may-be, instead of integer input field a selection to select its direct neighbor)
- [x] `sortOrder` (`ASC` and `DESC`)


## Finishing Implementation

- [x] Check required fields hidden due to dependencies.
- [x] Check that all (error) language item exist.
- [x] Make sure that `isImmutable()` is checked for all fields.
- [x] Update official documentation

**Comment by jens1o** [comment]
Could you add the possibility to add a suffix(`chars`, `pixel` and so on)?

**Comment by jens1o** [comment]
I saw you implemented `inputSuffix`es. Do you also want to add support for prefixes?
https://github.com/WoltLab/WCF/blob/e8dfe26a3bd8e751210f6f1f677cd56ff3aa19a4/wcfsetup/install/files/style/layout/form.scss#L198
