### ISSUE TITLE
Guard against requests to the frontend while WCFSetup is running

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2510]
Every so often an installation fails because the frontend is being accessed by an unrelated visitor or search engine, causing some internal caches to be populated before they're supposed to be. This can cause the installation to fail with a bogus error message, eventually forcing the user to reinstall - while still being at risk of suffering from the same issue.

We should try to work around this issue by some kind of forced exit that terminates the execution while the setup is still active. Locks based on file existence (e.g. some kind of `lock.txt`) are error-prone and increase the latency of every request, making them the least favorable option.

Also consider marking applications as tainted as long as the installation process is running - just make sure to flip the flag at the end.

**Comment by jens1o** [comment]
What about injecting some kind of termination message after the files have been unzipped in the newly created `index.php`? And as soon as the setup is done, it could be restored to the original file.

**Comment by dtdesign** [comment]
Thought about deploying custom code into the `options.inc.php` that checks for some kind of constant. This could work because the WCFSetup uses a static options file that was deployed during the pre-ACP setup.

**Comment by jens1o** [comment]
why this has been delayed to the next minor?

**Comment by dtdesign** [comment]
Some of my initial assumptions have turned out to be false and/or incomplete. Considering that this can affect the installation of apps too, we need to find a different strategy to avoid early cache population, but this directly interferes with the cache behavior during an installation process.

There's simply too much attached to it and there is a significant risk of breaking the entire installation process. That said, I'm not even certain anymore that we can resolve this without introducing some sort of breaking change, eventually it boils down to a design flaw in the isolation layer of the package installation itself.
