### ISSUE TITLE
[Proposal] PSR-0 / PSR-4 autoloading using Composer for WCF / WoltLab

### ISSUE THREAD

**Issue by timonf** [WoltLab/WCF#2520]
Dear WoltLab community,

This is just a proposal for the future: It would be better, if WoltLab use only one autoloader: The composer's one with an industrial standard: The PSR-0 or PSR-4 autoloading standard! At the moment there are multiple autoloaders inside of WoltLab:

* WoltLab's native autoloader
* [Composer's autoloader](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/api/composer.json) (included [here](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/WCF.class.php#L62).)

It would nice to have only the second autoloader. Why WoltLab should use Composer Autoloader?

* Some WoltLab classes could be reused in other php files.
* It's easier to add 3rd party libraries
* WoltLab can be used inside other frameworks (like Symfony)
* WoltLab can be used in tests

What are the todos to use Composer as an autoloader for WoltLab?

* This is the big downside: All filenames have to be renamed (`Slug.class.php` to `Slug.php` to be ready for the PSR-4 autoloading standard)
* Add a composer.json to the root (maybe the other one can be moved, and vendor directory can point to the "api" directory)
* Plus: No namespace or directory have to be changed :)

Here is a quick example (test.php to load Composer's autoloader, a renamed Slug class and the composer.json itself):

![image](https://user-images.githubusercontent.com/546813/35158233-cb685dba-fd36-11e7-8f20-352fb0eafd17.png)

Please let me know, what you think about this change! I think the biggest challenge is to rename all files to remove the `.class` postfix. Composer is not a big deal, because it's already integrated in the "lib/system/api" directory.

I don't know what to do with plugins and such things. I'm very new to WoltLab.

I hope we can have a nice discussion on this propossal :)

Regards
Timon

**Comment by theparthy** [comment]
i second that

**Comment by dtdesign** [comment]
This is something we plan to do in the future, but right now it would cause a massive b/c-break without any significant benefits.
