### ISSUE TITLE
Built-in evaluation notice

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2532]
The current practice of embedding evaluation notices into each app has a lot of downsides, including but not limited to the stacking and the lack of an extended explanation. Adding a more general evaluation notice that can be enabled through an app avoids the usual issues that came with the current approach.

* [x] Apps should report an expiration date that is used for display, grouping apps with the same date.
* [x] The notice should include an explanation on the auto-removal of said expiration once the final version has been installed.

**Comment by jens1o** [comment]
Will the application continue to be responsible for rejecting the request?

**Comment by dtdesign** [comment]
That shouldn't be in the domain of the app at all, and in fact, wouldn't even make sense to implement it this way.

**Comment by jens1o** [comment]
So why did you do that currently? 😋
