### ISSUE TITLE
DevTools: Creating and Editing PIP Entries

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2545]
> Writing PIPs is more or less an annoying task, that requires far too much manual work. Offering a GUI not only eases this process by suggesting the components, but it would also open up the opportunity for inline-help on each element.

**Disclaimer:** This issue, at this point in time, contains early ideas about a PIP GUI. Nothing mentioned in this issue is guaranteed to be implemented at all or in the described way.

## Listing PIPs and PIP Entries

The basis for editing PIP entries is a list of available entries that can be edited. This list is read from the package’s source folder when the list page is requested.

- [x] Add list of all available pips
- [x] Add list of all entries of a pips
- [x] Unify implementations

## Adding and Editing PIP Entries

Every PIP will have a method for each of the different stages of building a form builder form – the most important being the method that appends the form fields to the form object. As the whole form logic is handled by the form object itself, the PIP only comes into play again when it comes to processing the entered data.

“Processing the entered data” in this context means to edit the “data structure” providing the PIP entries (in most cases an XML file) directly to add a new entry or edit an existing entry.

In general, the inline-help mentioned above can be achieved using the form field descriptions.

- [x] Add form for pip entry adding
- [x] Add form for pip entry editing
- [x] Update existing PIP file (or create new one if none existed before)
- [x] Update entry in database
- [x] Ensure extensibility by plugins

### Simple Example

The `ObjectTypeDefinitionPackageInstallationPlugin` would support a form with two fields: the required `name` and optional `interfaceName`. The latter one could potentially support autocompletion for the entered interface name and would have a custom validator to ensure that the entered interface exists. The `name` field could have a custom validator to ensure that the entered name is unique.

### Complex Example

The `ObjectTypePackageInstallationPlugin` would result in a form with greater complexity as many object types support additional fields that are displayed depending on which object type definition is selected.

### Language Items

ACP menu items, for example, require a language item that matches the name of the menu item. PIPs that require language items would be able to allow setting them directly in the form.

### Validation Modes

There are two potential modes when validating inputs:

1. enforcing that referenced data exists, for example a permission or an option, though one would have to be careful to ensure that no circular dependencies arise that would make it impossible to create certain entries,
2. only warning that referenced data does not exist yet.

## Supported PIPs

- [x] `ACLOptionPackageInstallationPlugin`
- [x] `ACPMenuPackageInstallationPlugin`
- [x] `ACPSearchProviderPackageInstallationPlugin`
- [x] `BBCodePackageInstallationPlugin`
- [x] `BoxPackageInstallationPlugin`
- [x] `ClipboardActionPackageInstallationPlugin`
- [x] `CoreObjectPackageInstallationPlugin`
- [x] `CronjobPackageInstallationPlugin`
- [x] `EventListenerPackageInstallationPlugin`
- [x] `LanguagePackageInstallationPlugin`
- [x] `MediaProviderPackageInstallationPlugin`
- [x] `MenuPackageInstallationPlugin`
- [x] `MenuItemPackageInstallationPlugin`
- [x] `ObjectTypeDefinitionPackageInstallationPlugin`
- [x] `ObjectTypePackageInstallationPlugin`
- [x] `OptionPackageInstallationPlugin`
- [x] `PagePackageInstallationPlugin`
- [x] `PIPPackageInstallationPlugin`
- [x] `SmileyPackageInstallationPlugin`
- [x] `TemplateListenerPackageInstallationPlugin`
- [x] `UserGroupOptionPackageInstallationPlugin`
- [x] `UserMenuPackageInstallationPlugin`
- [x] `UserNotificationEventPackageInstallationPlugin`
- [x] `UserOptionPackageInstallationPlugin`
- [x] `UserProfileMenuPackageInstallationPlugin`

## Unsupported PIPs

- [X] `ACPTemplatePackageInstallationPlugin`
- [X] `FilePackageInstallationPlugin`
- [X] `ScriptPackageInstallationPlugin`
- [X] `SQLPackageInstallationPlugin`
- [x] `StylePackageInstallationPlugin`
- [X] `TemplatePackageInstallationPlugin`

## Finalization

- [x] Check every PIP implementation (again)
- [x] Check for missing language items
- [x] in BBCode XML files `"` becomes `&quot;`
- [x] Update Language PIP
- [x] Fix adding new options/categories if no options/categories element exists
- [x] Improve handling of object type-specific children when creating xml element
- [x] Add `supportsReactions` support for object types (See #2508)
- [x] Add `disableAutocomplete` support for text options (See #2750)
- [x] Update other packages if necessary
- [x] Use `<kbd>` instead of `<code>` in language items.
- [x] Add German translation
- [x] Update existing XML files after saving all relevant entries and enforcing the format provided when editing via GUI.
- [x] Add missing German translations marked with `TODO:`.
- [ ] Add language item `wcf.acp.pip.page.controllerCustomURL.description`.

**Comment by Gravatronics** [comment]
Can you please explain what you mean by that?

**Comment by jens1o** [comment]
I mean like you created the PIP(for example `eventListener`) using the GUI and now want it to be exported as XML, so you can use it for previous versions of WoltLab Suite, too. So you are able to download the `eventListener.xml` file.

**Comment by Gravatronics** [comment]
There is no need for that. The GUI works on the files directly. Feel free to install the branch and have a look for yourself.

**Comment by jens1o** [comment]
Uh, that's cool. :)
