### ISSUE TITLE
Multidomain: Sitemaps need to be split per app

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2560]
Sitemap links are only recognized if they share the same origin, for example, `https://example.com/sitemap.xml` will cover all links from the host `example.com`, but completely ignores `www.example.com` or `foobar.example.com`.

See https://www.sitemaps.org/faq.html#faq_sitemap_location, but ignore the very last sentence of that faq item because it is proven to be not true.

This requires the sitemap to be split per domain where all links are provided that resolve to the same domain. Since apps can be arbitrarily distributed among subdomains, it makes the most sense to generate one sitemap per app. The downside is that a user has to deal with dozens of sitemaps even if all apps exist on the same domain.

We can resolve this issue by defining a predictable pattern for the sitemap distribution:
* [ ] If all apps use the same domain, generate a single sitemap in the Core directory which covers all apps (this is the current behavior).
* [ ] If at least one app uses a different domain, then the sitemaps are _generated and stored per app_, even if some apps share the same domain.
* [ ]  Include a remark on the "Manage Apps" page that prints the URL to the global sitemap or a list of sitemaps if they are split.

**Comment by jens1o** [comment]
@joshuaruesweg Why did you decided to not fix this failure?

**Comment by joshuaruesweg** [comment]
Since it does not matter for the relevant search engines practically.

**Comment by jens1o** [comment]
About what do we talk about exactly? Sitemaps are useless?

**Comment by joshuaruesweg** [comment]
About splitting sitemaps for domains.

**Comment by dtdesign** [comment]
The specification does say that the sitemap should not include links to other subdomains, but in reality no search engine gives a damn about this and accepts them anyway.

**Comment by jens1o** [comment]
Alright, thanks for clarifying. Some persons say that sitemaps aren't that useful anymore, too.
