### ISSUE TITLE
Restricted OpCache API

### ISSUE THREAD

**Issue by phillipp** [WoltLab/WCF#2562]
Hi,
to prevent Information Disclosures, shared hosting providers should disable Zend OpCache Status API with "opcache.restrict_api" when the OpCache is shared (PHP-FPM for example). A shared hosting user should not be able to see the status (and therefore the cached scripts list). The cached scripts list could potentially leak information (a user might give a file a "secret" name for example). The cached scripts list is shared between all processes in a PHP-FPM master, regardless of the user and the setting of `opcache.validate_permission` and/or `opcache.validate_root`.

With the restricted API, WCF and Woltlab Buring Board is crashing from awarning. Example:

```
Message: PHP warning in file /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/WCF.class.php (821): Zend OPcache API is restricted by "restrict_api" configuration directive 
File: /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/WCF.class.php (309) 
PHP version: 5.6.36 
WCF version: 2.1.21 pl 1 (Typhoon) 
Request URI: /team-speak3-viewer/?s=ZZZZZZZZZZZZZZZZZZZZZZ 
Referrer: 
User-Agent: Mozilla/5.0 (compatible; SemrushBot/1.2~bl; +http://www.semrush.com/bot.html) 
Information: "" 
Stacktrace: 
#0 [internal function]: wcf\system\WCF::handleError(2, 'Zend OPcache AP...', '/home/webpages/...', 821, Array) 
#1 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/WCF.class.php(821): opcache_invalidate('/home/webpages/...', true) 
#2 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/cache/source/DiskCacheSource.class.php(81): wcf\system\WCF::resetZendOpcache('/home/webpages/...') 
#3 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/cache/CacheHandler.class.php(88): wcf\system\cache\source\DiskCacheSource->set('wcf_ClicksRecor...', Array, 300) 
#4 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/cache/builder/AbstractCacheBuilder.class.php(43): wcf\system\cache\CacheHandler->set(Object(wcf\system\cache\builder\ClicksRecordCacheBuilder), Array, Array) 
#5 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/event/listener/ClickListener.class.php(45): wcf\system\cache\builder\AbstractCacheBuilder->getData() 
#6 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/event/EventHandler.class.php(141): wcf\system\event\listener\ClickListener->execute(Object(wcf\page\TeamSpeak3ViewerPage), 'wcf\\page\\TeamSp...', 'readParameters') 
#7 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/event/EventHandler.class.php(173): wcf\system\event\EventHandler->executeInheritedActions(Object(wcf\page\TeamSpeak3ViewerPage), 'readParameters', 'wcf\\page\\TeamSp...', 'readParameters@...', Array) 
#8 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/page/AbstractPage.class.php(108): wcf\system\event\EventHandler->fireAction(Object(wcf\page\TeamSpeak3ViewerPage), 'readParameters') 
#9 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/page/TeamSpeak3ViewerPage.class.php(28): wcf\page\AbstractPage->readParameters() 
#10 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/page/AbstractPage.class.php(99): wcf\page\TeamSpeak3ViewerPage->readParameters() 
#11 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/request/Request.class.php(58): wcf\page\AbstractPage->__run() 
#12 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/wcf/lib/system/request/RequestHandler.class.php(139): wcf\system\request\Request->execute() 
#13 /home/webpages/lima-city/XXXXXXX/YYYYYYYYYY/index.php(10): wcf\system\request\RequestHandler->handle('wbb') 
#14 {main}
```

We advise our customers to change `protected static $zendOpcacheEnabled;` to `null` in `wcf/lib/system/WCF.php`, but that is only temporary because the update overwrites the changes.

Would it be possible to change WCF to make is easier to run in a shared webhosting environment with secure defaults (problem is: PHP-FPM + secure defaults seem not to be very wide spread)?

What would the best solution look like?

**Comment by dtdesign** [comment]
Restricting the opcache API isn't a solution, because it will render the system unable from selectively flushing files on cache reset or when other changes via PHP are performed. It is an absolute requirement that the software is able to reliably flush files between two consecutive requests, otherwise you'll end up breaking a lot of things.

In general, the cache is reset via `opcache_invalidate()` (selective purge) and in some rare cases using `opcache_reset()` in case the changed files cannot be reliably determined.

Have you considered using `disable_functions` instead to prevent access to potentially dangerous functions such as `opcache_get_status()`?

> We advise our customers to change `protected static $zendOpcacheEnabled;` to `null` in wcf/lib/system/WCF.php, but that is only temporary because the update overwrites the changes.

`null` is the default value, so what change are you suggesting to your customers?

PS: opcache in shared hosting is a bad idea in general, it leaks a lot of information between apps running on the same instance, for example, paths are stored relative to the chroot dir and thus exposing cached versions from different hosts with the same relative path.

**Comment by phillipp** [comment]
Sorry, I meant "false" instead of "null", my fault.

Disabling the function itself seems like one idea, certainly easier than modifying the PHP sources.

Do you have an example for "it leaks a lot of information between apps running on the same instance,"? We don't use chroots, otherwise we'd enable validate_root.

**Comment by dtdesign** [comment]
> Do you have an example for "it leaks a lot of information between apps running on the same instance,"? We don't use chroots […]

Opcache uses the absolute file path of the PHP file to store the cached byte code, which isn't much of a big deal. Unless you are working with php-fpm's built-in chroot which (you might have guessed it) alters the root directory for the process.
* `/var/customers/abc/www/config.php`
* `/var/customers/123/www/config.php`

If you now enable chroot and set it to the `www` part of each customers, then the absolute path of both PHP files will now be `/www/config.php`. Congratulations, opcache can now no longer tell those two files apart, in fact it treats them both to be the same. If request 1 hits the `config.php` of the customer "abc" and the next request will require 123's config.php, then opcache will serve the cached version from abc's `config.php`.

_… and yes, I failed for this more than once. Shame on me._

**Comment by phillipp** [comment]
Ah yes, I know that problem. exactly what the config setting opcache.validate_root is made for ;-)

Luckily, you don't need chroots any longer for shared hosting, customer separation is much easier with MAC via AppArmor now :-)

I'll close this one, thanks for the help.
