### ISSUE TITLE
Broken exception output in cli mode

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#2569]
In cli mode exceptions are shown as html.

**Comment by TimWolla** [comment]
Cannot reproduce this. CLI specifically sets a different Exception handler:

https://github.com/WoltLab/WCF/blob/cef4d328b4fe5a330abbdfda4c0269dbcfa0dbb5/wcfsetup/install/files/lib/system/CLIWCF.class.php#L25
