### ISSUE TITLE
Custom sort order for articles per category and a box for random articles

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2592]
* [x] Allow different sort orders, such as alphabetic ~or randomized~ ordering.
* [x] New box controller that displays a random article (teaser).

See https://community.woltlab.com/thread/257431-artikel-reihenfolge-und-zufallsartikel/

**Comment by joshuaruesweg** [comment]
https://github.com/WoltLab/WCF/commit/10eeeb808b153a98049e461358d6a7a2f022f642
