### ISSUE TITLE
The `XML` class is too restrictive and does not allow access to the doc and its schema

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2646]
n/t

ref https://community.woltlab.com/thread/266561-xml-util-%C3%BCberarbeiten/

**Comment by Gravatronics** [comment]
Note: A `XML::getDocument()` method already exists in the `pipGui` branch.

See https://github.com/WoltLab/WCF/blob/26a29e3558bc1df2735375327d9429138332df8b/wcfsetup/install/files/lib/util/XML.class.php#L200-L208
