### ISSUE TITLE
Notify on new logged errors by email

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2654]
* [x] Notify the administrator once per day if one or more errors have occured.
* [x] Track the timestamp of the last notification, set it to `TIME_NOW` whenever the exception view page is accessed.
* [x] The check is performed at 5 am in the morning and includes everything since the tracking timestamp.

ref https://community.woltlab.com/thread/266608-exceptions-wahlweise-per-e-mail-versenden/

**Comment by jens1o** [comment]
> Notify the administrator once per day if one or more errors have occured.

Wouldn't it make sense to notify them every time, so in case the delivering fails the Administrator is not in the false belief that everything is working fine just because the Software does not report any errors?

**Comment by dtdesign** [comment]
It will use the background queue, so it would re-try to send the email in case of a connection issue or other kind of errors that would prevent this function from working properly.

Sending out emails everytime is a dangerous action, as it can cause a significant amount of load on the system. Especially in situations where the software is struggling due to resource constraints, such a feature would be the so-called "nail in the coffin", effectively turning into a self-DoS.

Restricting it to just once per day is a bit of a middle ground, reporting issues in a timely manner without having a significant impact on the day-to-day operation.
