### ISSUE TITLE
Auto-pruning for ip addresses

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2656]
n/t

ref https://community.woltlab.com/thread/267451-cron-der-ip-adressen-je-nutzer-l%C3%B6scht/
ref https://community.woltlab.com/thread/268399-dsgvo-option-ip-speichern-erweiterung-um-zeitraum-nach-dem-alle-gespeicherten-ip/

**Comment by TimWolla** [comment]
While the Subject field cannot be deleted (`originIsSystem`) it can be disabled, renamed and edited.

It might be required to special case it, but it might not be possible to clearly identify it during the upgrade.
