### ISSUE TITLE
Use the subject field value in the contact form in the email's subject line

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2661]
n/t

ref https://community.woltlab.com/thread/268282-kontakt-formular-betreff-f%C3%BCr-das-subject-der-e-mail-nutzen/

**Comment by TimWolla** [comment]
While the Subject field cannot be deleted (`originIsSystem`) it can be disabled, renamed and edited.

It might be required to special case it, but it might not be possible to clearly identify it during the upgrade.
