### ISSUE TITLE
Detect ImageMagick during the setup process

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2684]
* [x] GD should no longer be a requirement, imagemagick should be accepted as a substitute.
* [x] Enable imagemagick during the setup if it is available.
* [x] Prefer imagemagick over GD for obvious reasons.

ref https://community.woltlab.com/thread/263624-installationsroutine-imagemagick-pr%C3%BCfen/

**Comment by mutec** [comment]
@TimWolla http://php.net/manual/de/function.getimagesize.php
The German version says the library is not needed for that method. Are they talking about another library?
> Hinweis:
> Diese Funktion benötigt die GD-Bibliothek nicht.

**Comment by TimWolla** [comment]
> the library is not needed for that method

It appears you are right. From `getimagesize` being inside the GD section of the manual I concluded erroneously that it would require GD …

```
[timwolla@~]docker run -it --rm php bash                                                                                                                                                                    22:06:13
root@d6437fde4376:/# php -i |grep -i gd
root@d6437fde4376:/# php -m |grep -i gd
root@d6437fde4376:/# php -r "var_dump(function_exists('getimagesize'));"
bool(true)
```
