### ISSUE TITLE
Compress avatars during the upload

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2685]
Evaluate if there is any viable option to compress avatars (^= reduce the file size) using just PHP.

ref https://community.woltlab.com/thread/264718-komprimierung-f%C3%BCr-avatargrafiken/

**Comment by jens1o** [comment]
> Evaluate if there is any viable option to compress avatars (^= reduce the file size) using just PHP.

https://secure.php.net/manual/en/imagick.setimagecompressionquality.php

https://secure.php.net/manual/en/function.imagejpeg.php#refsect1-function.imagejpeg-parameters (quality parameter)
