### ISSUE TITLE
The ip addresses listed in the users online list should be linked to a search engine

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2686]
* [ ] Defaults to querying `google.com`.
* [ ] Include an event-based override to support other sites.

ref https://community.woltlab.com/thread/266425-add-google-ip-search-query-link-to-ip-s-listed-on-online-list/

**Comment by jens1o** [comment]
>  Defaults to querying google.com.

Please. Make. This. Configurable.
