### ISSUE TITLE
Cronjobs are not multi-process safe

### ISSUE THREAD

**Issue by lgandras** [WoltLab/WCF#2699]
Hi,

In version 3.1.3 cronjobs can be run multiple times in parallel. The problem is as follows. Cronjobs that are for potential execution must meet:
```
(afterNextExec <= TIME_NOW || nextExec <= TIME_NOW) && isDisabled = 0 && failCount < MAX_FAIL_COUNT
```
Afterwards, a cronjob is *not* put into PENDING *if it doesn't meet any* of the following conditions:
```
afterNextExec <= TIME_NOW && state = EXECUTING && failCount + 1 == MAX_FAIL_COUNT
afterNextExec > TIME_NOW && nextExec <= TIME_NOW && state != READY
```
The previous can be written as follows:
```
afterNextExec <= TIME_NOW && state = EXECUTING && failCount + 1 == MAX_FAIL_COUNT || afterNextExec > TIME_NOW && nextExec <= TIME_NOW && state != ready
```
The opposite of that condition (represents cronjobs that *are* going to be executed under this thread) is:
```
!(afterNextExec <= TIME_NOW && state = EXECUTING && failCount + 1 == MAX_FAIL_COUNT || afterNextExec > TIME_NOW && nextExec <= TIME_NOW && state != ready)
```
==
```
!(afterNextExec <= TIME_NOW && state = EXECUTING && failCount + 1 == MAX_FAIL_COUNT) && !(afterNextExec > TIME_NOW && nextExec <= TIME_NOW && state != ready))
```
==
```
(afterNextExec > TIME_NOW || state != EXECUTING || failCount + 1 != MAX_FAIL_COUNT) && (afterNextExec <= TIME_NOW || nextExec > TIME_NOW || state = ready)
```
Which in conjunction with the mysql read condition (represents cronjobs that were read AND *are* going to be executed under this thread) is:
```
(afterNextExec <= TIME_NOW || nextExec <= TIME_NOW) && isDisabled = 0 && failCount < MAX_FAIL_COUNT && (afterNextExec > TIME_NOW || state != EXECUTING || failCount + 1 != MAX_FAIL_COUNT) && (afterNextExec <= TIME_NOW || nextExec > TIME_NOW || state = ready)
```
Now, in order to label a cronjob as "it is going to be run under this thread", the following change is done:
```
state = PENDING
```
So, the following represents cronjobs that: 1. were read in the query 2. are going to be executed in this thread 3. are going to be executed in some other thread (already state=PENDING):
```
(afterNextExec <= TIME_NOW || nextExec <= TIME_NOW) && isDisabled = 0 && failCount < MAX_FAIL_COUNT && (afterNextExec > TIME_NOW || state != EXECUTING || failCount + 1 != MAX_FAIL_COUNT) && (afterNextExec <= TIME_NOW || nextExec > TIME_NOW || state = ready) && state = PENDING
```
==
```
(afterNextExec <= TIME_NOW || nextExec <= TIME_NOW) && isDisabled = 0 && failCount < MAX_FAIL_COUNT && (afterNextExec <= TIME_NOW || nextExec > TIME_NOW) && state = PENDING
```
==
```
afterNextExec <= TIME_NOW && isDisabled = 0 && failCount < MAX_FAIL_COUNT && state = PENDING
```
Which means that all cronjobs that:
1. Failed at least once
2. Were reactivated (setting manually failCount to 0 again)

Are going to executed simultaneously by all threads that find the row in the database with exactly that condition above described. In fact, the SELECT ... FOR UPDATE will not change the value of state after the first thread changes it. All others will follow thinking they executing the cronjob by themselves only.

The above is just the proof of a behaviour we've observed ourselves with cronjobs that failed and had to be reactivated manually again. The problem is solved as soon as that condition above is false. For that, the first thread just has to make sure the following threads can't fullfil it. And the easiest way to do that without generating a lockout is by setting afterNextExec = TIME_NOW + 10 when setting state = PENDING. That way, that condition becomes false and only the first thread (the one that changes the state to PENDING) is the only one who can lock the cronjob for execution when this one is being restarted from failure.

**Comment by dtdesign** [comment]
Fixed in #2726
