### ISSUE TITLE
SMTP tester trims trailing spaces due to readString(), SmtpEmailTransport does not

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#2703]
If a users enters trailing spaces, e.g. at the end of the host field then the SMTP test button claims to have a working connection, while the actual sending fails.

Either `SmtpEmailTransport::__construct()` should trim spaces or `OptionAction::validateEmailSmtpTest()` should not use `readString()`.

The former might cause issues with usernames or passwords that legitimately end with a space. This might be an edge case, though.

**Comment by dtdesign** [comment]
Spaces should be removed, and while they can be an actual part of a username and a password, they're rather uncommon due to the issues with selection & copy on Windows.
