### ISSUE TITLE
Built-in tool to generate rewrites for an Apache .htaccess file

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2704]
n/t

**Comment by mutec** [comment]
Would you mind having a look at https://github.com/MysteryCode/de.mysterycode.wcf.htaccess? Maybe I can change it in a way it can be merged into WSC 3.2 (as the milestone says).

**Comment by dtdesign** [comment]
We've taken our time to look through the code, but it's a bit too heavy and goes much further than what we have in mind:

The tool is intended to generate the rewrite rules for all installed apps, that requires a single method that iterates over all apps, adds their paths to an array, order it by their specificity (e. g. `/` comes last (!)) and output the rules. All in all you're looking at, I don't know, maybe 20 lines of actual code? This pretty much covers the use cases for over 99.9% of all users of our software, sometimes it just makes more sense to keep it simple.
