### ISSUE TITLE
Quote boxes in articles cause issues with AMP

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#2705]
Quote boxes in articles cause issues with AMP, because the `UserAvatar` tag carries a `style` attribute with `width` and `height` properties. A `style` attribute is invalid in AMP.

For the SVG `DefaultAvatar` the `style` attribute has been changed to `width` / `height` attribute already in #2555 for 3.1.x.

The commit 98b2f7cb2d51f18f39ff64f02ddf3ad637b44940 should be backported to 3.0 and the change should be applied to `UserAvatar`:

https://github.com/WoltLab/WCF/blob/80f796a73aacc80af2420329849383ac65214e1e/wcfsetup/install/files/lib/data/user/avatar/UserAvatar.class.php#L82

**Comment by dtdesign** [comment]
Fixed in 551feed6055b62df0398f57b7485d58d7df54128
