### ISSUE TITLE
Add `TToggleAction` trait

### ISSUE THREAD

**Issue by Fabii547** [WoltLab/WCF#2728]
Integrating `IToggleAction` requires duplicating the same code over and over again which could be avoided by introducing a `TToggleAction` trait which would provide a default implementation of the two methods.

```php
trait TToggleAction {
	
	public function validateToggle() {
		$this->validateUpdate();
	}
	
	public function toggle() {
		foreach ($this->getObjects() as $object) {
			$object->update([
				'isDisabled' => $object->isDisabled ? 0 : 1
			]);
		}
	}
}
```

If you like I would create a pull request for that.

**Comment by Gravatronics** [comment]
I have checked our code for implementations of `IToggleAction` and found that the majority of the implementations does exactly what is proposed here.

(The majority of the remaining implementations require an additional check by the relevant objects whether they can be disabled.)

**Comment by Gravatronics** [comment]
See #2763
