### ISSUE TITLE
Rebuild data workers not implementing IRebuildDataWorker

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2760]
The object type definition `com.woltlab.wcf.rebuildData` requires its object types to provide a class that implements `wcf\system\worker\IRebuildDataWorker`.

The class of `com.woltlab.wcf.databaseConvertEncoding`, `wcf\system\worker\DatabaseConvertEncodingWorker`, however, does not implement this interface. The same applies to `com.woltlab.wcf.sitemap` and `wcf\system\worker\SitemapRebuildWorker`.

Saving these object types via the new PIP GUI will fail as a consequence of this issue.

**Comment by dtdesign** [comment]
Actually, I'm not quite sure if they should implement it, after all they don't use object lists like the other tasks do. I'm leaning towards modifying the definition to require only `wcf\system\worker\IWorker`, because at the bare minimum it provides everything that's required to execute the tasks.
