### ISSUE TITLE
DevTools: Setting up new Projects

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2772]
> Offer to create a new package.xml through a guided process. Maybe even add editing tools that lets the user make changes to the configuration, such as adding dependencies.

TODOs:
- [x] Replace `for (… of …)` loops

**Comment by dtdesign** [comment]
Sounds like #2616?

**Comment by Gravatronics** [comment]
@dtdesign Isn't #2616 about installing existing packages via the DevTools while this is about setting up new packages (new `package.xml` files) via the DevTools?
