### ISSUE TITLE
DevTools: Search for missing language items in language.xml files

### ISSUE THREAD

**Issue by Morik** [WoltLab/WCF#2785]
Ever so often you write updates for a Plugin in one language and translate them later in the process.
Whenever you do so there is a chance that you'll miss one item to translate in the process or you renamed it and need to delete it from the other language files.
Therefor it would be nice to have an option to validate all files, check and list missing items (ordered by language with an indicator in which languages the item exists) and using the new GUI add the option to add them directly or delete old items in all languages they exist.

This would also be a nice way to add completely new translations even for people without the knowledge of editing XML files.

**Comment by Gravatronics** [comment]
You can use the new language PIP entry list and search for `0` to show language items missing in any language.

(`1` is used if the language item is present in the language and `0` if it isn't.)

**Comment by Morik** [comment]
OK, i'll missed that completely.
In this case, only the option to delete an item seams to be missing.
And an option to add a blank language file for translations would also be nice.

**Comment by Gravatronics** [comment]
Deleting entries is now also possible via PIP GUI.
(See 7de77b9e9693a2992049019eaa3faafeb30651a2)
