### ISSUE TITLE
Change the appearance of blocked external images

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2788]
Images from external sources are displayed as `[IMG:<url>]` which looks far too similar to the `[img]` bbcode, leaving site owners wondering why the image won't display. Changing it into something less subtle, such as `[blocked-img:<url>]` should make it much clearer and easier to spot.

Affects 2.1+

**Comment by dtdesign** [comment]
Do we really need to localize it? It doesn't really look any better and translating it wouldn't make it much clearer as to why the image isn't displayed. After all, users should not see this at all, at least under ideal circumstances?

**Comment by Morik** [comment]
Its more that i prefer the current version.
I mean currently it looks like intended by the admin, but you try to force admins to disable the img bbcode completely.
If this is the goal so simply do it or at least give them the option to have the more subtile version as alternative.
