### ISSUE TITLE
Profile preview erroneously renders ”more options” icon

### ISSUE THREAD

**Issue by max-m** [WoltLab/WCF#2791]
When loading a profile preview in desktop mode everything is fine:
![bildschirmfoto vom 2018-12-04 22-00-18](https://user-images.githubusercontent.com/642457/49472690-58560e00-f810-11e8-8077-149c5dd7a316.png)

But once you enter the tablet or smartphone view, even without loading a preview, all newly created profile previews will render the “more options” icon:
![bildschirmfoto vom 2018-12-04 22-00-35](https://user-images.githubusercontent.com/642457/49472692-5ab86800-f810-11e8-9ece-1269e7eb885d.png)

**Comment by dtdesign** [comment]
The previews are enabled on desktop only and will trigger on hover. You've accessed the site using a non-touch desktop-class device and therefore the popovers are active, manually reducing the browser window will not change this state.

The "more options" icon is part of the mobile optimization that is applied to all icon lists, but the popover doesn't exist on non-desktop devices…
