### ISSUE TITLE
Improve the UX when sharing search results

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2792]
Search results are limited to the active user and expire after two hours, making them a bad choice for sharing. The page title of the result page actually contains a link to a new search using the same parameters, but it's extremly hidden.

* [ ] ~Add an explicit field that contains the link to a new search using the same parameters.~
  * [ ] ~Adjacent button to copy it to clipboard.~
* [x] Links to search results with a `highlight` parameter should implicitly start a new search, but interpreting the `highlight` value as a search query (similar to what `index.php?search/&q=hello+world` does.

**Comment by TimWolla** [comment]
Just an idea: Replace the URL in the address bar using `window.history.replaceState`? This would generate new searches on F5, though.

**Comment by dtdesign** [comment]
There's no difference in changing the address bar vs evaluating the highlight parameter, it would yield the same result without messing with page reloads.
