### ISSUE TITLE
Built-in tool to verify the system status

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2811]
There can be a lot of different issues when moving between servers, e. g. missing PHP extensions, different email servers or just bad file permissions. The new tool should periodically check the system status in the background to notify of any possible configuration issues, additionally the administrator may run these checks at will.

* [x] Check for any missing PHP extensions that are required.
  * [x] Dynamically extend the check for PHP extensions that are required through extensions, e. g. `ldap` or `curl`. The plugins or apps are responsible to report such requirements.
  * [x] Only report optional extensions as missing if they are in use, for example, imagick should only be checked if its enabled through the options.
* ~[ ] Run the basic authorization check for the SMTP settings that is also used in the options form.~
* ~[ ] Verify the URL rewrites, if enabled.~
* [x] Check the file and directory permissions.
* [x] Validate the PHP version against a list of versions, for example:
  * [x] Bare minimum (orange/yellow-ish): 5.5-7.1
  * [x] Recommended (green): 7.2 or 7.3
  * [x] Not (yet) supported (red): >7.3
  * [x] Should follow http://php.net/supported-versions.php, only versions that are have active security support are valid for the "Recommended" range.
* [x] Check the MySQL/MariaDB version and verify InnoDB support.
* [x] The PHP memory limit must be validated too.

I can imagine backporting the basic potions of the check (file permissions, PHP and MySQL requirements) to the 3.1 branch. This would allow us to have a mandatory check for these values and store the result in the registry, available for the upgrade process to probe for?

**Comment by Morik** [comment]
You should also check for the status of the foreign keys, as this is a common problem after server changes.
Keep in mind that there are fks that are not logged for the wsc, these need to be checked separate.

**Comment by Morik** [comment]
Out of curiosity:
Wasn't a cronjob planned in order to check it in the background and notify the admin?
For me this was the most important part as most admins won't check the page until they have real troubles an therefore run an unstable system.

**Comment by dtdesign** [comment]
There were no such plans and going through that thought, it doesn't make that much sense at all. Most issues that people have come from migrations, where the move from one webspace to another, but for obvious reasons don't go through the requirements check.

The system check page will be mentioned in our guides and should make it easier, to spot any discrepancies quickly, considering that the page does work. This is propably the most important aspect, because most of the things that the system check validates is actually mandatory for the software to run in the first place. Missing pdo_mysql or running on PHP 5.6? Good luck even trying to access the admin panel…

**Comment by jens1o** [comment]
What about adding the `redis` php extension to the check-list if the Redis cache driver is used? While it is not necessary(as it will automatically fallback to the fs-cache), it might be confusing for system administrators when moving from one system to another.
