### ISSUE TITLE
Rewrite Rule generator triggers on enter on any text field

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2817]
If the form to edit "General" options is submitted via pressing enter on any focused text field (not related to the rewrite rules), an AJAX request is sent for `OptionAction::generateRewriteRules()` causing an exception for nginx.

See #2764

Affected (tested) browsers: Firefox, Safari

**Comment by mutec** [comment]
I case you're fixing that on your own please also fix this: https://github.com/WoltLab/WCF/pull/2764/commits/6d540a8fe8b19679fac00c5969a3a21883036e03#r245452021
Noticed that while I wrote the standalone generator on my website yesterday.
