### ISSUE TITLE
Improve ExceptionLogView list

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#2831]
- [x] When attempting to find the newest Exceptions one has to go to the last page manually: Invert sort order. The newest Exceptions appear at the top of the first page.

see also: #2472

**Comment by mutec** [comment]
To the second point: Please keep in mind users might not remove the logs and don't get that it's a new exception when new exceptions with the same trace (...) don't get logged. So please group them (maybe by an additional identifier/hash of the exception), but store every single one!
