### ISSUE TITLE
Prevent attachments being damaged when transfered in FTP auto mode

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2840]
Attachments are stored as simple filenames without a file extension, causing some FTP clients in auto mode to assume ASCII for whatever reason. This results in severly damaged files when an attachment is actually a binary file, e. g. an image.

We cannot use the original file extension for security reasons, it might make sense to use the `.bin` extension to give those bad FTP clients something to chew on, while preventing the files being executed on the webserver.

This should be implemented in a backwards compatible manner, e. g. trying to read the file should check for `<hash>.bin` first and then fall back to `<hash>`. The performance penalty of accessing the filesystem twice for a legacy file should be neglible.

* [x] Save new attachments with the `.bin` file extension.
* [x] Rebuilding attachments should rename the files to include `.bin`.
* [x] Lookups will be performed against `<hash>.bin` first, but just `<hash>` is a supported fallback.

**Comment by Morik** [comment]
You could also add an auto rename into the attachment rebuild worker
