### ISSUE TITLE
Information for nginx to secure directories

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2844]
We should implement an information box for nginx users that shows up during the installation.
Most nginx users won't think about which directories (of WSC and default applications) should get protection against web-calls. Or add it to the ACP's index page?

**Comment by dtdesign** [comment]
I could see this being incorporated into the system check, which could probe for some known files in order to determine the directory status. I'll keep an eye on this one and see how the system check by itself turns out and make changes as we go.
