### ISSUE TITLE
User popover and dialog interaction

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2870]
In the user popover (`class="userLink"`), there are links that open dialogs (activity points and trophies). After clicking on one of the links (do not move the cursor afterwards!), the relevant dialog opens but is shown below (smaller `z-index`) the user popover.

Either the user popover should have a smaller `z-index` than the dialogs or the popover should be hidden.

**Comment by dtdesign** [comment]
The popover should never trigger any sort of overlay or dialog, this has led to some very awkward bugs in the past. Can't we simply block the links from offering the dialog in the first place?

**Comment by Gravatronics** [comment]
> Can't we simply block the links from offering the dialog in the first place?

I have not looked into how simple that would be, but of course, that would be another alternative.
