### ISSUE TITLE
Support application-attribute in Dev tools

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2900]
```
<instruction type="file" application="shop" />
<instruction type="template" application="shop" />
```
During installation the `files.tar` and `templates.tar` get extracted to the shop's directory, but Dev tools are still ignoring the `application`-attribute. Triggering the sync for files/templates/acptemplates will end up in writing the content of `/files/` (or others) into the WSC's directory, which is basically wrong and is a different behavior than the installation/update in real.

**Comment by dtdesign** [comment]
The developer tools make use of the application abbreviations in order to detect the path: `files_<app>/` is mapped to the files directory of `<app>`, e. g. `files_wbb/`.

The package.xml's instructions are by design ignored by the dev tools.

**Comment by mutec** [comment]
Then remove the support for importing projects if it's not supported (where's the sense?) or fix this bug which is basically a bug - whether you want or not.

**Comment by dtdesign** [comment]
Some non-uniform projects may not be supported, including project layouts that incorporate a different directory structure, e. g. using a `xml/` directory and similar.

The dev tools require a predictable layout in order to support arbitrary packages, regardless of the XML configuration. There is a large notice on the sync PIP page that explicitly explains the use of per-app file PIPs.

**Comment by mutec** [comment]
Well in that case, I'll continue using the IDE's features and a custom script until the dev tools are implemented in a way that make them usable.
Changing 100+ branches to a non-WSC-default handling would be bullshit.

**Comment by dtdesign** [comment]
The behavior of the dev tools, in particular the detection of application specific PIPs, was designed to support packages during the development. At no point is the `package.xml` actively being used to make any sorts of assumptions, which in return does not require you to have any working instructions whatsoever.

This is nothing new, it was designed this way when it was first introduced, there was no change in 5.2 in these regards. I can understand that this might be an issue if you're using a different project layout, but at the end of the day we need to use a single and predictable layout.
