### ISSUE TITLE
Generate rewrite rules: Apache not identified

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2903]
`function_exists('apache_get_version')` returns false for me.

I'm using a php-fpm setup, using 
```
Web Server
    Apache/2.4.39 (Unix)

MySQL Version
    10.3.14-MariaDB-log 

PHP Version
    7.3.4 
```

I think it could use the `$_SERVER['SERVER_NAME']` variable, as it looks like the function only exists when the current process is spawned by the mod_php module.

**Comment by dtdesign** [comment]
Does it even make sense to restrict the rule generator's output? I mean, sure, you can't take the `.htaccess` rules and slap them on a nginx, but there are dozens of free converters that turn them into proper rules. This would solve this issue (bonus points for not sniffing for bogus server tokens) and make it a bit easier for users to incorporate the rules into their configuration?
