### ISSUE TITLE
Replace {APP}1_ with {APP}{WCF_N}_ in Database::prepareStatement()

### ISSUE THREAD

**Issue by joshuaruesweg** [WoltLab/WCF#2911]
At the moment you have to make sure that the correct `WCF_N` is used for database queries. In the future an automatic replacement from `{APP}1_` to `{APP}{WCF_N}_` should take place in the method `\wcf\system\database\Database::prepareStatement()`, so that the `WCF_N` does not have to be considered with manual database queries any longer.

**Comment by Gravatronics** [comment]
There has to be an opt-out per `Database` object for the importers were a specific value is used that in general is different from `WCF_N`.
