### ISSUE TITLE
Style: Color Schemes

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2928]
The style system already supports a huge customizable color palette, but each color variable can be assigned a single value only. This creates a situation where styles are sometimes offered in dozens of different variants that only differ by the color palette, but use the same overall CSS. "Color schemes" solve this by offering a switch between color variants that all belong to the same "physical" style.

* [ ] A toggle allows the color palette to switch between color schemes.
* [ ] Color schemes are read-only for protected styles.
  * [ ] The administrator may copy an existing scheme to customize it, thus preserving full update support.
  * [ ] Color schemes must be sortable and it should be possible to disable variants.
  * [ ] Pre-defined color schemes cannot be deleted, unless the style protection is removed.
  * [ ] One color scheme should be defined as the default variant.

**Comment by TitusKirch** [comment]
It would be nice to make color schemes only available to certain groups

**Comment by dtdesign** [comment]
This issue would greatly benefit from CSS variables, especially since something like a "Dark Mode" is pretty much just a different set of colors for the same thing.

However, this can have a significant impact on static images, including but not limited to logos, so things may be much more complicated than they appear on the surface.
