### ISSUE TITLE
Issues with flexible Controller Resolution 

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#2934]
Ref #2773

Dunno, if this is the expected behavior, but imho this should be improved:

1. When overriding the application of a page, the page is still listed under it's initial application instead of the "new" one:

![image](https://user-images.githubusercontent.com/81188/57870204-e9d99b00-7806-11e9-9f45-d67fe8d3bf3d.png)

2. Individual URLs are ignored within menu items when overriding the application. Let's take the example above:

The individual URL is "impressum". When not overriding the application, the menu item is linked to `/index.php?impressum/`

When overriding the application, the menu item is linked to `/blog/index.php?legal-notice`.

**Comment by SoftCreatR** [comment]
Another issue i've experienced is, that if the application for the board-list page has been overridden, you won't be able to access it anymore. Instead, you will be redirected to the start page (which is, in my case, the dashboard page).

However, if you set board-list as start page, you can access the board list as expected.

**Comment by SoftCreatR** [comment]
@dtdesign Were you able to reproduce any of these issues?

**Comment by dtdesign** [comment]
It is still somewhere on my todo list, I will look into it before releasing a public beta, until then it will have to wait.

**Comment by SoftCreatR** [comment]
Ty for the info.

**Comment by SoftCreatR** [comment]
@dtdesign Sorry, but all issues listed above are still unfixed. To reproduce, simply set a custom URL.

Furthermore, there's another issue: When editing a page, the associated App isn't pre-selected. Instead, it just displays/selects the first App in the selection. This will lead to unplanned modifications of URLs, because no one will notice that during a page edit.

**Comment by dtdesign** [comment]
I cannot reproduce issue (1.) and (2.) above, these work perfectly fine using a clean installation.

**Comment by SoftCreatR** [comment]
Well, the only thing that i missed was, that we've configured url rewriting. Maybe that's the issue?

**Comment by dtdesign** [comment]
URL rewriting does not cause any issues for me. Considering that this is just a simple if-condition to omit the `index.php?` part, I doubt that it even could make a difference.

![image](https://user-images.githubusercontent.com/208610/59927366-97f6e700-943c-11e9-9b6f-1710001c36e2.png)

**Comment by SoftCreatR** [comment]
In our test environment, WSC is installed in /com/ and WSF is installed in /

I've tested it in two fresh instances and got the same results.

**Comment by dtdesign** [comment]
I did notice that the first screenshot was refering to the active filter, the red square made me think that the displayed link was reported to be incorrect. I fixed that one with the previous commit.

However, the menu item link is still looking correct for me. I have this set up:
1. Installed at `/com/` (Core) and `/` (Forum).
2. Enabled url rewriting.
3. Set the application for the privacy policy to `/` (Forum).
4. The link in the page list points to `/privacy-policy/`.
5. The existing link in the page footer also points to `/privacy-policy/`, clicking on it opens the page without redirecting.

**Comment by SoftCreatR** [comment]
And if you set a custom URL it's working? Because that's the problem here.

**Comment by dtdesign** [comment]
Oh, this is related to system pages only. Your example mislead me into testing this with custom pages …

**Comment by SoftCreatR** [comment]
Tbh, i did not test it with custom pages, yet, because all i did was to test it in a fresh install, using the existing pages.

**Comment by SoftCreatR** [comment]
With 74ee82c it seems to work. Ty :)

**Comment by SoftCreatR** [comment]
After a week of testing, i just stumbled across another problem with this feature. Let's assume, that you've changed the application of all WSF controllers to WSC. This works fine so far, but it also results in the problem, that (in my example) `wbb` will never be the active application (which might be the expected behavior). So everything that checks for `$__wbb->isActiveApplication()` will stop working (e.g. `__searchAreaSettings.tpl`).

**Comment by SoftCreatR** [comment]
@dtdesign Imho, this is a huge problem, because it breaks everything that relies on the current application, when using the rewrite option. This should be fixed before the first Beta.

**Comment by dtdesign** [comment]
Thanks, but there is really no need to push issues, I have everything organized :)

**Comment by SoftCreatR** [comment]
Sorry. Didn't want to push, I just thought you may have missed that I've reopened the issue.
