### ISSUE TITLE
3rdParty login: Indicators for admins and in password requests

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2951]
The third party login is a bit unflexible:
- The administrator is unable to review the authentication method, it is simply not visible that a user has registered themselves through a 3rd party site.
- Requesting a password yields an error message that denies the request, because the account is attached to a third party service. While this is correct, it is a poor UX in terms of the workflow. Instead, the message should tell the user that their account is connected with service X and present the user with a button to initiate the process.

**Comment by joshuaruesweg** [comment]
I would also remove the password field for administrators for accounts registered through third parties. 
In addition, I would offer an option to decouple the account at the place of the password (if the user, for example, no longer has access to the account, for whatever obscure reason).
