### ISSUE TITLE
Improving event listeners

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2952]
The event system is pretty powerful, but subscribing and processing events is still a bit cumbersome, or at the very least, could be made easier:
- [x] **New mode for the environment: `all`.**
  The event listener is registered for `admin` and `user` alike.
- [x] **Dynamic invocation of event listener methods based on event names.**
  Subscribing to an event called `foo` should invoke the method `::onFoo($eventObj, array &$parameters)`. This behavior is achieved through a new, empty interface that signals the compatibility with this kind of method invocation, the `::execute()` call is only supported for the existing interface which should not be deprecated (at that time).

**Comment by Morik** [comment]
It would be really nice if you could make a special case for DBOAs.
In most Cases you only want to trigger for a specific Action, which could be solved by invoke a method like ```::onFinalizeActionCreate```.

**Comment by TimWolla** [comment]
Fully resolved as of c2e14083712e43bf4f25bb49aeedd3dc93ce278f.
