### ISSUE TITLE
Missing common bots

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2970]
* [x] `Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)`
* [x] `Slack-ImgProxy (+https://api.slack.com/robots)`
* [x] Discord (?)
* [x] Telegram (?)

**Comment by TimWolla** [comment]
Discord is: `Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com)`
Telegram is: `TelegramBot (like TwitterBot)`
