### ISSUE TITLE
Reactions should emphasis on the content rather than the author

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2975]
Reactions are very versatile and enable a whole lot of different user cases, all covered by a single system. However, in it's current state the focus lies too much on the idea of "rating" content rather than expressing thoughts and emotions through reactions.

* [x] There are only plain reactions, there is no positive/neutral/negative rating attached to them.
* [x] `cumulativeLikes` is kept in the code and the database (ALTER TABLE in large communities is a real pain), but will track the total number of reactions.
* [x] Users will only have a counter that trackes the number of received reactions, again using the legacy `cumulativeLikes` column.
* [x] Remove the ability to react to the own content, the constant `LIKE_ALLOW_FOR_OWN_CONTENT` is always `0`.
* [x] Remove `LIKE_ENABLE_DISLIKE` and set it to always `0`.

**Comment by mutec** [comment]
This makes it impossible to moderate automatically by marking good or bad posts by it's reactions (count).
It makes it impossible to display lists with the best ratings of files/posts/users/products/…
In case someone doesn't want to use valued reaction, he/she/it can set every reaction to neutral.
Did you ever think about other projects than your forum-app? This change is very disappointing and makes WSC unattractive for many projects.

It's not your position to decide whether the administrator should be able to vote negative and positive and might project that onto the authors. This decision has to be made by every administrator itself based on every single project and user base.
