### ISSUE TITLE
WCFSetup: Attempt to create the database

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2979]
Implicitly try to create the database if it does not exist. If this fails for whatever reason, the error message must be suppressed and instead yield the generic error for the missing database.

**Non developer mode only.**

**Comment by TimWolla** [comment]
> **Non developer mode only.**

In fact this is already done in developer mode: https://github.com/WoltLab/WCF/blob/4b6fd19148feb2a13b95db866577a0efb8dd274a/wcfsetup/install/files/lib/system/WCFSetup.class.php#L670

**Comment by dtdesign** [comment]
I know exactly what it does in developer mode, including but not limited to the dev config. This issue is entirely focusing on the regular setup, most important the different kind of error reporting.
