### ISSUE TITLE
getLocationHelper($path) as public method in FileUtil

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2990]
Maybe it would be better to provide that method in the FileUtil-class instead of writing it for every single Class, that might contain binary data/files.
I just noticed it in the Attachment-class.

**Comment by dtdesign** [comment]
Does it even make sense to move this particular method into a generic collection? I mean, there's a lot more attached to it and this method exists as a fallback mechanism to help with the migration and is not meant to be used as a method for regular file access.

**Comment by mutec** [comment]
In case someone might want to switch from no-extension-files to binary-files it would be a nice fallback. I didn't check that but I think you're using it for attachments, media-files, the gallery and the filebase (basically for every piped file); so it might reduce code duplications.

**Comment by dtdesign** [comment]
We'll keep the logic separated for now, but we're working on a new concept for the package system, including the handling of volatile files, including a focus on stateless packages.
