### ISSUE TITLE
New events in UserNotificationHandler

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3016]
At the moment there's the event-point `fireEvent` at `wcf\system\user\notification\UserNotificationHandler::fireEvent()`.
The 'problem' with this event is, that `$parameters['recipients']` might include users who aren't going to be recipients in the end, because they don't want that kind of notification.
It might be better to have an additional event (since moving it would break compatibility) within the stackable-update-block:
https://github.com/WoltLab/WCF/blob/ecf02509ca3658c24fdc3efe85ad2d8b45d0256c/wcfsetup/install/files/lib/system/user/notification/UserNotificationHandler.class.php#L167-L184
and one directly before the notifications are created:
https://github.com/WoltLab/WCF/blob/ecf02509ca3658c24fdc3efe85ad2d8b45d0256c/wcfsetup/install/files/lib/system/user/notification/UserNotificationHandler.class.php#L226-L251
always containing the same parameters than the existing event, but updated/additional values.

For the moment I'll change my plugin to use `UserNotificationAction::create()` instead - if there are all necessary parameters available.

PS: It could be helpful too, if there were events in `markAsConfirmed` and `markAsConfirmedByIDs`.

**Comment by dtdesign** [comment]
Implemented in https://github.com/WoltLab/WCF/commit/10e75eaf0ae577aff1f133ac742be6022a227a71
