### ISSUE TITLE
Inherit Languages

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3019]
Since I didn't get any answer on the PR #2330 yet:
Inherited languages would make it easy to provide dialects or specials variants of languages and a fallback to it's parent language.
This would be also a good change to remove the performance-horror of the current implementation of informal German.
PS: The required changes aren't that big.

**Comment by dtdesign** [comment]
We do not see any benefit in making such changes to the language system at this time. Any major change needs to solve an actual problem that is a real show stopper. A more sophisticated language system would tidy some things up and allow for some slightly cleaner phrases, however, none of this qualifies for such a move.

> This would be also a good change to remove the performance-horror of the current implementation of informal German.

Now you're making facts up. There are on average only a couple of phrases per page that uses the constant, which results in a handful of `if` statements for a simple boolean check of a constant. The few ns that this adds is neglible and is lost in the margin of error of any benchmark.
