### ISSUE TITLE
Use AbstractFormBuilderForm more often

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3021]
`\wcf\acp\form\AbstractAcpForm` and `\wcf\form\MessageForm` or `\wcf\form\AbstractCaptchaForm` might extend `\wcf\form\AbstractFormBuilderForm`

**Comment by dtdesign** [comment]
This is not possible for backwards compatibility, `AbstractFormBuilderForm` introduces a set of new properties and methods that may not be compatible with existing implementations of forms deriving from the mentioned forms.
