### ISSUE TITLE
x64 builds of PHP and `PHP_INT_MAX`

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3023]
File sizes are often stored as integers, counting the raw number of bytes. However, these numbers are effectively limited to 2,1 GB due to the size constraints in the database (`INT(10)`) and in x86 builds of PHP (`PHP_INT_MAX`).

Since PHP 7.0, the support for 64bit integers is available on Windows too, if using an actual x64 PHP build. The size can be determined through `PHP_INT_SIZE` which returns `4` (bytes) for x86 and `8` (bytes) for x64 builds.

We should monitor the number of x64 builds and once it reaches a sufficient treshold, x64 should become a requirement for all installations.

Note: Not targeting a specific milestone, because this change requires a wide-spread adoption of x64 builds.

**Comment by TimWolla** [comment]
Shall we add a 64 Bit recommendation to WCFSetup with 5.5?

**Comment by dtdesign** [comment]
Yes, that makes sense.

**Comment by TimWolla** [comment]
Resolved with #4784.
