### ISSUE TITLE
Failsafe test for custom CSS/SCSS

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3026]
Implement any sort of testing methology that attempts to validate if the code compiles, before finally saving the changes.

**Comment by mutec** [comment]
https://github.com/MysteryCode/de.mysterycode.wcf.customSass/blob/master/files/lib/acp/form/CustomScssForm.class.php#L61-L89

**Comment by joshuaruesweg** [comment]
@dtdesign This issue is relevant to the style itself and the global custom CSS, correct?

**Comment by dtdesign** [comment]
Yes, both can introduce errors that brick the style compilation.
