### ISSUE TITLE
Menu in landscape view on iPad Pro

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3027]
The main menu doesn't behave properly on touch based devices, there appears to be some interference with the a11y changes to the drop-down menu.

-- @joshuaruesweg

**Comment by joshuaruesweg** [comment]
As a note: This commit causes the broken view: https://github.com/WoltLab/WCF/commit/385a3e642863a456ea56745fe2a01e0ae2b3ccb0

**Comment by jens1o** [comment]
Assuming the patch already landed on beta.woltlab.com: This also happens when using a Laptop that supports touch (however when using a convertible with a pen it works properly).

I cannot trigger the menu item `Upcoming Events`, because it is unaccessible when only using the touch screen.
