### ISSUE TITLE
Allow access to the `MediaPage` when `FORCE_LOGIN` is enabled

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3036]
n/t

Affects 3.1+

**Comment by jens1o** [comment]
Why is this required? It seems more like a security issue for me …

**Comment by dtdesign** [comment]
Media items can be embedded in pages that are visible regardless of the login state. Remember, you can set any regular page to be viewable at all times, not just those pages that are defined in this small list of classes.

This is not a security risk, permissions can be set for each media item.
