### ISSUE TITLE
Deduplication of similar exceptions on exception log page

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3044]
Deduplicate similar Exceptions (e.g. by collapsing Exceptions with an identical message + stack trace). Possibly update the calculation of the exceptionID: https://github.com/WoltLab/WCF/blob/489106fa026f06563971108cd9dd59bd98950b9e/wcfsetup/install/files/lib/core.functions.php#L151

**Comment by mutec** [comment]
Just to keep it in mind: https://github.com/WoltLab/WCF/issues/2831#issuecomment-522067803
