### ISSUE TITLE
DevTools: Set file owner, group and make writable

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3046]
The files get copied but their owners won't change automatically - this causes problems when overriding the files with the next request.

**Comment by TimWolla** [comment]
Which operating system is PHP running on?

**Comment by mutec** [comment]
Debian 9.9
The "problem" behind this is that I'm uploading the files as root 0644 - the webserver uses www-data (www-data and root don't use the same groups of course). DevTools copied everything without setting the "correct" permissions/user/group. Even if it hadn't caused problems it would be better to use the correct values.
I'm going to check that in another installation these days; maybe it was just angry with me.

**Comment by TimWolla** [comment]
non-root users are not able to chown files on Linux. Any files copied by WoltLab Suite thus must be owned by `www-data` for sure (i.e. the process' UID), granting the necessary permissions.

**Comment by dtdesign** [comment]
Closing for the aforementioned reason.

Have you considered enabling SCP access for `www-data` via pubkey? It works like a charm and gives you the ability to upload files without having to face issues with bad ownerships or permissions.
