### ISSUE TITLE
WysiwygSmileyFormContainer: Possibility to show or hide smiley categories

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3048]
compare `MessageForm::readData()` https://github.com/WoltLab/WCF/blob/12a79f5575f43da15c3f6d752f9adf8111182c26/wcfsetup/install/files/lib/form/MessageForm.class.php#L283-L291
It would be nice to be able to hide some categories or explicitly show just a few.

**Comment by Gravatronics** [comment]
Have you tried marking the relevant category tabs (`{$messageID}_smileyCategoryTab'{$smileyCategoryID}`) as inaccessible?
