### ISSUE TITLE
Filtering global modification log by action is broken

### ISSUE THREAD

**Issue by Fabii547** [WoltLab/WCF#3058]
https://github.com/WoltLab/WCF/blob/bf4cd1bf37c8c3127558e856c99bf83f73726b9e/wcfsetup/install/files/lib/acp/page/ModificationLogListPage.class.php#L194-L197 

`$this->action == intval($this->action)` evaluates always to `true`, therefore it is not possible to filter the list by an action.

https://3v4l.org/nN4gA

**Comment by joshuaruesweg** [comment]
Thanks!
