### ISSUE TITLE
MenuItem not considered as active with ID and Title applied

### ISSUE THREAD

**Issue by ilouHD** [WoltLab/WCF#3110]
Hello,

in my instance of WoltLab Suite Core 3.1.11 I ran into an issue:

I've added a page, that should display yearly papers of our tennis club. When clicking the menu item, you get to /habeku, the default URL to the page. That just works fine. But when selecting an other paper - let's say from 2017 - the URL looks like this: /habeku/2017-habeku/.

However in the second case (with id and title applied in the URL), the page still loads, but there is no active menu item anymore. I tried setting it in the HabekuPage.class.php using the `activeMenuItem`-property, but nothing works.

I've added the menuItem using
```
        <item identifier="de.tcbw.base.habeku">
            <menu>com.woltlab.wcf.MainMenu</menu>
            <title language="de">Habeku</title>
            <page>de.tcbw.base.habeku.HaBeKu</page>
        </item>
```
and the page using this:
```
        <page identifier="de.tcbw.base.habeku.HaBeKu">
            <pageType>system</pageType>
            <controller>wcf\page\HabekuPage</controller>
            <name language="de">Habeku</name>

            <content language="de">
                <title>Habeku</title>
            </content>
        </page>
```

At last I set `public $activeMenuItem = "de.tcbw.base.habeku";` in my HabekuPage.class.php

I hope for your help,
Marc

**Comment by ilouHD** [comment]
In addition to that: I've installed Woltlab Suite 5 Beta 3 for testing purposes and ran into the same problem in the gallery plugin:
Going to the gallery into a category lets "Galerie" stay active in the main menu, but switching to a subgallery/subcategory doesn't considers "Galerie" as active:

Category "2019" and "Galerie" set active:
![image](https://user-images.githubusercontent.com/8680610/69097099-22785c80-0a56-11ea-94b1-363e06418009.png)

Category "test" (subcategory of 2019) and "Galerie" not set as active:
![image](https://user-images.githubusercontent.com/8680610/69097123-2b692e00-0a56-11ea-843b-44cda32ab059.png)

Greetings

**Comment by Gravatronics** [comment]
> In addition to that: I've installed Woltlab Suite 5.2.0 Beta 3 for testing purposes and ran into the same problem in the gallery plugin:
Going to the gallery into a category lets "Galerie" stay active in the main menu, but switching to a subgallery/subcategory doesn't considers "Galerie" as active:

That issue has been fixed in Gallery and will be shipped with the next release.

In Gallery, the category page is a child page so that for the parent categories, a page location entries has to be manually added:

```php
foreach ($categories as $category) {
	PageLocationManager::getInstance()->addParentLocation('com.woltlab.gallery.CategoryImageList', $category->categoryID, $category);
}
```

(see `GALLERYCore::setLocation()`, with the first parameter of `PageLocationManager::addParentLocation()` already being fixed in the code above)

**Comment by ilouHD** [comment]
Thank you for your reply. That fixed my issue, so I will close this.
