### ISSUE TITLE
Updateserver improvements

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3120]
This issue should work as a brainstorming in order to make update-servers better in the future.
- Validation of files against checksums provided within the server's XML
- Login/Authentication using certificates
- Optional validation of the used URL

might be similar to https://community.woltlab.com/thread/280179-kryptographische-absicherung-von-updates/

**Comment by dtdesign** [comment]
The checksum validation is part of #3443, other changes to the package servers are not planned right now. We'll keep an eye on the package system and actively look for opportunities to improve it.
