### ISSUE TITLE
Idea: Minify the compiled templates to be loaded faster

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#3123]
(and save disk space)

This could be easily achieved by omitting the whitespaces in the `TemplateScriptingCompiler` (especially turn the old-school `array()` into `[]`):
https://github.com/WoltLab/WCF/blob/0f2bb2aa0536121b65d8b8e0af82fd2a590370d8/wcfsetup/install/files/lib/system/template/TemplateScriptingCompiler.class.php#L492-L494

would become (without trailing newlines as well):
```php
$phpCode = "<?php \$this->tagStack[]=['".$tagCommand."',[".$tagArgs."]];";
$phpCode .= "\$this->pluginObjects['".$className."']->init(\$this->tagStack[count(\$this->tagStack)-1][1],\$this);";
$phpCode .= "while(\$this->pluginObjects['".$className."']->next(\$this)){ob_start(); ?>";
```

**Comment by dtdesign** [comment]
The opcache does not care for any of this, but debugging will result in an endless nightmare of "error in line 1". That's the reason why my optimizations in 5.2 focus entirely on the code that is actually executed, all performance comparisons were performed with a warm opcache. None of your suggested changes have any impact on the execution time.

**Comment by jens1o** [comment]
Alright, thanks for the response :)
