### ISSUE TITLE
Quotes and code blocks can't be expanded under certain circumstances

### ISSUE THREAD

**Issue by Krymonota** [WoltLab/WCF#3198]
A user reported that after installing version 1.0.0 of my [Reading Time Estimate for Articles](https://pluginstore.woltlab.com/file/3174-reading-time-estimate-for-articles/) plugin, he was unable to expand quotes in articles. I was able to reproduce this issue on 3.1.11 and 5.2.4, and it appears that 3.0 is also affected.

[The issue was caused by the following function call in the `readData@ArticlePage` event](https://github.com/Krymonota/software.krymo.woltlab.suite.core.article.readingtime/blob/1.0.0/files/lib/system/event/listener/ArticleReadingTimeListener.class.php#L53) (which causes the `HtmlOutputProcessor` to process):
```php
$this->eventObj->article->getFormattedContent()
```

Calling this function resulted in the following HTML code not being embedded in the final HTML document:
```html
<script data-relocate="true">
    require(['WoltLabSuite/Core/Bbcode/Collapsible'], function(BbcodeCollapsible) {
        BbcodeCollapsible.observe();
    });
</script>
```

A closer look at the [quoteMetaCode](https://github.com/WoltLab/WCF/blob/056a6ddf7866a0c4e5d3e15facde9f52a147bb16/com.woltlab.wcf/templates/quoteMetaCode.tpl#L31) and the [codeMetaCode](https://github.com/WoltLab/WCF/blob/056a6ddf7866a0c4e5d3e15facde9f52a147bb16/com.woltlab.wcf/templates/codeMetaCode.tpl#L18) template reveals the problem:
If the function was called before (as in my case), the variables `$__overlongBBCodeBoxSeen` and `$__wcfCodeBBCodeJavaScript` are already set so that the script isn't embedded in the final HTML document and therefore quotes and code boxes can't be expanded.

**Comment by Morik** [comment]
You should enable the template sandbox before calling the formatted content and disable it afterwards.
```
WCF::getTPL()->enableSandbox();
$message = $this->eventObj->article->getFormattedContent();
WCF::getTPL()->disableSandbox();
```

This way all set template variables will be discarded.

**Comment by Krymonota** [comment]
Thanks for pointing that out.

@TimWolla You had asked me to create this issue. Can we consider this as solved?

**Comment by TimWolla** [comment]
> @TimWolla You had asked me to create this issue. Can we consider this as solved?

I'm not sure. Personally I strongly dislike having to "force" developers to use the sandbox, because it's entirely non-obvious and leads to hard to discover bugs such as the one in your plugin. So please leave this issue as is, maybe a good solution can be found.

**Comment by dtdesign** [comment]
These kind of checks in templates have a long running history of being fragile and prone to unwanted side effects like this. At some point we need to implement some sort of mechanics that allows components to automatically mount to such constructs without the need for these constructs.

However, this is nothing that we can improve right now, so @Krymonota, I recommend that you make use of the aforementioned sandbox feature for the time being. It's your best option at this time.
