### ISSUE TITLE
Support all IANA timezones

### ISSUE THREAD

**Issue by JuliusPC** [WoltLab/WCF#3222]
Currently all supported 100 timezones are hardcoded in [`wcf\util\DateUtil`](https://github.com/WoltLab/WCF/blob/5.2/wcfsetup/install/files/lib/util/DateUtil.class.php), which is problematic when setting the user's timezone from plugins. I have written a workaround that selects an alternative time zone based on the offset to UTC.
There is a reason for all these timezones existing. It is not only about offsets from UTC, there are also different daylight saving times. Timezones also include settings for historical dates. MediaWiki e.g. seems to support all 400 IANA timezones supported by PHP. [They can be obtained from a PHP API](https://www.php.net/manual/en/datetimezone.listidentifiers.php).

To demonstrate the problem I attach my workaround.

~~~php
  protected function getValidTimezone(string $timezone, string $default = 'Europe/Berlin') {
    $woltlab_zones = DateUtil::getAvailableTimezones();
    $unknown = trim($timezone);

    if(in_array($timezone, $woltlab_zones)) {
        return $timezone;
    }

    $unknown_offset = (new \DateTimeZone($unknown))->getOffset(new \Datetime('now', new \DateTimeZone('UTC')));
    $unknown_region = explode('/', $unknown)[0]??$unknown;

    $timezone_identifiers = \DateTimeZone::listIdentifiers();
    
    $candidate = $default;
    foreach($timezone_identifiers as $timezone) {
      if(in_array($timezone, $woltlab_zones)) {
        $offset = (new \DateTimeZone($timezone))->getOffset(new \Datetime('now', new \DateTimeZone('UTC')));
        if($unknown_offset == $offset) {
          $candidate = $timezone;
          if($unknown_region == explode('/', $timezone)[0]) {
            break;
          }
        }
      }
    }
    return $candidate;
  }
~~~

**Comment by dtdesign** [comment]
There will be no change to existing implementation.

The rationale is that the selection is already quite large and picking your own timezone is already cumbersome. We're already representing all significant timezones in the current state which are directly mapped to PHP's timezones. If you believe that a relevant timezone is missing, please feel free to report the issue.
