### ISSUE TITLE
Submit confirmation dialogs with Return

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3234]
It should be possible to submit confirmation dialogs generated with `WoltLabSuite/Core/Ui/Confirmation` with enter.

See https://community.woltlab.com/thread/277802-confirmation-js-submit-dialog-with-enter/

**Comment by TimWolla** [comment]
Is 837f68ba5f8557fec1aaefecfefc7b5eb0453d8a related to this?

**Comment by dtdesign** [comment]
Yes, that issue fixed it.
