### ISSUE TITLE
Show name of packages blocking updates

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3247]
relevant code: https://github.com/WoltLab/WCF/blob/eb1b9201fa6449e15ececb685a2a6188f2650eda/wcfsetup/install/files/lib/data/package/update/PackageUpdateAction.class.php#L680

see https://community.woltlab.com/thread/281769-anzeige-blockierendes-update/ (and https://community.woltlab.com/thread/280633-fehlermeldung-bei-update-auf-die-suite-5-2/)

**Comment by dtdesign** [comment]
The package system will be partially reworked in 5.3, including but not limited to a mechanism to automatically apply pending updates first. The mentioned error message is not pretty, but is only a failsafe for people that fail to read the documented upgrade procedure.
