### ISSUE TITLE
Restrict paid subscriptions to certain user groups

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3253]
It should be possible that only members of specific user groups are allowed to purchase paid memberships for other user group.

see https://community.woltlab.com/thread/272164-berechtigung-f%C3%BCr-bezahlte-mitgliedschaften/

**Comment by TimWolla** [comment]
How do you expect this to work? Should it be one general permission that decides whether a user can buy themselves into any group or should the restriction be configurable per paid group?

**Comment by BurntimeX** [comment]
One general permission would be sufficient.
