### ISSUE TITLE
Add "Go to content" button in notification emails

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3257]
… to make it easier to view the content the user is notified about.

see https://community.woltlab.com/thread/281019-benachrichtigungen-zu-inhalten-mit-button-zum-jeweiligen-inhalt/

**Comment by BurntimeX** [comment]
I would suggest that we just rename the "Mark as Read" button to "Go to Content", because the button already leads to the content.

**Comment by TimWolla** [comment]
I would be fine with that and already had that in mind myself.
