### ISSUE TITLE
Fixed throphies for message sidebar

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3271]
It should be possible for administrators to optionally restrict the types of trophies that are shown in message sidebars.

see https://community.woltlab.com/thread/278278-die-troph%C3%A4en-f%C3%BCr-die-anzeige-in-der-message-sidebar-global-festlegen/

**Comment by dtdesign** [comment]
This kind of defeats the purpose of user selectable trophies, after all, trophies are meant to engage users by giving them something to show off. Forcing them to display trophies that they equally care for just doesn't make any sense.
