### ISSUE TITLE
Different maximum number of trophy permissions for profile/sidebar

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3272]
There should be two separate permissions to restrict the number of trophies shown on the user profile page and in message sidebars.

Also see #3256

This might lead to having two separate selections for the relevant trophies.

see https://community.woltlab.com/thread/278279-das-limit-maximale-anzahl-an-besonderen-troph%C3%A4en-in-zwei-eigenst%C3%A4ndige-limits-au/

**Comment by dtdesign** [comment]
This kind of separation increases the complexity, forcing us to introduce a secondary selection of the trophies for each context. It creates a bad UX with little to no value for the user.
