### ISSUE TITLE
Support zooming images in image viewer on touch devices

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3282]
(iOS might already be working)

see https://community.woltlab.com/thread/279780-bilder-galerie-modal-zoom-auf-touch-ger%C3%A4ten/

**Comment by dtdesign** [comment]
I do intend to move to [FancyBox v4](http://fancyapps.com/next/) which no longer relies on ancient jQuery, but native JavaScript. Unfortunately, the progress is somewhat intransparent, so it is unclear if the version is mature enough once we're close to a release.

See fancyapps/fancybox#1346
