### ISSUE TITLE
Improve ACP search

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3335]
The more packages are installed, the more possible search results exist for searches in ACP making a dropdown with a fixed number of search results insufficient.

Current issues:
* Search shows only few results
* Results are severely truncated in width

Solution:
- [x] Show more results
- [x] Increase width of the search results dropdown

**Comment by dtdesign** [comment]
You can already restrict the results, there is a type selection literally right next to the search input. Adding some kind of full page search results is a nice idea, but this is entirely out of scope for now.
