### ISSUE TITLE
Handling of external links

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3339]
The current practice of augmenting `a.externalURL` with the `rel` and `target` attribute is quite cumbersome and error prone, also caused by the complexity of the generated attributes. We'll change this by offloading some parts of this to JavaScript (which, at least to a basic extent, is supported by all signficiant search engines). Also, external links will be flagged with `rel="nofollow"` at all times, force enabling the corresponding permanently.

* [x] Option `EXTERNAL_LINK_REL_NOFOLLOW`
  * [x] Remove it from the options and define it with the fixed value of `1`.
* [ ] ~~External links must be marked with the CSS class name `externalURL` **or** the new attribute `data-is-external-url="true"` (same as `a.externalURL` but without a visual indicator, for use with menus).~~
  * [ ] ~~If `EXTERNAL_LINK_TARGET_BLANK` is enabled, links will be augmented with the `target` attribute and the properties `noopener` and `noreferrer` on the `rel` attribute. (Use a `MutationObserver` to detect new links.)~~
* [x] The `HtmlOutputNodeA` is modified to flag all links as `rel="nofollow ugc"`.
* [x] Modify `ApplicationHandler::isInternalURL()` to treat everything as internal that resides on the same subdomain (not the domain apex, unless an application explicitly uses it!). Effectively, we'll just ignore the `domainPath`.

**Comment by TimWolla** [comment]
related: #3261
