### ISSUE TITLE
Allow upload of additional images via style editor

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3364]
Currently it is not possible to upload images that can be used as background-images in CSS.

Blocked on #3451

**Comment by TimWolla** [comment]
As already mentioned in #3438 the whole file handling for styles is pretty unclean and in order for a refactoring. We currently have the following:

1. The style's logo. Searched in the style's image folder with a fallback to the global `images/` folder. Not really cleaned up when deleting a style.
2. The style's preview. Stored in the global `images/` folder.
3. The style's default coverPhoto. Stored in the `images/coverPhotos/` folder and named using the styleID.
4. The style's favicon. Stored in the `images/favicon/` folder and named using the styleID.

On top of that the style's images folder does not necessarily exist and has an arbitrary name. During a style import if the style's image folder is already in use it will automatically be adjusted by appending a number.

So all in all the files for a style are all over the place. Going forward I propose the following:

1. _Always_ create a style specific asset folder.
2. Do not allow an arbitrary name for the style specific asset folder. Use the `styleID`.
3. Store all assets within this asset folder:
  - The logo.
  - The mobile logo.
  - The preview image.
  - The default coverphoto.
  - The favicon.
  - The Android / Windows manifests.
  - Any images uploaded as part of this very issue.
  - **Maybe:** The style's compiled CSS.

During style export the checkbox to include the style's image folder will be removed. The folder will *always* be exported.

**Comment by TimWolla** [comment]
With the cleaned up asset handling of styles building on the existing foundation of the new upload handler this should be fairly easyish:

- Add a new form field, allowing the upload of an infinite number of arbitrary images.
- These images are stored in `images/style-<styleID>/custom/` to not collide with the other assets, such as the logos.
- No database adjustments are required. During export the whole style folder is already exported recursively, during editing we can simply `glob('images/style-<styleID>/custom/*')` for existing images.

Does this sound like an appropriate solution to this issue?

**Comment by dtdesign** [comment]
I like the approach, especially using the `/custom/` directory to avoid collisions.
