### ISSUE TITLE
Disable cache in 5.2

### ISSUE THREAD

**Issue by Anti067** [WoltLab/WCF#3370]
Any ideas, how to stop cache permanent in 5.2, please?
I do not see any option to do it.

**Comment by dtdesign** [comment]
Which cache are you referring to?

**Comment by Anti067** [comment]
> Which cache are you referring to?

I use Filesystem (default) and i want to disable that in WWB 5.2. How to do it?

**Comment by dtdesign** [comment]
You cannot disable the cache, it is an essential component of the software and a lot of the software relies on the cache behavior.

Whatever your _actual_ issue is, "disabling the cache" is not the solution for your problem.

**Comment by Anti067** [comment]
I have a problem and i don't know what is the reason. I use sucuri firewall and when i enable their cache through cdn the cookies don't work properly.
When i click on logout, it has an effect elsewhere, but i remain logged in index.php
How can this be fixed?
Any ideas?

**Comment by dtdesign** [comment]
You should not cache the site output itself, that does not work and leads to all sort of inconsistencies in the behavior.

**Comment by Anti067** [comment]
The reason i want this is that their protection stops many DDoS attacks using CDN (with their cache), but i can't use that because WBB conflicts and nothing is updated or updated after a very long time.
I want to know how to prevent this.

https://docs.sucuri.net/website-firewall/performance/caching-options/
https://docs.sucuri.net/website-firewall/troubleshooting/troubleshoot-cache-issues/
https://docs.sucuri.net/website-firewall/performance/cache-exceptions/

I try with disable .js files - result is the same.

Any ideas?
Where can this conflict come from?

**Comment by dtdesign** [comment]
You cannot cache the page output, it won't work! For such a cache logic to work, the software needs to be built exactly for this purpose, otherwise it will break pretty much every application.

Please consider using a ddos mitigation provider that is capable of filtering live traffic, like they usually are able to.
