### ISSUE TITLE
Overhaul layout of comments

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3387]
Especially in the mobile version the margin to the left is too big and also the avatars are too big.

The comment system is in need for a significant overhaul, mostly because it has grown over many versions with new additions every now and then. There are a few particular issues that need to be adressed:
* The DOM is awful, cluttered with strange (`h3`) and misused (`ol` / `li`) HTML elements.
* Relying on `.containerList` for the visuals cause a lot of unwanted formatting to bleed into comments. This is even worse considering that `.containerList` was designed for a flat view with no level of nesting.
* Buttons are invisible in the desktop view, even the reaction button is hidden unless hovering.
* The dimensions of elements including their paddings and margins take up too much space, eventually crippling the available screen space for the actual content. The mobile view suffers even more with parts of the issue caused by the reliance on `.containerList`

**Comment by TimWolla** [comment]
see #5210
