### ISSUE TITLE
Url validation fails on non-URLs

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#3391]
Due to the nature of how `parse_url()` works, `Url::is()` (and other places, where this function is used) will never return the correct result on non-URLs. Every non-URL is considered as `path`, so the return value will never be false or empty.

Instead, `filter_var($url, FILTER_VALIDATE_URL)` or similar should be used. Alternatively, use the `PHP_URL_HOST` component parameter in combination with `parse_url()` (which leads to `null` on non-URLs, not `false`!).

---

```php
<?php
var_dump(parse_url('foo'));

/*
array(1) {
  ["path"]=>
  string(3) "foo"
}
*/
```

**Comment by TitusKirch** [comment]
The PHP documentation (https://www.php.net/manual/en/function.parse-url.php) also says:
> This function is not meant to validate the given URL, it only breaks it up into the above listed parts. Partial URLs are also accepted, parse_url() tries its best to parse them correctly.


> Instead, `filter_var($url, FILTER_VALIDATE_URL)` or similar should be used.

Unfortunately `filter_var($url, FILTER_VALIDATE_URL)` does not support IDN.

**Comment by SoftCreatR** [comment]
> Unfortunately filter_var($url, FILTER_VALIDATE_URL) does not support IDN.

That's correct, but i[dna2::encode](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/api/pear/net_idna2/Net/IDNA2.php#L2325) could be used to fix this issue.

**Comment by SoftCreatR** [comment]
Or maybe this one?

https://github.com/WoltLab/WCF/blob/fbbb20ec0da9d99c97186b911465053a7dc406cf/wcfsetup/install/files/lib/system/api/ezyang/htmlpurifier/library/HTMLPurifier/AttrDef/URI/Host.php#L33

**Comment by TimWolla** [comment]
> Unfortunately `filter_var($url, FILTER_VALIDATE_URL)` does not support IDN.

Because IDN URLs are not valid URIs by definition (RFC 3986). Unfortunately it also doesn't support percent encoding which *is* a valid URI (while also recommending IDNA encoding):

>   The reg-name syntax allows percent-encoded octets in order to
>   represent non-ASCII registered names in a uniform way that is
>   independent of the underlying name resolution technology.  Non-ASCII
>   characters must first be encoded according to UTF-8 [STD63], and then
>   each octet of the corresponding UTF-8 sequence must be percent-
>   encoded to be represented as URI characters.  URI producing
>   applications must not use percent-encoding in host unless it is used
>   to represent a UTF-8 character sequence.  When a non-ASCII registered
>   name represents an internationalized domain name intended for
>   resolution via the DNS, the name must be transformed to the IDNA
>   encoding [RFC3490] prior to name lookup.  URI producers should
>   provide these registered names in the IDNA encoding, rather than a
>   percent-encoding, if they wish to maximize interoperability with
>   legacy URI resolvers.

Encoding the URL properly is the responsibility of the API user, because `Url::is()` cannot know how the URL is going to be used afterwards.

> That's correct, but i[dna2::encode](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/api/pear/net_idna2/Net/IDNA2.php#L2325) could be used to fix this issue.

For Punycoding within WoltLab Suite I recommend [true/punycode](https://github.com/WoltLab/WCF/tree/5acd2862e255e3b9eaf30e318a106e20992b2f65/wcfsetup/install/files/lib/system/api/true/punycode). It's used within the email API:

https://github.com/WoltLab/WCF/blob/5acd2862e255e3b9eaf30e318a106e20992b2f65/wcfsetup/install/files/lib/system/email/Mailbox.class.php#L54-L55
