### ISSUE TITLE
Collapsible sidebar for `screen-lg-only`

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3399]
ref https://community.woltlab.com/thread/284299-geringe-seitenbreite-zerschie%C3%9Ft-layout/
related https://github.com/WoltLab/WCF/issues/3348

**Comment by dtdesign** [comment]
There is no simple approach to this:
* Adopting the mobile toggle button (it ain't pretty anway) looks awful on desktop sizes.
* Requires some fundamental adjustments to the style, which forces us to lock it away in the compatibility mode.

From what I grasp, this appears to be mostly an issue with (a) unrealistic browser sizes and (b) affects only some pages at all. We do have `screen-lg-only` at hand which should gives us enough tools to make some adjustments to affected pages instead, thus mitigating the issue to some extent. Besides that it is still an unrealistic scenario so anything that looks "okayish" will do.
