### ISSUE TITLE
Use InnoDB for search index tables

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3404]
- [x] Adjust the search query parser.
- [x] Afterwards the change should be as simple as s/MyISAM/InnoDB/. Actually migrating the tables should probably be left to a worker as it can take a while on larger communities and leaving the tables as MyISAM will not cause hard errors.

**Comment by TimWolla** [comment]
The issue preventing us from properly supporting InnoDB search indicies is the fact that the InnoDB FT grammar is much stricter than MyISAM's (which accepts literally everything, but might do what is expected).

The best solution probably is stripping all, except a small number of supported, special characters that appear outside of a quoted string in `parseSearchQuery()`.

Afterwards the change should be as simple as `s/MyISAM/InnoDB/`. Actually migrating the tables should probably be left to a worker as it can take a while on larger communities and leaving the tables as MyISAM will not cause hard errors.
