### ISSUE TITLE
isBlockElement appears to be ignored for the [wsm] BBCode

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3410]
Quoting from #3397:

> But according to bbcode.xml the wsm BBCode already is <isBlockElement>1</isBlockElement>. I am a bit confused why it didn't previously render as such and why it is a valid child of a <p> element.

see also: https://github.com/WoltLab/WCF/issues/3315#issuecomment-647498485

**Comment by dtdesign** [comment]
I am unable to reproduce this one, the bbcode is properly moved out of inline elements.

**Comment by TimWolla** [comment]
Okay, I have tested again. It appears there is a difference between the _actual_ `[wsm]` BBCode and the button that inserts media files.

I can still reproduce the issue using the following:

1. Press the Bold button.
2. Type `aa`
3. Move the cursor into the middle.
4. Click the media button in the toolbar and insert a media file (image in my case).
5. Show the HTML view in the editor: `<p><strong>a<img src="https://example.com/index.php?media/1-001-png/" class="woltlabSuiteMedia" data-media-id="1" data-media-size="original">a</strong></p>`.
6. Submit and view the generated HTML:
    ```
    <p><strong>a<span class="mediaBBCode">
    			<img src="https://example.com/index.php?media/1-001-png/" alt="" title="" data-width="193" data-height="162">
    		
    	</span>a</strong></p>	
    ```

It results in technically valid HTML, but appears to be not intentional especially when compared to the actual `[wsm]` BBCode.
