### ISSUE TITLE
Package Integrity Checks

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3419]
# What are Package Integrity Checks?

The Core accepts packages from arbitrary sources, both by upload and via package servers, without performany any sort of integrity checks, making them vulnerable to harmful modifications. The integrity checks are meant to protect users against malicious packages by verifying the contents against a known signature.

There are two sources for packages:
 1. Manual upload from packages received from arbitrary sources, such as other users or sites with a questionable reputation.
 2. Package servers maintained by third party developers have been put at risk multiple times by compromising the system they are running on. A rogue attacker is able to inject malicious code into existing packages or release new versions of reputable packages.

# How Will Package Integrity Checks Be Calculated?

The integrity check will yield a signature that should be somewhat graceful by only verifying the parts that make an actual difference when installed and/or applied as an update.

What will be checked:
- The package identifier and version as found in the `package.xml`.
- The list of required and optional packages.
  - Validate both the exact list and version numbers.
  - Recursively check any required and optional packages.
- The instructions for installing the packages.
- Any block with update instructions, including the exact version string.
- Any file (XML, SQL, archives, etc.) referenced by the `package.xml`: Checksum for the entire file.

What will **not** be checked:
- The outer archives themselves, because a tar file containing the same data could yield binary differences caused by deviations in the tar implementation or the gzip compression.
- Any file that is present in the package archive, but is not part of any PIP, including other parts of the `package.xml` that does not impact the result of an installation or update. This allows debug or versioning artifacts to be included without changing the signature, for example, commit ids added by the build system to indicate which version was used to build the package.

# What Is the Consequence of the Validation Result?

The signatures are calculated by the Core whenever a package is to be installed or updated.
1. The signature matches the expected value: No action, the processes continues.
2. No signature is found: Notify the user and ask for the permission to continue.
3. Signature mismatch: The installation/update is rejected and the user is presented an error message explaining the issue.

**All checks will be bypassed when running in developer mode.**

# Where Will the Signatures Be Stored and Retrieved From?

_Which came first: The chicken or the egg?_

This iconic question is quite representative of the challenges for any kind of integrity checks. Over the course of the last years, third party sites run by external developers have been both targeted and in some cases even successfully compromised. Retrieving signatures from these sites does not add any sort of security, since the validity of the provided signatures cannot be verified with certainity.

The Plugin-Store on the other hand provides another level of validation, where any package is reviewed by an independent third party. Any package released to the public has thus been reviewed by at least two different people, the developer and the reviewer. This layer of protection works independently from the integrity of any third party sites, making the Plugin-Store an ideal choice.

Adding the signatures to the existing package lists also eliminates the need for additional APIs, since any installation out there has the official servers registered automatically. The package list of the Plugin-Store will thus serve as the sole authoritative source for signatures, creating a trustworthy foundation for third party modifications.

**Comment by Hanashi** [comment]
I believe this is a good solution, but what is with breaking (not security) bug fixes of a plugin? Will this bug fixes prioritized in the future? For security bug fixes I know, that you priorize this, if we wrote to you.

Example:
I created a plugin, which uses the Twitch API. Twitch is doing now changes on the API. The plugin will now not work. So I create a bugfix and upload it to my store und the official store from WL. The customers on my store could now download the bugfix on my store, but in the official store the customers must wait hours or days and with this solution also the customers must wait on my store. This is a big problem for important bug fixes, which prevent the plugin from running properly.

**Comment by TimWolla** [comment]
> Will this bug fixes prioritized in the future? For security bug fixes I know, that you priorize this, if we wrote to you.

I'm not sure why you got the impression that only security fixes qualify for fast tracking an update. The approval process in the store is not performed by a computer program following a strict flow chart, if you shoot us a message, giving a _proper rationale_ why you believe an update is important it will get fast tracked in ~100% of the cases. A plugin suddenly breaking due to external circumstances (like your Twitch example)? Check. A “bad deploy” (e.g. bad update instructions), preventing customers from successfully updating? Yup. A logic bug eating all of the customer's data? That's a yes. We are interested in our customer's communities running smoothly after all.

In fact I'd say we have a pretty good feeling for the types of updates you load into the store. In many cases I could determine from the version number, the version description or just from the fact that you uploaded a new version 20 minutes after I just approved the previous version that the new version somehow must me important and fast track it.

Of course you shouldn't make the checking process harder than it needs to be for such updates. Intermingling the important changes with a `s/2019/2020/` within every license comment in addition to running an autoformatter across every file _will_ cause the mood of the approvers to drop.

**Comment by earlyhost** [comment]
I like the idea to improve the security of the package installation, however it forces developers to release in the plugin store as otherwise you will get a warning message. There are reasons why various packages are not released in the plugin store. To be honest I do not see a different way to implement such thing, which would be ok for me. 

On the other hand will you enable the installation of plugins using external package servers in the woltlab cloud if and only if the signature matches? This would enable users to purchase plugins outside the plugin-store and ensure a trusted codebase.

**Comment by Hanashi** [comment]
@TimWolla sorry, I believed the prioritized process is only for security fix. I don‘t know, why I believed this. I had this in memory ^^

So I like the idea and believe it‘s good solution.

**Comment by Grischabock** [comment]
Die Idee dahinter finde ich gut, ich hoffe jedoch dass der Prüfprozess durch eventuell umstrukturierungen im Team oder durch Freiwillige Entwickler beschleunigt wird. 

Zu dem ganzen Thema hier aber dazu zu sagen, Woltlab ist eine Deutsche Firma und ich würde jetzt mal über den Daumen schätzen dass 95% aller Entwickler auch aus dem Deutschen Raum kommen. Aus welchem Grund also werden die Diskussionen auf Englisch geführt? Das macht einfach keinen Sinn, Sofern das Thema nur mit Entwicklern geführt werden will dann kann man dies Nachträglich den Kunden in zweisprachiger Ausführung Öffentlich kommunizieren. 
Weiters kommt dazu das Woltlab Anbieter einer Forensoftware ist. Diese ist ja genau für Diskussionen ausgelegt. Warum nutzt man GitHub dazu? Beide der beiden Punkten machen keinen Sinn. Möchte man nämlich Issues ins Git übertragen meinetwegen dann könntet ihr doch auch eine Integration bauen. Viel andere Anwendungen sehe ich darin wirklich nicht. Man möge mich korrigieren.

Der Beitrag soll überhaupt keine schlechte Stimmung verbreiten oder Woltlab in irgendeiner Form angreifen aber vielleicht zum Nachdenken anregen.

**Comment by dtdesign** [comment]
Thank you for your feedback, we'll proceed and start working towards a draft implementation. We'll put up a pull request that will be linked to this issue, allowing you to try it out as soon as it is sufficiently stable. This should allow us to catch issues early on and to ensure a smooth introduction of this validation, without breaking existing workflows.

**Comment by jens1o** [comment]
How do you prevent a vendor lock-in ... imagine when WoltLab is shutting down their services or due to security policies, I don't allow external connections (like in some enterprises)? I'd like to see the product to be as much non-dependent as possible.

**Comment by BurntimeX** [comment]
> How do you prevent a vendor lock-in ... imagine when WoltLab is shutting down their services or due to security policies, the suite isn't allowed to do external connections (like in some enterprises)? I'd like to see the product to be as much non-dependent on foreign services as possible.

In this case the user can still install packages. He will only receive a warning before the installation that the origin of the package could not be verified.

**Comment by dtdesign** [comment]
A first draft has been published at #3443, with one major change:

> Contrary to the suggestion in #3419 even unused files within the archive are being hashed, including LICENSE and similar files. The reason is that it's impossible to statically determine which files are being accessed by a PIP in the general case.

Please take a look at the PR #3443 to learn more about the change and to be able to review the generated data for packages. Feel free to comment if you see any issues with the current approach, in particular any change that could negatively impact your current practices!

**Comment by SoftCreatR** [comment]
What I've experienced when developing a Plugin for XF: Their command line package generator generates a hashes.json file on the fly upon package generation and validates it in several situations. Example file: https://github.com/openauth-dev/XF-OA-OpenAuth/blob/main/upload/src/addons/OA/OpenAuth/hashes.json
