### ISSUE TITLE
The `UserEditForm` should force a rank recalculation

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3446]
The edit form in the admin panel for a single user should force a rank recalculation, reducing the confusion caused by delayed rank recalculations.

**Comment by TimWolla** [comment]
This is already the case since like forever: https://github.com/WoltLab/WCF/blob/dec192f9fac0a293593183223f3f3e9b0d1a3a81/wcfsetup/install/files/lib/acp/form/UserEditForm.class.php#L442-L445
