### ISSUE TITLE
Increase upload limits to more reasonable values

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3457]
The current default value for attachments is 1 MB, which is a bit sparse by today's standards. Increasing it to a higher value would benefit users, while not adding too much pressure on the available storage space. The biggest issue could be the default 2 MB upload limit set by crappy rip-off hosting companies, so we'll have to once again artificially cripple the software to take these into account.

**Comment by TimWolla** [comment]
> The biggest issue could be the default 2 MB upload limit set by crappy rip-off hosting companies, so we'll have to once again artificially cripple the software to take these into account.

Could we detect this limit during the installation and set the default to 5MB or the PHP limit, whichever is smaller?

**Comment by Morik** [comment]
Could be a reason to add [Chunked Uploads](https://community.woltlab.com/thread/266577-chunked-upload/?postID=1664404) to 5.3.

**Comment by dtdesign** [comment]
Solution: Bump the default limit to 2 MB and run a check during the installation to see if there are larger limits. If the system permits larger uploads, bump it to 5 MB.
