### ISSUE TITLE
TelegramUserOptionOutput

### ISSUE THREAD

**Issue by TitusKirch** [WoltLab/WCF#3481]
I would like to have, by default, a "Telegram user option field". Since I have already built something like this as my own extension, I would like to include it with a PR, if others would like it as well.

**If who is faster than me, here the regex and the link to the Telegram profiles:**
Regex: `^$|^[a-zA-Z0-9\_]{5,32}$`
URL: `https://telegram.me/{$username}`

**Comment by dtdesign** [comment]
These kind of profile fields can easily be added through plugins without the need to ship them by default. That's the prime reason why the existing profile fields have been left untouched for quite some time, there are simply too many services that could be useful, but only a fraction while be used for each community.

**Comment by TitusKirch** [comment]
For a service with well over 400 million users, I wouldn't say that it is only used by a fraction of the community, but thanks for the answer.
