### ISSUE TITLE
PHP 8: SystemCheck reports the PHP version with a red triangle

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3491]
It also strips the “Beta” indicator from the human readable version number, pretending that PHP 8.0.0beta1 is PHP 8.0.0.

- [ ] Do not report PHP 8 with a red triangle after all PHP 8 issues are fixed.
- [ ] Check if WCFSetup also needs to be adjusted.

**Comment by dtdesign** [comment]
This issue is blocked until PHP 8.0 GA is released and we have verified that the software runs stable with this version.

The wiki states Nov 26 as the release date: https://wiki.php.net/todo/php80

**Comment by TimWolla** [comment]
Closing this without changes to WoltLab Suite 5.3:

- imagick as a key extension still is not yet available as an _official_ release for PHP 8.
- The necessary changes to resolve this issue have already been performed in master / WoltLab Suite 5.4 as part of the PHP 7.2 minimum requirement adjustments.
