### ISSUE TITLE
Reading updateservers fails due to feof

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3529]
server url: `https://update.mysterycode.de/hurricane/` (you need to use the WSC's user agent for getting the XML-stuff)

thrown error within the client's ACP
```
Beim letzten Verbindungsversuch trat folgender Fehler auf:
feof(): supplied resource is not a valid stream resource
```

using `nginx/1.19.2` and PHP `7.4.9` (FPM) currently on Debian `9.13`
curl is enabled witin PHP using `7.52.1` using `OpenSSL/1.0.2u`
the server responds with status code 304 and an empty body if nothing changed since the last "download" (according to the API used since WSC 3.0 I think)
the XML output is generated by the WSC-XML-Utils and provided by `echo` and a following `exit`
WSC 5.2 and earlier are not throwing an error while reading the same server using the same URL and credentials

I didn't check the new API and didn't debug yet.

any ideas yet?

**Comment by TimWolla** [comment]
I can reproduce the issue outside of the package server system with:

```
		$request = new \wcf\util\HTTPRequest('https://update.mysterycode.de/hurricane/');
		$request->execute();
		var_dump($request);
		var_dump($request->getReply());
		exit;
```

Somehow the explicit sink is at fault: https://github.com/WoltLab/WCF/blob/95939e32de17b466f6588dd150c9bc0fd29fa42a/wcfsetup/install/files/lib/util/HTTPRequest.class.php#L195
