### ISSUE TITLE
Tooltip of disabled buttons not shown

### ISSUE THREAD

**Issue by ilouHD** [WoltLab/WCF#3533]
I have the following situation: I have a button in the ACP, that is disabled. To display a reason, why the button is disabled, I want to use tooltips. So I added a tooltip to the disabled button like this:
```
                <a href="" class="button jsTooltip disabled" title="Bearbeiten nicht mehr möglich">
                    <span class="icon icon16 fa-edit"></span> Bearbeiten
                </a>
```

But now the tooltip doesn't show up on mouse enter. When I remove the class "disabled" from the element, the tooltip is shown as expected. So the "disabled"-class not only disables the button, but also the tooltip.

I couldn't find any reason in the [Tooltip.js](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Tooltip.js) that explains this behaviour, but I think tooltips shouldn't behave like that.

Please fix this.

**Comment by dtdesign** [comment]
The `disabled` class sets `pointer-events: none` which makes the element unresponsive to any mouse interaction. This will also prevent any "hover"-class events from being fired.

https://github.com/WoltLab/WCF/blob/75631516d45f9355f6c73d6375bf804d2abd587e/wcfsetup/install/files/style/ui/button.scss#L107
