### ISSUE TITLE
Leading and trailing whitespace within [tt] is not properly being preserved

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3536]
```
[tt] foo [/tt]
"foo"
[tt]  foo  [/tt]
"  foo "
```
Leading space: A single whitespace is removed, anything more is preserved in full.
Trailing space: One whitespace is removed for all lengths.

**Comment by dtdesign** [comment]
They are actually not removed, but the browser does not display them. The issue appears to be that those whitespaces are just plain whitespace and not protected ones, such as `&nbsp;`.
