### ISSUE TITLE
Show named user exception information in UI in dev mode

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3541]
Change

https://github.com/WoltLab/WCF/blob/62b1c5c2deee8b18220fc692dde1577b77c516ed/com.woltlab.wcf/templates/userException.tpl#L27-L31

to be shown in the UI if dev mode is enabled for quicker information on the origin of the exception without having to check the page soure.

**Comment by dtdesign** [comment]
I have opted for a simpler appraoch by also printing the validation error to the console. Showing it in the UI might not always be useful and it imposes a lot of questions in terms of styling.

**Comment by TimWolla** [comment]
@dtdesign You mixed up NamedUserException and UserInputException.
