### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by TitusKirch** [WoltLab/WCF#3562]
Since GitHub will now officially change the default name to main, I would suggest this for the WCF. But I would also like to call for a peaceful and objective discussion (maybe it works better here than in the forum)

Reference: https://github.com/github/renaming#from-master-to-main

**Comment by SoftCreatR** [comment]
Why discuss this, if this is going to happen anyways?

**Comment by TitusKirch** [comment]
If I understand this correctly, the default will later become main and for exiting projects only a tool for easy renaming will be provided later this year.

**Comment by dtdesign** [comment]
We're actively monitoring the changes happening at GitHub in this regard. At this time it is not supported to rename the default branch of an existing repository, but they are working on it. Since this is independently tracked, I'll close this one for housekeeping.

**Comment by SoftCreatR** [comment]
> At this time it is not supported to rename the default branch of an existing repository

Sure it is.

**Comment by TimWolla** [comment]
> Sure it is.

According to the [github/renaming](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) repository this is not *well-supported* at the very least.

**Comment by SoftCreatR** [comment]
https://github.com/SoftCreatR/almost-naked
https://github.com/openauth-dev/SocialiteOpenAuthProvider
...

Works fine for me.
