### ISSUE TITLE
Add a persistenter runtimecache

### ISSUE THREAD

**Issue by TitusKirch** [WoltLab/WCF#3564]
In my opinion, the cache system is currently very simple and you quickly reach its limits.

I would suggest to extend the cache system with a "persistenter runtimecache". Other frameworks like Laravel (https://laravel.com/docs/8.x/cache) do a similar thing. Here I can load objects from the cache and if they do not exist, they are created and stored in the cache for time X (or forever).

**Comment by TitusKirch** [comment]
I was told that there was something similar. So a cache where you could add and get entries with e.g. `set($cacheName, $key, $value, $seconds)` and `get($key)`. If this is true, what was the reason to remove it?

**Comment by dtdesign** [comment]
There is no cache for arbitrary data, but you have both the "regular" caches and the runtime cache at your disposal. Please take a look at https://docs.woltlab.com/php_api_caches.html, it provides further information on both types as well as a guide for the proper use of caches (and when not to use them!).

**Comment by TitusKirch** [comment]
The two current cache types are known to me and I use them regularly. I am also aware of what to cache which data and when it is rather counterproductive.

But that was not the topic of my issue. I wanted to suggest to add a new cache type. In my opinion it is not always smart to store all objects of a datatype persistent. It would make more sense, similar to the runtime cache, to save the data only after it has been called once. But the RuntimeCache only runs (as the name says) at runtime and is therefore not persistent. I would just like a symbiosis of RuntimeCache and CacheBuilder.

Maybe now it is better clear what I was getting at.

**Comment by dtdesign** [comment]
The cache system was designed this way to provide solutions for actual problems and they are quite scoped to avoid luring developers into using caches when they shouldn't. A persistent cache has a significant cost attached to it, no matter what implementation or backend you are using, so it should be avoided unless there is an actual need.

I'm having a hard time imagining a situation neither a regular cache nor the runtime cache solves your problem. Maybe you can go a bit more into detail to understand the problem you are dealing with?

**Comment by TitusKirch** [comment]
I will try to summarize my current situation.

I write an extension in which it is possible to create documentation. For each documentation, you store a repository (e.g. one on GitHub). Each branch reflects a version of the documentation and each markdown file reflects a page. E.g. the path could look like `/documentation/version/path/to/file` and the extension would look if this documentation exists and if so, load the corresponding file from the deposited repository and the requested version/branch.

I then came up with the following ideas/possibilities:

**Option 1) Always load data live:**
Loading the files always live from the repository is a miserable idea, so I won't go into it here.

**Option 2) Load all files once and cache them:**
There are two problems here
1. the whole thing should be dynamic and the admin should not be forced to put all files in the ACP somehow
2. let's say we have 5 documentations with an average of 5 versions and 30 pages. Here we would then already have 750 requests that would have to be made to load all pages.

**Option 3) Load file on request and save it in the database:**
Here you could even save the pages with timestamps and have them deleted and reloaded if necessary (possibly even automated via. cronjob and/or with a webhook).
However, this was a bit slow in the test with several requests and the largest single page.

**Option 4) Option 3 and caching:**
Now you could use a CacheBuilder to store the entries from the database. But if we stick to our 750 requests/pages and say that a page has an average of 50,000 characters (parsed), we would have to cache more than 37,500,000 characters just for the content. Probably not even all pages are called in an interval X and in a simple test (where I had created many Lorem Ipsum entries), I already noticed a reduction in speed.

**Option 5) Cache only requested pages;**
And this would then also be what I am getting at. I would only want to cache requested files (e.g. for time X) and then reload them from the DB. A comparison in Laravel showed that I was able to improve the loading times (to be fair, I had loaded everything from the database before I cached the requested entries).


However, I am open for further approaches to solutions.

Here is a similar solution from the official Laravel documentation:
https://github.com/laravel/laravel.com-next/blob/master/app/Http/Controllers/DocsController.php
https://github.com/laravel/laravel.com-next/blob/master/app/Documentation.php

**Comment by TimWolla** [comment]
> **Option 3) Load file on request and save it in the database:**
> Here you could even save the pages with timestamps and have them deleted and reloaded if necessary (possibly even automated via. cronjob and/or with a webhook).
> However, this was a bit slow in the test with several requests and the largest single page.

Once the page is locally stored this should not be worse than e.g. pulling a thread or user from the database, provided that your database table is properly indexed.

>  And this would then also be what I am getting at. I would only want to cache requested files (e.g. for time X) and then reload them from the DB. A comparison in Laravel showed that I was able to improve the loading times (to be fair, I had loaded everything from the database before I cached the requested entries).

You can do this by leveraging the `$parameters` parameter of the cache builder. However I expect this to be slower compared to simply pulling a properly indexed row from the database.

**Comment by TitusKirch** [comment]
> Once the page is locally stored this should not be worse than e.g. pulling a thread or user from the database, provided that your database table is properly indexed.

Since I use Redis for caching (of course not everyone does) this would be faster than loading from the "normal" database.

> You can do this by leveraging the $parameters parameter of the cache builder. However I expect this to be slower compared to simply pulling a properly indexed row from the database.

Do I understand correctly that I could pass an entry as parameter and add it to the cache? If so, you might be able to send a small example.

> [...] they are quite scoped to avoid luring developers into using caches when they shouldn't. [...]

@dtdesign Personally I am a fan of giving the developers freedom (if you let them in your stream is again your decision).



All in all, I will of course be able to develop the product with the current means (how performant this is in comparison to other solutions, it remains to be seen). The whole thing was just a suggestion to expand the WSC.

**Comment by TimWolla** [comment]
> Since I use Redis for caching (of course not everyone does) this would be faster than loading from the "normal" database.

Not necessarily. Redis shines for write-heavy load, because it does not need to persist to disk. When the database pages of the table in question are loaded into memory (“buffer pool”) MySQL is plenty fast for read queries and you are not going to be able to measure a noticeable difference for a single query.

> Do I understand correctly that I could pass an entry as parameter and add it to the cache? If so, you might be able to send a small example.

```
MyPageCacheBuilder::getInstance()->getData(['url' => '/documentation/version/path/to/file']);
```

And `MyPageCacheBuilder` would then pull the proper file from the data source depending on `$parameters['url']`.

**Comment by TitusKirch** [comment]
Thanks. I will try it after my exams.

**Comment by dtdesign** [comment]
@TitusKirch Any news on this?

**Comment by TitusKirch** [comment]
@dtdesign Oh oh sorry, now a few things have come up. But I will definitely look into it next week. I would ask you not to close this until then.

**Comment by TitusKirch** [comment]
@TimWolla the small example from your last message helped me a lot. It is not what I had hoped for, but it solves my "problem".

I will close the issue with this and thank you for your patience.
