### ISSUE TITLE
Migrate FileUtil::downloadFileFromHttp() users to Guzzle

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3618]
`downloadFileFromHttp()` by now is a compatibility layer for a compatibility layer. Uses within WoltLab/WCF should be modernized.

**Comment by joshuaruesweg** [comment]
Whether an adjustment is still worthwhile here? The method is deprecated anyway and should not be used anymore.

**Comment by TimWolla** [comment]
Sorry, I was being unclear. Adjust the *users* of this method so that it no longer is used within our code.
