### ISSUE TITLE
Log out of all sessions when the password is changed

### ISSUE THREAD

**Issue by joshuaruesweg** [WoltLab/WCF#3641]
If the password is changed, the user should be automatically logged out of all sessions except the active session (if the user changes the password themselves).

**Comment by TimWolla** [comment]
see also #3635

**Comment by TimWolla** [comment]
Not sure if this is necessary with #3640. Maybe just add a prominent note to the password field and a large button “log out everything else” at the top of #3640?

**Comment by joshuaruesweg** [comment]
I thought about it, but rejected the idea, because the user usually assumes that other people will not have access to his account if he changes the password (e.g. after his account has been compromised).  Very few users change their password out of boredom.
