### ISSUE TITLE
Remove closest.js polyfill?

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3655]
https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/js/closest.js

**Comment by dtdesign** [comment]
It can be safely removed, it was required for IE11 only. We can also get rid of the Promise polyfill.

**Comment by TimWolla** [comment]
> We can also get rid of the Promise polyfill.

That one is already gone, because I knew myself how exactly it worked: d0e11bc7f25013728c1cab7984f0d2ec84d2859f
