### ISSUE TITLE
RemoteFile TODO in ImageProxyAction

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3660]
Check if the TODO in https://github.com/WoltLab/WCF/blob/99735c4fd202ffe0c4dbaed6d5cbd785928da0bf/wcfsetup/install/files/lib/action/ImageProxyAction.class.php#L101-L102 is still relevant with the internal change to Guzzle.

**Comment by TimWolla** [comment]
In fact that check needs to be updated. It might make sense to switch ImageProxy to Guzzle. It's a prime candidate for the streaming improvements and without the translation later in between handling the Exception becomes easier.
