### ISSUE TITLE
Remove Dialog from ACP's LoginForm

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3733]
It will clash from a styling perspective with the upcoming MFA integration and it serves no benefit except for "looking nice" (which of course boils down to a personal preference). In fact it even comes with the drawback that it requires the page to fully load before it can be interacted with.

Related to #3732

**Comment by dtdesign** [comment]
The current implementation isn't perfect, but works best for full backwards compatibility with third party logins or modifications. Also the behavior is consistent between the front- and the backend which adds security through known form elements/behaviors.
