### ISSUE TITLE
Banned user can request a new password

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3741]
n/t

**Comment by TimWolla** [comment]
I'm not sure if I'd call this a bug:

1. Users might only be temporarily banned.
2. Preventing the password request will leak information about personal information (the ban status) to an unauthenticated third party.

**Comment by dtdesign** [comment]
Displaying a proper error message is quite some effort for such a small change and this would indeed leak informations to third parties. It was just an idea, but there are too many downsides to this.
