### ISSUE TITLE
user.lastActivityTime is not reliably updated

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3776]
`lastActivityTime` is set by a cronjob based on the active sessions. If the user has logged out before the cronjob is run, the column will not be updated.

Solution:
- [ ] set `lastActivityTime` during registration
- [ ] ~~set `lastActivityTime` during logout~~

**Comment by TimWolla** [comment]
> If the user has logged out before the cronjob is run, the column will not be updated.

The timestamp *should* already be updated when the session is being destructed during logout: https://github.com/WoltLab/WCF/blob/46ba4035650c25be46703d8f6d0e6cf533caf53b/wcfsetup/install/files/lib/system/session/SessionHandler.class.php#L972
