### ISSUE TITLE
Submitting UserEditForm always deletes all sessions

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3780]
This is due to this line not checking whether `password !== ''` : https://github.com/WoltLab/WCF/blob/a480c62ba78c3f1271b850a799d7b8af16486c7a/wcfsetup/install/files/lib/data/user/UserAction.class.php#L331

Adding that check feels like an implementation detail, though. Should the session deletion possibly be moved to UserEditor?

**Comment by dtdesign** [comment]
The check should only check if the key is `!empty()` which covers all cases. I don't see much benefit of moving it to the `UserEditor`, given the theoretical impact of this modification I would rather not introduce a possibly unexpected change.

**Comment by TimWolla** [comment]
> The check should only check if the key is `!empty()` which covers all cases.

No, it does not. `null` is a valid value to indicate the `invalid:` password hash. This is used when sending a new password within the ACP.

**Comment by dtdesign** [comment]
Good point, so adding a check against an empty string should do fine. My argument against moving the code elsewhere still stands.

**Comment by joshuaruesweg** [comment]
Somehow the behaviour is confusing. Wouldn't it have been better not to pass the parameter in the UserEditForm at all? Unfortunately, it is difficult to adjust the behaviour now, so I am fixing the error accordingly.
