### ISSUE TITLE
Clear filesystem cache when switching to redis

### ISSUE THREAD

**Issue by LucaDev** [WoltLab/WCF#3784]
Whenever the cache get set to redis/memcached, the filesystem cache should be cleared.

Without it, a website could break as soon as the cache provider isn't available/turned off, because there's a incompatibility between the current running version and the WCF/application/plugin the filesystem cache was build with originally.

**Comment by BurntimeX** [comment]
Deleting the filesystem cache when changing the cache method in the configuration would only help once here, since the filesystem cache would be recreated again on the next fallback case and would remain permanently (until the problem eventually occurs again).

**Comment by LucaDev** [comment]
Yeah. You're absolutely right. I see two obvios solutions:
a) completely disable the fallback cache and make it obvious to the administrators that the cache is offline
b) always check/rebuild the fallback cache(filesystem) too whenever redis/memcached is updated
