### ISSUE TITLE
Proxy the favicon for multi domain setups

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3795]
We cannot embed the favicon from a different domain, because this would cause issues if the image is being processed in a canvas ("dirty"). The favicon library ("favico.js") does support loading images from crossorigin contexts, but this requires the server to set proper headers.

Since we cannot rely on webservers to be configured properly, we should proxy the favicon through a PHP file to force set the headers. Granted that browsers love to cache favicons for an eternity, this shouldn't cause any significant extra load, plus favicons are usually rather tiny.

On the bright side this will allow us to remove the base64 puke that is currently being generated in these instances.

**Comment by TimWolla** [comment]
This will solve itself with #3859
