### ISSUE TITLE
Get default style in cronjob?

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#3800]
I was trying to get the default style in a cronjob by using `WCF::getStyleHandler()->getDefaultStyle()`, unfortunately does this throw the `Illegal request` exception.

What's the proper way to get the default style for a cronjob as `getStyle()` would get the style of the user who is executing the cronjob in the background?

https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/style/StyleHandler.class.php#L251

**Comment by dtdesign** [comment]
This should do:
```php
$defaultStyle = array_filter(StyleHandler::getInstance()->getStyles(), function ($style) {
	return !!$style->isDefault;
})[0];
```

**Comment by Sir-Will** [comment]
I didn't think about that approach, thanks.

Small adjustment as it's not always 0.
```php
$defaultStyle = array_filter($styles, function ($style) {
      return !!$style->isDefault;
});
$defaultStyle = reset($defaultStyle);
```
