### ISSUE TITLE
Move `<title>` after `<meta charset="utf-8">`

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3802]
The page's title might contain unicode characters and thus probably should appear after the charset tag.

**Comment by joshuaruesweg** [comment]
Is there a specific reason for the meta tag? Can't we better use a header for it and remove the tag?

**Comment by TimWolla** [comment]
> Can't we better use a header for it and remove the tag?

We already add the `charset` attribute within the `content-type` response header (at least for responses that go through the template engine): https://github.com/WoltLab/WCF/blob/ea75158ea9cb971449b2c518cafd9a2312430fd7/wcfsetup/install/files/lib/util/HeaderUtil.class.php#L67

It *should* be possible to remove the `charset` meta tag, but having it gives me a bit of peace of mind, because I know that bogus web server configurations will not mess with it. Especially since the correct document charset is somewhat security critical.
