### ISSUE TITLE
Recommend PHP's intl extension

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3811]
intl is no hard requirement, but it makes things better. So it should be a recommendation like cURL is: https://github.com/WoltLab/WCF/blob/439de4963c947c3569a0c584f795245f693155b0/wcfsetup/install/files/lib/system/WCFSetup.class.php#L389

**Comment by dtdesign** [comment]
What do we need `intl` for?

**Comment by TimWolla** [comment]
1. https://github.com/WoltLab/WCF/blob/fbbb20ec0da9d99c97186b911465053a7dc406cf/wcfsetup/install/files/lib/system/api/ezyang/htmlpurifier/library/HTMLPurifier/AttrDef/URI/Host.php#L98-L104
2. https://github.com/WoltLab/WCF/blob/439de4963c947c3569a0c584f795245f693155b0/wcfsetup/install/files/lib/util/FileReader.class.php#L207

intl for (1) would allow to remove this dependency: https://github.com/WoltLab/WCF/tree/fbbb20ec0da9d99c97186b911465053a7dc406cf/wcfsetup/install/files/lib/system/api/pear/net_idna2
