### ISSUE TITLE
Ignore specific folders when scanning a dev tools project

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3830]
Some folders can get pretty huge and are not required for proper plugin operation. They should be skipped when scanning the project to improve performance.

- [ ] Top level `.git`
- [ ] Top level `node_modules`

**Comment by Gravatronics** [comment]
When would those folders be scanned in the dev tools?

**Comment by Gravatronics** [comment]
`DirectoryUtil` does not support filtering during scanning, only after having collected all files.

**Comment by TimWolla** [comment]
Ideally the use of DirectoryUtil would be replaced by a simple DirectoryIterator, which should be way more memory efficient anyway.
