### ISSUE TITLE
Deprecate multi domain setups

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3859]
Multi domain setups have been semi supported for quite some time, but they are a constant source of issues while bringing little to no value to the table. CORS is the most prominent case for added complexity to support these setups, this also applies to the crippled `localStorage` to some extent. This indirectly also causes the app domain management to be overly complex, instead of providing a simple interface with proper safeguards against misconfigurations.

This change does not impact the ability to assign cookies to the domain apex.

Proposed roadmap:
* 5.4: Deprecate multi domain setups and add a warning if such a setup is found.
* 5.5: Remove the support for multi domain setups.

**Comment by mutec** [comment]
Are you going to cancel the support for multiple subdomains too?
I'd prefer to be able to use a subdomain for every application if I want.

**Comment by dtdesign** [comment]
Entirely different domains `example.com` for app A and `example.org` for app B have never been supported, because it is impossible to share a single cookie between them.

The user of different subdomains for apps, such as `a.example.com` for app A and `b.example.com` for app B are refered to as "multi domain setups" and will be deprecated and eventually removed in the future. The support for cookie sharing using the domain apex will remain.

**Comment by TitusKirch** [comment]
> 5.5: Remove the support for multi domain setups.

But this would be an API-incompatible change and I thought you guys wanted to get into [Semantic Versioning 2.0.0](https://semver.org)  now.

**Comment by dtdesign** [comment]
> But this would be an API-incompatible change and I thought you guys wanted to get into [Semantic Versioning 2.0.0](https://semver.org) now.

First of all, this isn't part of the (public) API at all, it is merely a feature that allows you to utilize different subdomains.

Second, this is a pure gimmick feature that adds zero real value, but comes with a hefty tax on the development. The hidden cost of that feature is quite significant, because apart from the initial design and development phase, we and other developers have to constantly be aware of the consequences such as CORS. Not only is it something that needs to be considered for changes and new features, it also cripples the localStorage, severly holding us back on innovations that would built on top of that.

Frankly, there will never be a 100% backwards compatibility, because we have to make progress at some point and cannot postpone innovations till eternity. Just look at the code of how many sections have been deprecated for years and are still part of the API. We do take this seriously, but at times have to make sacrifices, because this is the real world and not a contained lab environment.

**Comment by TitusKirch** [comment]
Please don't get me wrong, I am not against this change. I just still find it very hard to understand your versioning because you feel every two versions change it or don't follow through 100%.

The argumentation regarding the X increase I can not quite follow, here I see more a homemade problem.

**Comment by dtdesign** [comment]
I do not see this as being an API change at all, because at worst some workarounds (such as CORS-proxies) will be superfluous, but they will not break or otherwise stop working.

We regularly run checks against all submissions in the Plugin-Store to identify potential problems ahead of time. In addition to that we reach out to 3rd party developers in case they might be affected by some subtle, yet rather obscure changes.

**Comment by mutec** [comment]
However it's (the removal of that feature) a change requiring a lot of work for users since they might have to change the whole directory structure and/or do new rewrite-rules and directory-mapping. It's definitely no change I'd expect for a change inside the 5.x series. ;)

**Comment by dtdesign** [comment]
Absolutely and we're very well aware of this, considering that this does apply to our very own site too. But at the end of the day, it is just a gimmick feature that is used by an absolute minority, without providing any value. It simply does not justify holding back innovation for many more releases to come.

**Comment by TitusKirch** [comment]
And what's wrong with just "sticking" to the versioning and switching to 6.x.x? Except now that many users expect new great features? I would just like to understand.

**Comment by dtdesign** [comment]
Users expect a version 6.0 to include serious breaking changes and are hesitant to make an upgrade, fearing that the installed plugins and styles will break. However, this is a change that does not affect 99,99% of users at all, because they did not opt for this gimmick feature.

A warning will be displayed in 5.4, giving the handful of affected users at least half a year to plan ahead. Again, this isn't a contained lab environment in a perfect world, in reality there will always be tradeoffs.

**Comment by Af0x** [comment]
I am really interested in what "innovation" is held back by multi domain support. Also, having more work is not a reason to remove an existing feature. The minority that you speak of are the ones with complex setups and although you as developers are happy about having less work, the people making extensive usage of this feature, including me, are not quite happy about this change and you take away a lot of possibilities by removing this feature. Lastly this feature has an impact on the rating by search engines so, as happy as you are, maybe you can reconsider your decision.

**Comment by Af0x** [comment]
Any feedback on my questions @dtdesign ?
So if I see this correctly you just postponed the removal? As I am looking for reliability and stability in this case this is not quite satisfying.

**Comment by dtdesign** [comment]
Indeed, the removal has been pushed back by one release. This has to do with other planned changes on the internal roadmap that are more closely tied to this change.

However. the decision to remove the multi domain support is final.
