### ISSUE TITLE
Suppress unsupported image types for avatars in emails

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3864]
Email clients are notorious for their incredibly bad support for modern HTML and CSS. The widespread use of email clients that are incappable of modern image formats are a constant source of confusion for administrators. We should dynamically modify the output of avatars in emails to provide a better experience:

* [x] Force disable WebP avatars and use the fallback image instead.
* [x] The default avatar must not yield a SVG, we must provide a "regular" image format. JPEG is a sufficient alternative.
* [ ] Adjust the email templates.

**Comment by TimWolla** [comment]
All resolved. For posteriority I searched the affected templates via:

```
ag -Q -G 'email_.*.tpl' -- '->getAvatar()->getImageTag('
```
