### ISSUE TITLE
Change default dev installation password

### ISSUE THREAD

**Issue by joshuaruesweg** [WoltLab/WCF#3866]
Since Chrome reports the current password combination (`root:root`) as insecure with every login, we should change the default password for the `root` account to `wl` in a developer installation.

**Comment by TimWolla** [comment]
> we should change the default password for the `root` account to `wl` in a developer installation.

Maybe the username should also be adjusted (unless Chrome detects that the Username = Password?) to make both values consistent again.

**Comment by joshuaruesweg** [comment]
The name `wl` is too short, to use it as default username. We require at least three characters for a username.

**Comment by dtdesign** [comment]
`dev:root` or `dev:woltlab` should do? (`username:password`)

**Comment by joshuaruesweg** [comment]
`dev:root` or `dev:woltlab` is fine, too. I think `dev:root` is the best solution, I will fix it in master only (?).
