### ISSUE TITLE
Usage of deprecated PHP (1)

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3880]
- [ ] `Class 'IPrintableException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install.php#L494
- [x] `Method 'getDoubleSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/MasterPasswordInitForm.class.php#L102
- [ ] `Field 'rankImage' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/UserRankAddForm.class.php#L250
- [ ] `Field 'rankImage' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/UserRankAddForm.class.php#L281
- [ ] `Field 'rankImage' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/UserRankEditForm.class.php#L107
- [x] `Method 'getDoubleSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/MasterPasswordForm.class.php#L68
- [ ] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/DataImportForm.class.php#L5
- [ ] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/DataImportForm.class.php#L207
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/page/TemplateListPage.class.php#L120
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/like/LikeAction.class.php#L10
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/like/LikeAction.class.php#L162
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/like/LikeAction.class.php#L200
- [ ] `Field '$avatarThumbnailSizes' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/user/avatar/UserAvatarEditor.class.php#L58
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/user/avatar/UserAvatarAction.class.php#L16
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/user/avatar/UserAvatarAction.class.php#L102
- [ ] `Method 'markAsConfirmedByID' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/user/notification/UserNotificationAction.class.php#L214
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/style/StyleEditor.class.php#L887
- [x] `Field '$compatibilityApiVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/style/StyleEditor.class.php#L976
- [x] `Field 'highlighters' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/bbcode/BBCodeCache.class.php#L77
- [x] `Field 'highlighters' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/bbcode/BBCodeCache.class.php#L78
- [x] `Field 'highlighters' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/bbcode/BBCodeCache.class.php#L81
- [x] `Class 'TLegacyUserPropertyAccess' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/comment/ViewableComment.class.php#L5
- [x] `Class 'TLegacyUserPropertyAccess' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/comment/ViewableComment.class.php#L20
- [x] `Class 'TLegacyUserPropertyAccess' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/comment/response/ViewableCommentResponse.class.php#L5
- [x] `Class 'TLegacyUserPropertyAccess' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/comment/response/ViewableCommentResponse.class.php#L20
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/package/PackageAction.class.php#L9
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/package/PackageAction.class.php#L98
- [ ] `Field 'permissions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/category/Category.class.php#L210
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/template/Template.class.php#L56
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/template/TemplateList.class.php#L48
- [x] `Class 'RecaptchaHandlerV2' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/form/RecaptchaForm.class.php#L3
- [x] `Class 'RecaptchaHandlerV2' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/form/RecaptchaForm.class.php#L68
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/FileUtil.class.php#L429
- [ ] `Method 'getSchema' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/XML.class.php#L105
- [x] `Constant 'BCRYPT_COST' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L95
- [x] `Method 'wcf1e' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L139
- [x] `Method 'getRandomSalt' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L165
- [x] `Method 'getSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L168
- [x] `Method 'getSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L168
- [x] `Method 'getRandomSalt' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L176
- [x] `Field '$blowfishCharacters' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L188
- [x] `Field '$blowfishCharacters' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L189
- [x] `Method 'secureRandomNumber' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L189
- [x] `Method 'getSalt' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L192
- [x] `Method 'secureRandomNumber' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L206
- [x] `Method 'randomInt' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L230
- [x] `Constant 'BCRYPT_TYPE' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L244
- [x] `Constant 'BCRYPT_COST' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L244
- [x] `Method 'vb3' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L258
- [x] `Method 'phpass' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L279
- [x] `Method 'smf1' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L374
- [x] `Method 'vb3' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L388
- [x] `Method 'vb3' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L395
- [x] `Method 'getDoubleSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L474
- [x] `Method 'getSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L492
- [x] `Method 'joomla1' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L514
- [x] `Method 'joomla1' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L521
- [x] `Method 'getSaltedHash' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L539
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/TwitterAuthAction.class.php#L12
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/TwitterAuthAction.class.php#L73
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/TwitterAuthAction.class.php#L130
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/TwitterAuthAction.class.php#L179
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/GravatarDownloadAction.class.php#L10
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/GravatarDownloadAction.class.php#L72
- [x] `Class 'IPrintableException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/WCF.class.php#L21
- [ ] `Class 'IPrintableException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/WCF.class.php#L275
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/WCF.class.php#L1077
- [ ] `Field '$supportedLegacyApiVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/WCF.class.php#L1136
- [ ] `Field '$supportedLegacyApiVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/WCF.class.php#L1146
- [ ] `Class 'Callback' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/Regex.class.php#L207
- [ ] `Method 'load' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/CLIWCF.class.php#L233
- [x] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/cli/command/ImportCLICommand.class.php#L5
- [ ] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/cli/command/ImportCLICommand.class.php#L214
- [x] `Class 'self' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/mail/Mail.class.php#L377
- [x] `Method 'getUserProfiles' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/GroupedUserList.class.php#L113
- [x] `Method 'getUserProfiles' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/UserNotificationHandler.class.php#L476
- [ ] `Class 'IEventListener' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/event/EventHandler.class.php#L6
- [ ] `Class 'IEventListener' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/event/EventHandler.class.php#L117
- [ ] `Class 'ILegacyEventListener' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/event/EventHandler.class.php#L143
- [ ] `Class 'IEventListener' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/event/EventHandler.class.php#L204
- [ ] `Class 'ILegacyEventListener' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/event/EventHandler.class.php#L227
- [ ] `Field '$attachmentList' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php#L60
- [ ] `Field '$attachmentList' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php#L61
- [ ] `Field '$objectID' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php#L61
- [ ] `Field '$attachmentList' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php#L191
- [ ] `Field '$objectID' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php#L201
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/TexHighlighter.class.php#L14
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PlainHighlighter.class.php#L14
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/BashHighlighter.class.php#L13
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PythonHighlighter.class.php#L13
- [x] `Class 'XmlHighlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/HtmlHighlighter.class.php#L16
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/HtmlHighlighter.class.php#L24
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/HtmlHighlighter.class.php#L57
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/DiffHighlighter.class.php#L14
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/XmlHighlighter.class.php#L16
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/XmlHighlighter.class.php#L58
- [x] `Class 'self' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/XmlHighlighter.class.php#L60
- [x] `Class 'XmlHighlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/XmlHighlighter.class.php#L63
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/XmlHighlighter.class.php#L76
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/XmlHighlighter.class.php#L90
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/JavaHighlighter.class.php#L13
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/SqlHighlighter.class.php#L15
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/JsHighlighter.class.php#L13
- [x] `Class 'HtmlHighlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/TplHighlighter.class.php#L14
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/TplHighlighter.class.php#L19
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/CssHighlighter.class.php#L13
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/CssHighlighter.class.php#L30
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/CssHighlighter.class.php#L44

(generated using a PhpStorm inspection)

**Comment by TimWolla** [comment]
I checked off all the highlighters complaining about their parent class being deprecated, because these deprecations are tied together.

**Comment by TimWolla** [comment]
>     * Field 'highlighters' is deprecated

Access of a deprecated property in a deprecated method of the same class. Checking this one off.

**Comment by TimWolla** [comment]
:point_up: applies likewise to all the `PasswordUtil` methods.

**Comment by TimWolla** [comment]
>     * Class 'self' is deprecated

Checking this off, because the full class is deprecated.

**Comment by TimWolla** [comment]
>     * Method 'getDoubleSaltedHash' is deprecated
(In MasterPasswordInit)

The master password itself is deprecated, thus this can be ignored.

**Comment by TimWolla** [comment]
>     * Class 'RecaptchaHandlerV2' is deprecated
(In RecaptchaForm)

RecaptchaForm is deprecated, thus this can be ignored.

**Comment by TimWolla** [comment]
>     * Class 'HTTPRequest' is deprecated
(in GravatarDownloadAction)

Gravatars are deprecated, thus this can be ignored.

**Comment by Gravatronics** [comment]
See #4281
