### ISSUE TITLE
Usage of deprecated PHP (2)

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3881]
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/CHighlighter.class.php#L13
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PerlHighlighter.class.php#L13
- [x] `Class 'Highlighter' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PhpHighlighter.class.php#L14
- [x] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PhpHighlighter.class.php#L21
- [x] `Class 'self' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PhpHighlighter.class.php#L25
- [x] `Class 'self' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PhpHighlighter.class.php#L27
- [x] `Class 'self' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/bbcode/highlighter/PhpHighlighter.class.php#L75
- [x] `Constant 'INVALID_API_VERSION' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageArchive.class.php#L308
- [x] `Field 'compatibility' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageArchive.class.php#L311
- [x] `Field 'compatibility' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageArchive.class.php#L315
- [x] `Field 'compatibility' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageArchive.class.php#L621
- [x] `Method 'getCompatibleVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageInstallationDispatcher.class.php#L556
- [x] `Method 'getCompatibleVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageInstallationDispatcher.class.php#L562
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageInstallationDispatcher.class.php#L945
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L14
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L116
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L154
- [x] `Constant 'INVALID_API_VERSION' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L458
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L14
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L227
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L237
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageUpdateUnauthorizedException.class.php#L6
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/PackageUpdateUnauthorizedException.class.php#L42
- [ ] `Constant 'AUTOMATIC_NAME_PREFIX' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/plugin/EventListenerPackageInstallationPlugin.class.php#L123
- [ ] `Constant 'AUTOMATIC_NAME_PREFIX' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/plugin/CronjobPackageInstallationPlugin.class.php#L142
- [x] `Method 'getCompatibleVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/validation/PackageValidationArchive.class.php#L202
- [x] `Method 'isSupportedApiVersion' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/validation/PackageValidationArchive.class.php#L206
- [x] `Constant 'INCOMPATIBLE_API_VERSION' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/package/validation/PackageValidationArchive.class.php#L216
- [x] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/session/SessionHandler.class.php#L12
- [ ] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/database/DatabaseException.class.php#L113
- [x] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/importer/AbstractWatchedObjectImporter.class.php#L5
- [ ] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/importer/AbstractWatchedObjectImporter.class.php#L38
- [ ] `Class 'LoggedException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/exception/SystemException.class.php#L12
- [ ] `Class 'parent' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/exception/SystemException.class.php#L40
- [ ] `Class 'LoggedException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/exception/AJAXException.class.php#L15
- [ ] `Class 'IPrintableException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/exception/UserException.class.php#L13
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/application/ApplicationHandler.class.php#L138
- [x] `Class 'DownloadRankImageJob' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_migrate_rank_images.php#L7
- [x] `Class 'DownloadRankImageJob' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_migrate_rank_images.php#L24
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/exception/HTTPException.class.php#L5
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/util/exception/HTTPException.class.php#L28
- [ ] `Method 'getWCF' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/cache/builder/RoutingCacheBuilder.class.php#L137
- [ ] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/database/exception/DatabaseException.class.php#L13
- [ ] `Method 'setRemoveLinks' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeWoltlabMetacode.class.php#L50
- [ ] `Method 'setRemoveLinks' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeWoltlabMetacode.class.php#L56
- [x] `Method 'exceptionDisableGzip' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/email/Email.class.php#L702
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/PaypalCallbackAction.class.php#L6
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/PaypalCallbackAction.class.php#L37
- [ ] `Method 'markAsConfirmedByID' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/action/NotificationConfirmAction.class.php#L66
- [x] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L4
- [x] `Class 'DatabaseException' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L441
- [ ] `Method 'add' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/search/AbstractSearchIndexManager.class.php#L22
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/recaptcha/RecaptchaHandlerV2.class.php#L6
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/recaptcha/RecaptchaHandlerV2.class.php#L43
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/captcha/RecaptchaHandler.class.php#L5
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/captcha/RecaptchaHandler.class.php#L104
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L7
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L49
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L50
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L56
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L57
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L69
- [x] `Class 'LikeHandler' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/user/notification/event/TTestableLikeUserNotificationEvent.class.php#L72
- [x] `Method 'setObjectTitles' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/system/event/listener/ArticleLinkHtmlInputNodeProcessorListener.class.php#L55
- [ ] `Field 'category' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/page/TrophyListPage.class.php#L100
- [ ] `Field 'categoryID' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/page/TrophyListPage.class.php#L101
- [x] `Class 'MessageParser' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/custom/option/CustomOption.class.php#L6
- [x] `Class 'MessageParser' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/custom/option/CustomOption.class.php#L175
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/blacklist/entry/BlacklistEntryAction.class.php#L12
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/blacklist/entry/BlacklistEntryAction.class.php#L41
- [x] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/blacklist/status/BlacklistStatus.class.php#L9
- [ ] `Class 'HTTPRequest' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/data/blacklist/status/BlacklistStatus.class.php#L81
- [x] `Method 'getSupportedLegacyApiVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/DevtoolsProjectAddForm.class.php#L339
- [x] `Method 'getCompatibleVersions' is deprecated` https://github.com/WoltLab/WCF/blob/24b9a09a288b209ffca50fd070ecfafc63068256/wcfsetup/install/files/lib/acp/form/DevtoolsProjectEditForm.class.php#L259

(generated using a PhpStorm inspection)

**Comment by TimWolla** [comment]
>     * Class 'DownloadRankImageJob' is deprecated

These are deprecated, because they are only required for the 5.3 :point_right:  5.4 upgrade.

**Comment by Gravatronics** [comment]
> > ```
> > * Class 'DownloadRankImageJob' is deprecated
> > ```
> 
> These are deprecated, because they are only required for the 5.3 👉 5.4 upgrade.

May-be we should already create an issue for 5.5 to remove them then to not forget it?

**Comment by TimWolla** [comment]
> May-be we should already create an issue for 5.5 to remove them then to not forget it?

As they are intimately tied to the update script I expect them to be removed when the update scripts are removed, but an issue sure can't hurt.

**Comment by TimWolla** [comment]
>     * Class 'DatabaseException' is deprecated

(in MysqlSearchEngine)

The using method itself is deprecated, thus I'm checking this off.

**Comment by TimWolla** [comment]
>     * Class 'HTTPRequest' is deprecated
(in HTTPException)

HTTPException was just deprecated, it is intimately tied to HTTPRequest.

**Comment by TimWolla** [comment]
>     * Class 'HTTPRequest' is deprecated
(in RecaptchaHandlerV2)

RecaptchaHandlerV2 is deprecated, thus this can be ignored.

**Comment by Gravatronics** [comment]
See #4281
