### ISSUE TITLE
Search for purchased products should also accept the license number / serial

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3910]
To request the purchased products, you currently have to enter the credentials for your WoltLab account. The function cannot be used if the WoltLab account is linked to a third-party provider.

The license number+serial should be the prefered input in the UI, because it drives users away of saving their sensitive credentials.

**Comment by TimWolla** [comment]
The API was adjusted to take license information, what's missing is the phrasing changes for the UI.

**Comment by dtdesign** [comment]
> The API was adjusted to take license information, what's missing is the phrasing changes for the UI.

You could look into this issue which would be somewhat related: https://community.woltlab.com/thread/288308-zugangsdaten-eintragen-wird-jedes-mal-bei-erworbene-produkte-plugin-store-angeze/
