### ISSUE TITLE
Easier filtering for the user list

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3954]
Filtering users is quite tedious for common tasks such as banned users or those awaiting approval. Some kind of quick navigation (or tab?) should be included to ease these kind of day-to-day tasks.

**Comment by joshuaruesweg** [comment]
As a note: In the ACP we have already the Quick Search Actions, which are hidden within the user search form. Maybe it would be easier, to relocate this dropdown to the user list page.
