### ISSUE TITLE
Rich snippets for embedded content from the software itself

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3956]
Links that lead to other components of the software, for example, forum threads or articles, are currently detected and replaced with their plain title. This can be extended to detect if these links are "standalone" which means they are in their own line with nothing else next to them. Converting these links into rich embeds could provide some real value by showing more context, similar to the file bbcode in the Filebase.

**Update:** All apps now support bbcodes for embeds, but the visuals might still need some work.

- [x] Update visuals
- [ ] Make fallback output consistent
    - [ ] Missing permissions.
    - [ ] Missing object.
    - [ ] non-`text/html` output type.
    - [ ] `$parser->getRemoveLinks()` being `true` / `false`.

**Comment by TimWolla** [comment]
Somewhat related: https://community.woltlab.com/thread/288717-wo-kommt-der-bbcode-post-her/

**Comment by TimWolla** [comment]
Also possibly somewhat related: #4018.

`HtmlInputNodeProcessorListener` in Forum processes the `$eventObj->plainLinks` structure. The event listener runs twice:

1. in `wcf\system\message\QuickReplyManager->validateParameters` in `wbb\data\post\PostAction->validateQuickReply()`
2. in `wbb\data\post\PostAction->quickReply()`

The array is non-empty during the validation and empty during the actual relevant processing.

**Comment by dtdesign** [comment]
I can't wrap my head around that one, if this is the same instance, then the data is the same regardless. If there are separate instances, each has its own internal state? Your explanation is a bit too vague here.

**Comment by dtdesign** [comment]
The issue is bogus, because this isn't the same message being processed. Instead this was the length check for the double post merge-feature that constructed a new message on the fly using the rendered (!) HTML of the message.
