### ISSUE TITLE
Simplify phrases for notifications

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3958]
There have been partial attempts in the past to reduce the complexity of notification phrases. In particular the Core and all other pages need to be reviewed for phrases that have not been updated yet.

Guidelines:
* Remove links and highlight titles using `<strong>…</strong>`.
* Avoid deep access on variables, pass in precomputed values from the PHP class instead.
* Use the `{plural}` helper whenever possible.

**Comment by TimWolla** [comment]
> Use the `{phrase}` helper whenever possible.

Should this read `{plural}`?
