### ISSUE TITLE
Restrict the access to email addresses

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3963]
Email addresses are considered to be sensitive data and should not be exposed to every admin.

* [x] New group permission to restrict the access to email addresses.
* [x] Restrict the ability to export email addresses.
* [x] How should the email input in the admin panel be handled?
  Prevent changes and hide it? Show a short text instead that notifies of the lack of permissions? It might be wise to show a message instead of hiding it to prevent confusion since this option existed since, like, ever.

See https://community.woltlab.com/thread/285612-datenschutz-e-mail-adressen-im-adminbereich-f%C3%BCr-alle-ausblenden/
See https://community.woltlab.com/thread/282048-recht-e-mail-adressen-exportieren-explizit-erteilen-oder-nicht/

**Comment by TimWolla** [comment]
see also: https://github.com/WoltLab/WCF/blob/85176ea5c21f429576abbeded80a5f8667340842/com.woltlab.wcf/userGroupOption.xml#L231-L237

**Comment by TimWolla** [comment]
After discussing this: The existing `canEditMailAddress` permission is sufficient. The missing validation before export in UserBulkProcessing is a bug.
