### ISSUE TITLE
Reject option names that are not lower case

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3966]
Option names have always been intended to be written in lower case together with their upper case variant as a constant. The system should enforce lower case names to ensure a consistent behavior for options.

See https://community.woltlab.com/thread/285301-abfangen-von-falschen-option-werten-in-den-entwickler-werkzeugen/

**Comment by TimWolla** [comment]
#3988 adds the requested validation to developer tools. I have not added a validation to the PIP itself for compatibility reasons.
