### ISSUE TITLE
Contact form: Disable the administrator if there are other recipients

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3967]
The administrator cannot be disabled as a recipient until now with the intention of providing at least one valid recipient. However, this restriction also causes the administrator to be always available, even when there are other, potentially more suitable, recipients.

* [ ] Allow the administrator to be disabled.
* [ ] Force-enable the administrator on runtime if there are no other recipients.

See https://community.woltlab.com/thread/282808-kontaktformular-administrator-deaktivieren-k%C3%B6nnen/

**Comment by TimWolla** [comment]
>     * Force-enable the administrator on runtime if there are no other recipients.

Alternative suggestion: Maybe disable the contact form via a page handler if no recipients are available?

**Comment by dtdesign** [comment]
That is possible too, my suggestion simply mimiced the effective previous behavior. Dynamically disabling it is fine, although this check needs to be run in the page handler too to prevent the link from showing up in the first place.
