### ISSUE TITLE
Always install all officially supported languages

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3969]
Adding the officially supported languages later on is quite a painful process, especially now that we have the built-in support to reliably disable languages. Keeping all languages simplifies the migration to multilingual support (which happens surprisingly often) without any drawbacks.

See https://community.woltlab.com/thread/285841-verbesserung-der-sprachinstallation/

--------------

- [x] Remove selection during WCFSetup
- [x] Disallow deleting the stock languages.

**Comment by TimWolla** [comment]
#3986 always installs all languages during WCFSetup, but does not prevent deletion of any language. I assume that already improves the situation, because an explicit deletion is a more intentional process compared to simply not checking the language during installation.

**Comment by dtdesign** [comment]
We should not allow users to delete the two officially supported languages, similar to what we're already enforcing for Cloud instances. It is perfectly valid to disable languages, removing is not required and horribly backfires if the admin makes up their mind days later.
