### ISSUE TITLE
Include the signature in the GDPR export

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3977]
n/t

See https://community.woltlab.com/thread/287365-pers%C3%B6nliche-daten-exportieren-signatur/

**Comment by TimWolla** [comment]
According to git blame this is already the case since 3.0.15 at the very least. I also checking that the signature actually is being exported (i.e. that there is not a bug that prevents it from working).

**Comment by TimWolla** [comment]
Specifically it is there since this commit: https://github.com/WoltLab/WCF/commit/32028252528d59a5824955d81f2719bcd7cbd997#diff-323d6bc2a1be727d2ac2c65273c8787f6d99e535f0863f8b578a1ee6ac6ca894R41. I'm not sure why git blame did not get through to it.
