### ISSUE TITLE
Prefill the description of trophies when providing custom values

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3979]
In order to ease creating trophies with a consistent custom description the `description` field could be prefilled with the description of the selected trophy when `useCustomDescription` is checked.

As an example this could be useful for a monthly contest where the description includes the topic and month of the contest and is otherwise phrased identical: „{$username} won the <contest name contest> held in <month>, <year>“.

See https://community.woltlab.com/thread/287550-usertrophyadd-prefill-description-with-the-selected-trophy-s-description-when-us/

**Comment by joshuaruesweg** [comment]
With the existing implementation, it is not practical to implement this. This is because a large amount of data would have to be loaded and held.
