### ISSUE TITLE
Remove dotSeparated from messageHeaderMetaData

### ISSUE THREAD

**Issue by TitusKirch** [WoltLab/WCF#3984]
I would like to suggest removing the `dotSeparated` from the `messageHeaderMetaData` class. The reason for this is that the `contentHeaderMetaData` does not have this either and the difference looks a bit ugly.

contentHeaderMetaData
![image](https://user-images.githubusercontent.com/16943133/107696143-deecbc80-6cb1-11eb-873d-35fb7b6e02bc.png)

messageHeaderMetaData (current)
![image](https://user-images.githubusercontent.com/16943133/107696177-ead87e80-6cb1-11eb-924a-d28d76c1b725.png)

messageHeaderMetaData (suggest)
![image](https://user-images.githubusercontent.com/16943133/107696227-fcba2180-6cb1-11eb-9173-a39af4bf4507.png)

**Comment by BurntimeX** [comment]
By default, `messageHeaderMetaData` does not use icons, which is why the dot is necessary. Examples of use without icons:
https://github.com/WoltLab/WCF/blob/master/com.woltlab.wcf/templates/messageQuoteList.tpl#L18
https://github.com/WoltLab/WCF/blob/master/com.woltlab.wcf/templates/moderationComment.tpl#L16

**Comment by TitusKirch** [comment]
Okay, at this point I understand why dots are good.

If you don't want to change the current behavior, it would occur to me that you add a class `iconMetaData` or `messageHeaderIconMetaData` and only if this is not set, `dotSeparated` is included in `messageHeaderMetaData` or in the latter case you could include `messageHeaderMetaData` without `dotSeparated`.

Otherwise, if you want to change this, you could also include `dotSeparated` wherever you need it.

I could also provide a PR for this.

**Comment by BurntimeX** [comment]
Can you give me an example where messageHeaderMetaData is used in combination with icons (as seen in the image above)?

**Comment by TitusKirch** [comment]
I am not aware of any place in the standard scope where this looks like this.
Whereas I actually wanted to submit as a next step also a change regarding the appearance of these small messages (that are used here just also icons)

**Comment by dtdesign** [comment]
> Whereas I actually wanted to submit as a next step also a change regarding the appearance of these small messages (that are used here just also icons)

I'm sorry, but can you please rephrase this?

**Comment by TimWolla** [comment]
@TitusKirch I believe you might have missed the comment above :point_up:

**Comment by TitusKirch** [comment]
Sorry, I had exams the last few days, which is why I didn't have time to read this message.

> I'm sorry, but can you please rephrase this?

Of course:
After this change request, I wanted to submit another one. The plan from me was to add icons for each attribute in all the metadata in the message header (similar to what is done for the content metadata).

Of course I know this is a "very unnecessary" change request. It's just that my inner Monk was bothered by this, which is why I wanted to start with this.

**Comment by dtdesign** [comment]
There shouldn't be any icons at all, this location is meant to be a distraction-free collection of meta data. This is also reflected by the use of a slighty dimmed text color to reduce the visual impact.

These two types of meta data appear in a vastly different context with distinct purposes. For example, the content meta data is placed after the title which uses a much larger font. Try to squint your eyes when looking at the page and you'll notice that the larger font serves as a visual anchor. You can quickly focus on the title and then on the message, the meta data does not distract you from quickly jumping between content.

Your suggested change breaks backwards compatibility and there really shouldn't be any icons whatsoever, they were left out intentionally. Is there anything else I may have overlooked?

**Comment by TitusKirch** [comment]
All right, thanks for the detailed answer. I will then simply implement this as an extension (for those who want it).
