### ISSUE TITLE
Nested HtmlOutputProcessors with embedded objects modify the internal state

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4018]
This is kind of an obscure bug that just recently surfaced in combination with the bbcodes for threads and posts. It was observed that multiple of such bbcodes within one message will cause only the first one to be rendered. Actually, depending on the circumstances, additional bbcodes could be rendered, if they are embedded objects of the first referenced object.

The issue unfolds like this:
1. A message with support for embedded objects is being rendered.
2. `HtmlOutputProcessor::setContext()` sets the active message of `MessageEmbeddedObjectManager`.
3. During processing, a bbcode is encounted that makes use of `HtmlOutputProcessor` itself (here: Render an excerpt of a post).
4. The same logic as in step 2 happens, setting the internal state of the `MessageEmbeddedObjectManager` to the object in step 3.
5. Once the embedded message is rendered, the control flow switches back to the original message.
6. The next bbcode in this message attempts to read from the `MessageEmbeddedObjectManager`, but the active message points to the embedded message in step 3 now.
7. The bbcode is unable to render the data and its fallback logic kicks in.

**Comment by dtdesign** [comment]
A possible solution (?) would be to store the previous state of the `MessageEmbeddedObjectManager`. At the end of `HtmlOutputProcessor::getHtml()` we could place a call to restore the active message before the current message was processed.

The state needs to be tracked as a simple stack in  `MessageEmbeddedObjectManager` where any new call to `setActiveMessage` pushes the current values to the stack and `MessageEmbeddedObjectManager::reset()` would pop the last values from the stack. It requires the least amount of changes (especially to fix this in earlier versions), does not leak the state to the outside and fixes the issue without requiring any changes by 3rd party developers.

**Comment by TimWolla** [comment]
see also: https://github.com/WoltLab/WCF/issues/3956#issuecomment-784906242. This issue might or might not be related and require a similar fix.

**Comment by TimWolla** [comment]
For some reason the merge of #4021 did not close this issue. Doing it manually now.
