### ISSUE TITLE
Style error in the post bbcode

### ISSUE THREAD

**Issue by TitusKirch** [WoltLab/WCF#4047]
I guess this is not supposed to be.

![image](https://user-images.githubusercontent.com/16943133/109843447-58d9eb00-7c4b-11eb-844b-70a0e67f3744.png)

Found here
https://community.woltlab.com/thread/288879-testpost-please-ignore/

**Comment by TimWolla** [comment]
Hey, the title of that topic says that you should ignore it!

In all seriousness: The thread should've went into the Private Test Forum and the exact purpose of the thread was having something to link to in the internal issue (WoltLab/com.woltlab.wbb#441).

Thus closing this one as it is a duplicate, thanks!
