### ISSUE TITLE
Optional input field for "internal" domains

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4049]
The detection for internal urls uses nothing but the domains set up for the applications. This has the unwanted side effect that some domains might be detected as external, for example, the site runs on `community.example.com` but the homepage uses `www.example.com`.

This can be solved by an extra input field that allows the administrator to supply additional domains that are treated as internal.

**Comment by TimWolla** [comment]
Somewhat related: https://github.com/WoltLab/WCF/blob/edca1afa18a0d21d428c3712bcf2b4b7b240d621/com.woltlab.wcf/option.xml#L1110-L1113

**Comment by TimWolla** [comment]
> This can be solved by an extra input field that allows the administrator to supply additional domains that are treated as internal.

Where should this apply? For links in UGC only? Everywhere where `isInternalURL()` is being used?

**Comment by dtdesign** [comment]
I wouldn't like to mix this with the image proxy, that is a different logic.

Modifying `isInternalURL()` is sufficient, this method is well-known and established, providing a single source of truth.
