### ISSUE TITLE
Consistently use (User)Option::getTitle()

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4107]
The `getTitle()` method was added in a41ce9459e97d83a620d5c3743907f4850f35eb5, but was not consistently used. It's missing from `optionFieldList.tpl` for starters:

https://github.com/WoltLab/WCF/blob/c29b75e0e43c5680f7d4182325b5958902997661/com.woltlab.wcf/templates/optionFieldList.tpl#L10

All occurrences can probably be found by searching for `wcf.user.option.`.

**Comment by Sir-Will** [comment]
With this change it is no longer possible to use HTML in the title. Is that intended?

**Comment by TimWolla** [comment]
> Is that intended?

Yes.

**Comment by BurntimeX** [comment]
I would not change this until we convert the forms to FormBuilder forms at some point.
