### ISSUE TITLE
5.4: Database-PIP not working with DevTools for non-core-projects

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4138]
For non-Core-projects (or: for every package except the core) the DevTools are going to search wrong. The Core expects the files to be at `./acp/database/*.php`, but the files are located at `./files(_abbreviation)/acp/database/*.php` in general.

**Comment by Gravatronics** [comment]
We are also using the database PIP for non-Core packages. Please provide more information like the exact path of the database file and the instruction in `package.xml`.

Also make sure when manually executing the PIP to first sync files.

**Comment by Gravatronics** [comment]
@mutec Do you have any feedback on this issue?

**Comment by mutec** [comment]
One class didn't sync for strange reasons; it's working now.
Would it be possible to sync the database-directory kind of automatically*? For developing I want to sync the database before syncing the files sometimes.

* Like searching in the project's directories instead of the final installation.
