### ISSUE TITLE
Concept for the upgrade 5.3 -> 5.4

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4141]
Once available, the upgrade should be as simple as possible, without requiring users to manually edit anything. Ideally we run some check for the requirements and make sure that all outstanding updates are installed before running the upgrade.

Potential behavior:
1.  Message on the package list informs of the new version, with a link or button to upgrade.
2. Clicking the link should run a check for the system requirements.
3. If the check was successful, check for outstanding updates.
4. If no outstanding updates were found, set a session variable to override the package servers for 5.4.
5. Run a "check for updates", which will redirect the user.

Outstanding questions:
* Do we need to manually handle connection issues preventing communications with the package server?
* Do we require adjustments for the Cloud instances?

/cc @TimWolla

**Comment by TimWolla** [comment]
> set a session variable

I don't like the use of a session variable here, because it is fragile when concurrent requests happen for whatever reason. Consider that the regular "fetch package lists" cronjob might run while the administrator is in the process of upgrading, possibly resulting in an inconsistent package list.

I would replace this by a regular option / registry item, storing the timestamp of the opt-in, automatically resetting after 1 day and ensuring that the package list cache is properly cleared upon the reset.

The remainder of your suggested process looks good to me.

> Do we need to manually handle connection issues preventing communications with the package server?

I don't understand this question.

> Do we require adjustments for the Cloud instances?

I don't think so.

**Comment by dtdesign** [comment]
> […] I would replace this by a regular option / registry item, storing the timestamp of the opt-in, automatically resetting after 1 day and ensuring that the package list cache is properly cleared upon the reset.

Good point, the `Registry` could be a viable option - it is persistent and somewhat thread-safe.

> > Do we need to manually handle connection issues preventing communications with the package server?
> 
> I don't understand this question.

The "Search for Updates" silently ignores failing package servers. This is a strange behavior by itself, but considering the reliability of some 3rd party servers certainly not the worst decision. It could cause an unexpected behavior when the software runs on one of these dreaded hosts with a bad firewall configuration, effectively reporting that there are no outstanding updates.

Maybe we could just change the behavior to complain about unreachable official servers, while still silently ignoring failing 3rd party servers?

**Comment by TimWolla** [comment]
> The "Search for Updates" silently ignores failing package servers.

I would probably "compile" the next available Suite version into the previous one, once it is available. Then button (or whatever) would show up somewhere once the appropriate patch update has been applied. On the page explaining what happens we could add a quick smoke test whether the update server generally is available.

**Comment by mutec** [comment]
This is not going to work if one or more 3rd-party-servers are required. Is the feature disabled for those cases or will it just confuse the admins?

**Comment by dtdesign** [comment]
> This is not going to work if one or more 3rd-party-servers are required. Is the feature disabled for those cases or will it just confuse the admins?

There has been no changes to the way that third party servers work, the process remains the same as before. Please feel free to point out any issues that prevent the previous behavior, just in case we unintentional changed something in that direction.

**Comment by mutec** [comment]
I'd rather suggest some kind of server-index every developer provides that keeps information about available servers and which WSC-versions they are meant for. Using something like that would improve the usability for every case - and it would be a very consistent handling during the upgrade-process.
I'd prepare a PR-Draft if that could be an idea for the future, but I don't really like working hours on that before I know it would get a chance. ;)

**Comment by dtdesign** [comment]
Thinking about this, wouldn't it be sufficient to report the requested version via a HTTP header? For example, we could send something like `woltlab-major-version: 5.4` to indicate that the client would like to request packages for 5.4. This could align with the setting implemented in #4160.

**Comment by TimWolla** [comment]
>  For example, we could send something like `woltlab-major-version: 5.4` to indicate that the client would like to request packages for 5.4.

I added that to #4160 under a slightly different name: https://github.com/WoltLab/WCF/pull/4160/commits/dc259a5044bed7ecbd52afa7234b027b34557750
