### ISSUE TITLE
Event/Possibility to modify PIP's default filename dynamically (cmp. database-PIP)

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4168]
see issue title

**Comment by dtdesign** [comment]
What is the motivation behind this request, what problem are you trying to solve that you can't otherwise?

**Comment by mutec** [comment]
Maybe the database PIP isn't the only PIP that might use a custom handling in the future and no 3rdparty-developer is able to do so if it's restricted and hard-coded.

**Comment by dtdesign** [comment]
I find it difficult to make such changes in advance without knowing what the actual requirements are. I would rather make changes when the need for those arise, enabling us to take a closer look at what actually needs to be done. This explicitly involves finding different approaches that might turn out to be the better solution, especially for something that sensitive like the package system.
