### ISSUE TITLE
Provide `elInnerSuccess(element, message, isHtml)`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4170]
I'd be happy if there was a function for handling `innerSuccess`-containers like `innerError`.

**Comment by TimWolla** [comment]
Note: The `el*` helpers are considered soft-deprecated with WoltLab Suite 5.4. They intentionally didn't receive TypeScript types.

The replacement for `elInnerError` is [`DomUtil#innerError`](https://github.com/WoltLab/WCF/blob/f632ee9f9d226690b3c579d1671e4c7ea359f9d0/ts/WoltLabSuite/Core/Dom/Util.ts#L433-L436)

**Comment by TimWolla** [comment]
I just scanned all our packages for `innerSuccess`, but I couldn't find a single user of that class. `innerSuccess` only ever appears in the SCSS of com.woltlab.wcf. I also can't think of a use case where using `innerSuccess` would result in a good user experience. Consistency in behavior is important: Where do you plan to use an `innerSuccess` element? Maybe there's a better solution.

**Comment by mutec** [comment]
I'm just implementing a kind of status-checking form field.
This form field may return (live while tying) whether the search string is valid and available or the string cannot be used for the further form. You might compare it to the new-password-form validating the strength of the password and returning sommething like "You password is bad." or "Your password matches the guidelines and is (very) secure matching a score of xyz." .
It's not dramatic, for the moment I'm using `elInnerError` and changing the classes. I just wondered why there is a CSS-implementation but none for JavaScript.

**Comment by TimWolla** [comment]
> This form field may return (live while tying) whether the search string is valid and available or the string cannot be used for the further form.

Doesn't the absence of an error imply success?

**Comment by mutec** [comment]
Not in that case. It's more like it's not checked or has to be checked later.

**Comment by dtdesign** [comment]
I have implemented `WoltLabSuite/Core/Dom/Util.innerSuccess()`, the method signature is equal to the `innerError()` implementation. There will be no legacy `elInnerSuccess()`, because the `el*` helper functions are deprecated.

**Comment by mutec** [comment]
No problem, I'll change it to the new API anyway. :)
