### ISSUE TITLE
MySQL error during a test installation

### ISSUE THREAD

**Issue by deraiser** [WoltLab/WCF#4171]
When installing WSC 5.4 locally, the installation terminates with the following error message:

> Could not execute statement 'CREATE TABLE `wcf1_user_multifactor_backup` ( `setupID` int(10) NOT NULL,`identifier` varchar(255) NOT NULL,`code` varchar(255) NOT NULL,`createTime` int(10) NOT NULL,`useTime` int(10) DEFAULT NULL , UNIQUE KEY (`setupID`,`identifier`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'

If I set the `identifier` `varchar` value in the `install.sql` to `191`, then this installation continues.
In `wcf1_user_multifactor_email` with `code` and `wcf1_user_multifactor_totp` with `deviceID` is the same.

**Comment by TimWolla** [comment]
> If I set the `identifier` `varchar` value in the `install.sql` to `191`, then this installation continues.

Your MySQL has `innodb_large_prefix` disabled. The default is `On`, the configuration option is deprecated in MySQL 5.7 and removed in MySQL 8.0. You really should fix your MySQL configuration.

Nonetheless I'll look into either changing the column's type or length.
