### ISSUE TITLE
First custom smiley category not being preloaded

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#4172]
When using at least 2 custom smiley categories and removing all smileys from the default category it will not preload the category but instead load it via ajax after the page is loaded.
This can cause the ajax status to popup in the middle of the screen.

![](https://i.imgur.com/WHKNUjW.png)

**Comment by Gravatronics** [comment]
See https://github.com/WoltLab/WCF/commit/edeb3e25323f43e4415cf4c47d282d4addd83b0a
