### ISSUE TITLE
Detection of nested tables broken in HtmlOutputNodeTable

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4175]
https://github.com/WoltLab/WCF/blame/962abd3aa503ead54638a10ea390fb76eb41c513/wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeTable.class.php#L29-L33

Should be `continue 2`?

**Comment by dtdesign** [comment]
Yes, it should be `continue 2;`.
