### ISSUE TITLE
Fix mail design in macOS Mail using dark mode

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4188]

**Comment by pehbeh** [comment]
Maybe not only on macOS? Here a screenshot from iOS (14.5.1). Maybe it is the same problem:

![EB3D3EC7-F016-4BAE-9161-EC77786E3AEA](https://user-images.githubusercontent.com/1836347/117196940-73fdde00-ade7-11eb-989a-473084d225df.png)
