### ISSUE TITLE
Add maximum length (user group) option for comments

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4195]

**Comment by dtdesign** [comment]
Does anybody remember what the rationale was for this? What use cases are we trying to address here?

**Comment by dtdesign** [comment]
After some digging I come to the conclusion that it makes sense to use at least a general limit and see if special cases arise. Until then one userGroupOption to limit to something sane (e.g. 100k) should be sufficient.

**Comment by joshuaruesweg** [comment]
This should not be adjustable for certain comment object types, correct?

**Comment by dtdesign** [comment]
What kind of exceptions do you have in mind?
