### ISSUE TITLE
Code box header should not move/scroll to box end

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4196]
The header of a code box stays attached to the visual top of the currently visible code box if the page is scrolled. If the code box, however, is hardly in view anymore, this header can start overlapping with the code box footer showing the button to collapse it. At a fixed distance from the code box bottom, the header should not move anymore.

**Comment by dtdesign** [comment]
`position: sticky` will always be contained within the boundaries of its parent and does not know about the concept of an offset from bottom. Therefore the header will be allowed to scroll until it reaches the very bottom of the container, eventually being placed on top of the footer as it is intended.

This is not a bug.
