### ISSUE TITLE
Debug mode tries loading qr-generator.js while there's only qr-generator.min.js

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4197]
see title

/cc @xopez

**Comment by SoftCreatR** [comment]
You mean `qr-creator.js` :)

**Comment by TimWolla** [comment]
This doesn't make sense to me.

a) It works for me.
b) The require.config explicitly references the `.min` file: https://github.com/WoltLab/WCF/blob/2a7aea52f123df4ac79885e52f62a8da1f3b0dad/wcfsetup/install/files/js/require.config.js#L10

**Comment by mutec** [comment]
nvm I thought it couldn't be loaded before. I checked it again and it's working…
Sorry for the false "alert".
