### ISSUE TITLE
CLI `exit` not closing properly

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#4220]
When using the CLI `exit` command it terminates the script without properly closing the `ConsoleReader` resulting in the shell not showing the currently typed command until `reset` is being used.

https://askubuntu.com/questions/171449/shell-does-not-show-typed-in-commands-reset-works-but-what-happened

**Comment by TimWolla** [comment]
I'm unable to reproduce this and never experienced this issue when using cli.php myself.

**Comment by Sir-Will** [comment]
It seems to be fixed. I didn't notice this issue in 5.5 anymore.
