### ISSUE TITLE
Option to remove all formatting does not work

### ISSUE THREAD

**Issue by JuliusPC** [WoltLab/WCF#4276]
I am using WoltLab Suite Core 5.3.7 with WoltLab Suite Forum 5.3.6. When I disable this option...

![grafik](https://user-images.githubusercontent.com/15018932/121385416-61784680-c949-11eb-8c22-a7659748f10a.png)

... and I write some coloured text with different font sizes in MS Word and copy-n-paste it in the editor, it looks like this:

![grafik](https://user-images.githubusercontent.com/15018932/121385852-c5027400-c949-11eb-945d-b4abb8bbc65b.png)

The heading is stripped but colors and font sizes are not (as I would expect in case of plain text).

---

Just for reference: If above option is enabled, the text looks like this:

![grafik](https://user-images.githubusercontent.com/15018932/121387171-c4b6a880-c94a-11eb-8e0b-2a29cb1cd982.png)

**Comment by JuliusPC** [comment]
@dtdesign I applied the fix to my installation (it would be overwritten by an update, so no problem, I guess) and it does not work (the behaviour hasn't changed). I also cleared the caches.

Do I miss something?

**Comment by dtdesign** [comment]
> Do I miss something?

It only works with the enabled debug mode, not with the production build. The minified JavaScript hasn't been rebuild yet.

**Comment by JuliusPC** [comment]
Thanks!
