### ISSUE TITLE
Usage of deprecated PHP

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4281]
- `Class 'HTTPUnauthorizedException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L10
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L16
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L119
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L161
- `Class 'HTTPUnauthorizedException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L183
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/acp/form/DataImportForm.class.php#L7
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/acp/form/DataImportForm.class.php#L242
- `Class 'IPrintableException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/WCF.class.php#L23
- `Class 'IPrintableException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/WCF.class.php#L292
- `Field 'rankImage' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/acp/form/UserRankAddForm.class.php#L271
- `Field 'rankImage' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/acp/form/UserRankAddForm.class.php#L306
- `Field 'rankImage' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/acp/form/UserRankEditForm.class.php#L116
- `Class 'LikeHandler' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/like/LikeAction.class.php#L12
- `Class 'LikeHandler' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/like/LikeAction.class.php#L173
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/user/avatar/UserAvatarAction.class.php#L18
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/user/avatar/UserAvatarAction.class.php#L110
- `Class 'MessageParser' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/custom/option/CustomOption.class.php#L8
- `Class 'MessageParser' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/custom/option/CustomOption.class.php#L208
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/package/PackageAction.class.php#L11
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/data/package/PackageAction.class.php#L106
- `Field 'category' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/page/TrophyListPage.class.php#L116
- `Field 'categoryID' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/page/TrophyListPage.class.php#L117
- `Method 'getSchema' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/util/XML.class.php#L112
- `Method 'load' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/CLIWCF.class.php#L263
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/cli/command/ImportCLICommand.class.php#L8
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/cli/command/ImportCLICommand.class.php#L250
- `Method 'setRemoveLinks' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeWoltlabMetacode.class.php#L55
- `Method 'setRemoveLinks' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeWoltlabMetacode.class.php#L61
- `Method 'paintTransparentImage' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/image/adapter/ImagickImageAdapter.class.php#L342
- `Method 'add' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/search/AbstractSearchIndexManager.class.php#L35
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L5
- `Field 'ftMinWordLen' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L463
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L470
- `Field 'ftMinWordLen' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L475
- `Field 'ftMinWordLen' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php#L478
- `Method 'deleteLegacyThumbnails' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/worker/UserRebuildDataWorker.class.php#L276
- `Class 'HTTPUnauthorizedException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L10
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L16
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L268
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L277
- `Class 'HTTPUnauthorizedException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageInstallationScheduler.class.php#L290
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateUnauthorizedException.class.php#L8
- `Class 'HTTPRequest' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/package/PackageUpdateUnauthorizedException.class.php#L46
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/database/DatabaseException.class.php#L118
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/database/exception/DatabaseException.class.php#L14
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/importer/AbstractWatchedObjectImporter.class.php#L7
- `Class 'DatabaseException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/importer/AbstractWatchedObjectImporter.class.php#L44
- `Class 'LoggedException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/exception/AJAXException.class.php#L17
- `Class 'IPrintableException' is deprecated`
https://github.com/WoltLab/WCF/blob/25e1c4184e7048313f040499bc8e413ed6d61b9e/wcfsetup/install/files/lib/system/exception/UserException.class.php#L15

**Comment by Gravatronics** [comment]
I marked the Gravatar-related points as done as we have a dedicated issue to remove Gravatar support later (#3894). I only kept the warnings about `HTTPRequest` in the Gravatar-related classes unchecked for now.

**Comment by Gravatronics** [comment]
`ApplicationHandler::getWCF()` is no longer deprecated, see c2b4349ce48025f49bb6786c232eb28d1c691358.

**Comment by Gravatronics** [comment]
As editing this long list takes quite a bit of time for GitHub to process, I deleted all checked items.

**Comment by Gravatronics** [comment]
Every multi-domain setup related issue has been removed as it is tracked via #4295.

**Comment by Gravatronics** [comment]
Every deprecation related to ACPSession DBOs has been removed as they are tracked via #4302.

**Comment by Gravatronics** [comment]
Every deprecation related to API versions/package compatibility has been removed as they are tracked via #4304.

**Comment by Gravatronics** [comment]
Every deprecation related to `PasswordUtil` has been removed as they are tracked via #4314.

**Comment by Gravatronics** [comment]
Every deprecation warning in `HTTPRequest.class.php` was removed because `HTTPRequest` itself is deprecated.

**Comment by Gravatronics** [comment]
`Callback` deprecations are tracked in #4331.

**Comment by TimWolla** [comment]
HTTPRequest in Paypal is in #4351.
HTTPRequest for Twitter is in #4352.
