### ISSUE TITLE
`HttpFactory::`* return `Client`  but is typed as `ClientInterface`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4337]
Just for my information maybe, but is there a reason, why e.g. `HttpFactory::makeClient()` returns `new Client($options)` by fact but the function is typed as `ClientInterface`?
Why don't we use `public static function makeClient(array $options = []): Client` directly since there might be some properties or functions in the future which might not be in `ClientInterface`* and it also implements `\Psr\Http\Client\ClientInterface` (which is not shown up within the IDE as a reason of using `ClientInterface`)?

* I know, the chance for that is barely zero.

**Comment by TimWolla** [comment]
Putting a concrete class into the return type is like pouring concrete into your code. It completely takes away your freedom to switch out the underlying implementation if the need arises and OO best practices “say no”. You should always put the most general interface that does everything you need.

> and it also implements `\Psr\Http\Client\ClientInterface` (which is not shown up within the IDE as a reason of using `ClientInterface`)?

This however is unintended indeed. Guzzle 6 as shipped in 5.3 when the return type (at that time as a PHPDoc tag) was initially added did not support PSR-18. This return type was taken as-is in 5.4.

Can you check whether the following change causes your IDE to detect both the `send()` (Guzzle) as well as the `sendRequest()` (PSR-18) methods? See: https://wiki.php.net/rfc/pure-intersection-types

```diff
diff --git i/wcfsetup/install/files/lib/system/io/HttpFactory.class.php w/wcfsetup/install/files/lib/system/io/HttpFactory.class.php
index 8fe4123bc5..25fd5f56e2 100644
--- i/wcfsetup/install/files/lib/system/io/HttpFactory.class.php
+++ w/wcfsetup/install/files/lib/system/io/HttpFactory.class.php
@@ -77,6 +77,7 @@ public static function makeClientWithTimeout(float $timeout): ClientInterface
      * specifically removed by passing appropriate options.
      *
      * @see Client
+     * @return Psr\Http\Client\ClientInterface & ClientInterface
      */
     public static function makeClient(array $options = []): ClientInterface
     {
```

**Comment by mutec** [comment]
@TimWolla the change looks fine:
![image](https://user-images.githubusercontent.com/1749344/123086716-0d2e9580-d424-11eb-838e-0540faabff25.png)

Just to be sure: I added it to all three functions. :)

**Comment by TimWolla** [comment]
> the change looks fine:

Perfect, thanks. Some piece of unsolicited advice based on your screenshot: I recommend using a getter function for the HTTP client instead of a property. This allows you to more easily lazily initialize the HTTP client.

See: https://github.com/WoltLab/WCF/blob/27a18f744bd73189173b348843199e99bdea04b5/wcfsetup/install/files/lib/action/ImageProxyAction.class.php#L61-L77

> Just to be sure: I added it to all three functions. :)

Thanks for the reminder. I probably would have forgotten otherwise. After making the commit I also noticed that the return type was not 100% correct, because the leading backslash was missing for the PSR interface. Apparently your IDE didn't care (or you fixed it yourself?). Anyway, there's  a follow up commit for that: 006d83b9c455127714663506df85e795897fc795

**Comment by mutec** [comment]
@TimWolla the screenshot was taken inside the getter-method. I just didn't use `self::$httpClient` since it's in a Singleton. But thanks for the advice anyway. :)

Ah sorry, I totally forgot the missing Slash when answering. I fixed it over here before testing.

**Comment by TimWolla** [comment]
> @TimWolla the screenshot was taken inside the getter-method. I just didn't use `self::$httpClient` since it's in a Singleton. But thanks for the advice anyway. :)

Then at the least I recommend calling the property `httpClient` (or just `client`), because `guzzle` is overly specific. Similar to how you type hint on some interface, instead of a specific class.
