### ISSUE TITLE
Remove obsolete avatar size-related code

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4338]
- `UserAvatarEditor::deleteLegacyThumbnails()`
- `UserAvatar::$avatarThumbnailSizes`
- `UserAvatar::$maxThumbnailSize`
- `UserAvatar::MIN_AVATAR_SIZE`

**Comment by TimWolla** [comment]
When this is removed it should be somehow ensured that all the legacy sizes are gone from the file system.

**Comment by TimWolla** [comment]
Resolved with b9701e46d84d69ebf60a216f9de8767c3838ffaf.
