### ISSUE TITLE
Enable UTF-8 support in StyleCompiler

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4339]
UTF-8 support for the SCSS compiler is currently disabled due to a historically abysmal performance:

https://github.com/WoltLab/WCF/blob/a402ccfa662057ef04601d0009b6d145ba7cd3fd/wcfsetup/install/files/lib/system/style/StyleCompiler.class.php#L79-L81

However as of scssphp 1.5 changing the encoding will be deprecated, with UTF-8 being the only option going forward (#4274).

I just tested commenting out the line setting the encoding with the current scssphp version and could not measure any difference. Both ISO-8859-1 as well as UTF-8 required roughly 1 second total to load the dashboard with the style sheet not yet existing.

It should be verified whether others can confirm that there's no measurable difference or whether I did anything wrong.

**Comment by Gravatronics** [comment]
My non-scientific comparison by compiling the standard style five times each:

| | With ISO-Line | Without ISO-Line |
| --------- | -------- | --------- |
| Frontend | 1.8857 s | 2.2267 s |
| ACP         | 1.3779 s | 1.5589 s |

**Comment by dtdesign** [comment]
I can't measure any significant runtime variation, all differences fall in between +/- 5% and as such are within the margin of error.

Tested in PHP 8.0.7 @ i7-7820HQ
