### ISSUE TITLE
Values of `MultipleSelectionFormField` not available in `*FormDataProcessor`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4347]
Values for `MultipleSelectionFormField`-fields don't show up when `*FormProcessor`s are executed, so it's impossible to work with those  parameters.
When dumping the sent parameters within the `DatabaseObjectAction`-class, I see those values at top level of the parameters-array.

Used piece of code:
```PHP
$this->form->getDataHandler()->addProcessor(new CustomFormDataProcessor('dataSplit', function (IFormDocument $document, array $parameters) {
	wcfDebug($parameters);
	return $parameters;
}
```

Same for `LabelFormField`

**Comment by Gravatronics** [comment]
Make sure to attach the data processor after building the form.

**Comment by mutec** [comment]
@Gravatronics thanks. :) I always thought it's placed within `createForm()` after appending the fields.
I just checked it against the docs and didn't find a hint: https://docs.woltlab.com/5.4/php/api/form_builder/validation_data/#customformfielddataprocessor
Maybe we should issue that as part of https://github.com/WoltLab/docs.woltlab.com/pull/188 and display a not over there.

**Comment by Gravatronics** [comment]
I already added a note this morning: https://github.com/WoltLab/docs.woltlab.com/commit/43cb6c1bd3ff9ae90ee5c05217b26ffcd624cf99.

**Comment by mutec** [comment]
Ah I didn't check the next version's branch. :D
