### ISSUE TITLE
Explicitly consider implicit import dependencies

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4379]
Importing conversations, for example, also requires the import of users. Hence, if conversations are selected for import, users should be auto-selected or conversations should only be selectable if users are selected.

See #3804

**Comment by BurntimeX** [comment]
The dependency of the conversation import on the user import cannot be mapped technically with the current system.

This can only be change with a comprehensive overhaul of the import function, which is planned for the long term.
