### ISSUE TITLE
Discard missing style cover photos

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4409]
Some installations appear to have missing cover photo files, despite `wcfN_style.coverPhotoExtension` containing a value. This causes `update_com.woltlab.wcf_5.4_styleCoverPhoto.php` to fail the upgrade, because it attempts to read a file that does not exist.

The script should check for the file existence and if it is not present, discard the value of `coverPhotoExtension` in the database and continue with the next style.

**Comment by TimWolla** [comment]
Resolved with #4412
