### ISSUE TITLE
Implicit `SameSite=Lax` breaks running in an iframe

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4428]
A missing `SameSite` attribute was previously implicitly evaluated as `None`, but somewhat recently this was changed into `Lax`. This breaks iframes by rejecting cookies set by them, because these do not originate from a direct action taken by the user.

The only solution is to set it to `SameSite=None` which permits the cookie, but this does require the `Secure` attribute to be set, otherwise the cookie is blocked again.

Earlier issue: #2548

**Comment by StevenLeonKara** [comment]
in witch file i need to set it to SameSite=None with the secure line

**Comment by TimWolla** [comment]
Note: We also set an explicit `SameSite=strict` for the XSRF-Token in 5.4: https://github.com/WoltLab/WCF/blob/a7c25bceed7bc6b02cbe8458381218e0eff47c63/wcfsetup/install/files/lib/system/session/SessionHandler.class.php#L496.
