### ISSUE TITLE
Setup implicitly discard cookies for plain HTTP connections

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4499]
f4cc22969df12701101a1ce4c7b35af4791ee43c fixed the issue described in #4428, but this will cause the setup to also send cookies using `SameSite=none`:
https://github.com/WoltLab/WCF/blob/54ca27975384690ffa108098e23a308f8f25db04/wcfsetup/install/files/lib/system/WCFSetup.class.php#L39

Unfortunately, this breaks the setup when attempting to install the software using a non TLS connection, because browsers will discard `Set-Cookie` containing `SameSite=none` but without `Secure`.

I thought about adding a check against `\PACKAGE_ID` in these places, but I think it is wrong to set `\HTTP_SEND_X_FRAME_OPTIONS` to `0` during the setup. Nobody is going to install the software in an iframe and the default value for the option is `1` anyway.

I think that the correct fix is to set this option to `1` in the setup, but I hesitate to make the change without asking for other opinions first. The option was introduced in b23a245aa8853fcb5035dd1330a5bc2bbcbf77e1 (˜8 years ago).

**Comment by TimWolla** [comment]
> I think that the correct fix is to set this option to `1` in the setup,

I agree.
