### ISSUE TITLE
Delegate header list parsing to \GuzzleHttp\Psr7\Header::normalize()

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4534]
- [x] https://github.com/WoltLab/WCF/blob/0c0111e9466e951d867f43869f040ea4aa27c738/wcfsetup/install/files/lib/system/message/unfurl/UnfurlResponse.class.php#L168 (This does not currently handle commas at all).
- [x] https://github.com/WoltLab/WCF/blob/0c0111e9466e951d867f43869f040ea4aa27c738/wcfsetup/install/files/lib/system/request/RequestHandler.class.php#L113 (this method probably becomes obsolete)
- [x] https://github.com/WoltLab/WCF/blob/5b5aa3c0e912489127caeb990950425983e232e3/wcfsetup/install/files/lib/util/ImageUtil.class.php#L207

**Comment by TimWolla** [comment]
Apparently `Header::normalize()` does not correctly handle quoted commas. This would be an upstream issue that needs to be fixed first.

**Comment by TimWolla** [comment]
> Apparently `Header::normalize()` does not correctly handle quoted commas. This would be an upstream issue that needs to be fixed first.

I was incorrect there, because I misread that regular expression. Nonetheless there's a bug in there:

https://github.com/guzzle/psr7/pull/447

**Comment by GrahamCampbell** [comment]
BTW, what version of the guzzle psr7 library are you using. Your PR is targetting 2.x, only.

**Comment by GrahamCampbell** [comment]
1.x series is not really accepting bug fixes anymore, just as a heads up.

**Comment by TimWolla** [comment]
re UnfurlResponse: That doesn't make sense. `Content-Type` is not defined to be a list.
