### ISSUE TITLE
Remove the option `attachment_retain_dimensions`

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4542]
The option `attachment_retain_dimensions` ("Retain Thumbnail Aspect Ratio") controls the behavior for thumbnails when the  source image exceeds the width and/or height restrictions. Disabling it will cause the image to be scaled to match either the width or height (whichever is relatively closer). Since the image will then exceed either the width or height, the thumbnail will be cropped from the center of the image.

This yields barely useful thumbnails when the image is tall or otherwise of an odd dimension, for example extremely wide. This option primarily exists for historical reasons and generally produces bad results when disabled. Even worse this can horribly backfire when the option is disable and the attachments are rebuilt (e.g. after an upgrade/migration), because "fixing" the bad previews requires all of them to be rebuilt again.

**Comment by TimWolla** [comment]
FWIW the current default of this option is “disabled“:

https://github.com/WoltLab/WCF/blob/d72145623fce5a627cf3aaa13cd5a5c403b58689/com.woltlab.wcf/option.xml#L953-L957
