### ISSUE TITLE
Recover "lost" tmpHashes for attachments

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4579]
Every now and then we receive reports of attachments that appear in the editor, but are not present in the final message. This is caused by the `tmpHash` being lost for various reasons, for example, the editor content being discarded after reloading the page and pasting from a word processor. This will cause the attachment to still exist, but having no object id assigned and the `tmpHash` still exists in the database.

We can try to mitigate this issue to some extent by gracefully recovering such "lost" attachments by taking advantage of the `tmpHash` itself. Its value is intended to be randomly generated to prevent collisions, but the only formal requirement is that it is a string with a length of 40.

A "new" `tmpHash` could be used if the user is logged in. Since the generation of the `tmpHash` is in the domain of the callee, this change should be introduced in the forum first to serve as a guinea pig in order to verify that it works as intended, also possible edge cases should surface quickly.

The following relevant data is known for attachments with a `tmpHash`:
* `objectTypeID` (maps to something like `com.woltlab.wbb.post`)
* `userID`

This means that in conjunction with an arbitrary identifier we can reliable associate attachments with an object ahead of time. For example:

```
// b = ThreadAddForm, boardID = 123456
b1234567-8d6c0dd0c64d8f524a65a76e128a663

// t = Reply to a thread, threadID = 123456
t7654321-6e465e882976bde0b0a88cb3d6f6ab8

// p = Edit a post, postID = 123456
p1122334-8d5d1da48781e68b2cbbdfecb2c82db
```

Since those are tied to an `objectTypeID`, the prefix is perfectly known to the callee and still holds enough random bytes.

We can then modify the `wcf\system\attachment\AttachmentHandler`:
```php
public function updateObjectID($objectID, string $prefix = '')
```

The prefix is then used as `tmpHash LIKE <prefix>%` which is able to leverage the existing index.

Closes #3983 
Closes #3714

**Comment by TimWolla** [comment]
This was implemented as fully deterministic tmpHashes within com.woltlab.wbb. The resulting tmpHash is the SHA-1 hash of:

1. The current class name (ThreadPage / ThreadAddForm).
2. The object ID (Thread ID / Board ID).

These two conditions match the scoping of redactor's autosave.

The third "ingredient" is the active sessionID. This makes the resulting tmpHash unguessable (this is required for security) and nicely separates all devices by a single user, as redactor's autosave is device specific as well.

Example implementation:

```
            \sha1(\implode("\0", [
                // Use class name + ID to match the autosave scoping.
                self::class,
                $something->someID,
                // Bind the tmpHash to the current session to make it unguessable.
                WCF::getSession()->sessionID,
            ]))
```
