### ISSUE TITLE
Link the full attachment area for images smaller than the thumbnail size

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4601]
For very small image attachments it might be hard to right click them with the mouse to grab the URL. The full "box" showing such images should be linked similar to attachments that have a thumbnail.

**Comment by dtdesign** [comment]
I don't understand this issue. Links are only placed around attachments if there are larger versions available. However, if the attached image is already smaller than the thumbnail size then there is no larger size anyway, therefore there is no link.

Can you please explain what kind of image I need to reproduce this?

**Comment by TimWolla** [comment]
> Links are only placed around attachments if there are larger versions available.

Yes, exactly. This is a request to change this to always link to the “original” size (in this case: to the same image) with a largish target area. Otherwise it might be hard to actually download an attachment that has a small size (e.g. 10×10px), as one has to hit the image to right click and "Save Image". With a link one can easily "Save Target As".

Another side benefit might be that these images will start to appear in the lightbox. Currently one might miss then when looking through the attached images via the lightbox.
