### ISSUE TITLE
MariaDB version is incorrectly detected when replication is active

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#4626]
see https://stackoverflow.com/questions/56601304/what-does-the-first-part-of-the-mariadb-version-string-mean

**Comment by BurntimeX** [comment]
Only WCF 2.1 was affected. From 3.0 on, this was already handled by using `SELECT VERSION()`.
I have reverted your commit.

**Comment by TimWolla** [comment]
> From 3.0 on, this was already handled by using `SELECT VERSION()`.

For the reference: c0babef492f585c98bb2a4affd06d3cd1c48b5b7
