### ISSUE TITLE
Build the Core myself

### ISSUE THREAD

**Issue by AlternativeCookie** [WoltLab/WCF#4675]
How do I build the WSC myself?

Thank u very much!

**Comment by TimWolla** [comment]
For a production environment we recommend using our official releases at: https://www.woltlab.com/en/woltlab-suite-download/.

If you'd like to perform development on WoltLab Suite itself, you can take a look at the [wcfsetup.yml](https://github.com/WoltLab/WCF/blob/master/.github/workflows/wcfsetup.yml) workflow. It builds WCFSetup.tar.gz for each pull request to ease testing.

**Comment by AlternativeCookie** [comment]
> If you'd like to perform development on WoltLab Suite itself, you can take a look at the [wcfsetup.yml](https://github.com/WoltLab/WCF/blob/master/.github/workflows/wcfsetup.yml) workflow. It builds WCFSetup.tar.gz for each pull request to ease testing.

That's what I was looking for. Thank you 👍
