### ISSUE TITLE
Remove outdated JS files

### ISSUE THREAD

**Issue by joshuaruesweg** [WoltLab/WCF#4677]
Currently, the JS files for deleted TS files are not automatically deleted. The remaining artefacts must be cleaned up before the release.

**Comment by TimWolla** [comment]
see 26965c56813c74e3683932b7f466b80218898607

**Comment by joshuaruesweg** [comment]
See https://github.com/WoltLab/WCF/commit/3c750b7b89156787becaac19cc04d2ead420aa83 and https://github.com/WoltLab/WCF/commit/f74902c88cbf749e11a9502cabaee19c4e88262e

**Comment by jens1o** [comment]
Why was the Template grammar file removed, @joshuaruesweg ?

**Comment by joshuaruesweg** [comment]
Because it is not needed within the JS-Dir. It is only needed within the TS-Dir: https://github.com/WoltLab/WCF/blob/master/ts/WoltLabSuite/Core/Template.grammar.jison
