### ISSUE TITLE
TypeScript types without PHP files

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#4711]
Hey,

is there any way to install the TypeScript types without having the whole repo with all the PHP files in every package?

**Comment by TimWolla** [comment]
This should already be the case since #4222.

**Comment by Sir-Will** [comment]
Looking through the yarn issues, it seems to be a long time known issue: https://github.com/yarnpkg/yarn/issues/2822

This workaround seems to kinda work: https://github.com/yarnpkg/yarn/issues/2822#issuecomment-847360267
After I added that, the `@woltlab\wcf` dir only included the typescript files and `@woltlab\wcf\wcfsetup\install\files\font\families\Open Sans` for some reason.

https://github.com/Sir-Will/WCF/tree/patch-8
Thought's on adding that?

**Comment by TimWolla** [comment]
https://github.com/WoltLab/WCF/pull/4738#issuecomment-1099201870
