### ISSUE TITLE
Quoted BBCode argument not correctly handled if `enableHtml = 0`

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4717]
This was reproduced with com.woltlab.wbb and manual database edits, but can likewise happen for importers.

1. Modify a post in the database to `enableHtml = 0` and message =

```
[quote='Test','https://www.example.com']Quote[/QUOTE] Stuff
``` 

2. Run the data rebuild for posts.
3. Notice that the resulting post now has `enableHtml = 1` (correct) and message = 

```
<woltlab-quote data-author="'Test'" data-link="'https://www.example.com'"><p>Quote</p></woltlab-quote><p>Stuff</p>
```

with erroneous single quotes around link and author. This does not happen if `enableHtml` is left at 1 when changing the contents.

**Comment by dtdesign** [comment]
Processing a message with `enableHtml = 0` will enable the code path for pure BBCode messages. Therefore this test case is sufficient:
```php
$htmlInputProcessor = new HtmlInputProcessor();
$htmlInputProcessor->process(
    <<<HTML
[quote='Test','https://www.example.com']Quote[/QUOTE] Stuff
HTML,
    'com.woltlab.wbb.post',
    0,
    true
);
```

**Comment by dtdesign** [comment]
Broken by f631a7de6506e52095299c15042c25a3979a8200 which changed the behavior of `StringUtil::encodeHTML()` to match PHP 8.1. This change encodes single quotes to `&#039;` which it left untouched before.
