### ISSUE TITLE
Style imagePath defined by style.xml ignored

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#4731]
Hello,

while trying to update a style to 5.3/5.4 I noticed that the imagePath was forced to `images/style-5/`, causing the images not to be found. To correct this, I added `<images path="images/woltlabstyles/">images.tar</images>` to the style.xml, but the path is not being used during update or install.

The export does export the path though: https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/data/style/StyleEditor.class.php#L983

The style has multiple versions with different colors with the same images, so I'm trying to use the same path for all versions, like before 5.3.

How can I achieve this?
Is it supposed to always force the `images/style-X` path and ignore the path defined in style.xml?

Unter https://docs.woltlab.com/5.4/migration/wsc52/php/ konnte ich über diese Änderung auch nichts finden.

**Comment by TimWolla** [comment]
> Is it supposed to always force the `images/style-X` path and ignore the path defined in style.xml?

Yes. 

> The export does export the path though:

The export embeds the path for compatibility with older versions.

**Comment by Sir-Will** [comment]
Nvm, using `../images/` instead of `#{$style_image_path}` seems to work and should work with all installations as style and images are always in the same directory.
