### ISSUE TITLE
Remove `wcf.global.noDeclaration` option from the gender profile field

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4770]
since 6fef8b82e15794eee5317e6b15bb0670f137315c it is redundant with the default `wcf.global.noSelection` option in that it won't show any gender (i.e. it does not allow for an explicit “Unspecified” gender).

**Comment by TimWolla** [comment]
This is likely blocked by #4771.

**Comment by BurntimeX** [comment]
Obsolete after reverting of https://github.com/WoltLab/WCF/commit/6fef8b82e15794eee5317e6b15bb0670f137315c
