### ISSUE TITLE
Sync selectOptionType in acp templates with frontend templates

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4771]
https://github.com/WoltLab/WCF/blob/c29b75e0e43c5680f7d4182325b5958902997661/wcfsetup/install/files/acp/templates/selectOptionType.tpl#L2

vs

6fef8b82e15794eee5317e6b15bb0670f137315c

**Comment by TimWolla** [comment]
Generally speaking it appears that `allowEmptyValue` is completely obsolete, because it only controls the template rendering, but does nothing about the PHP side, unless I missed something.

**Comment by BurntimeX** [comment]
I reverted https://github.com/WoltLab/WCF/commit/6fef8b82e15794eee5317e6b15bb0670f137315c, as it basically breaks any select option in user the profile and in user settings (e.g. privacy settings).
