### ISSUE TITLE
Modernize the favicon handling

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4885]
- [x] Do not generate a .ico favicon: Browsers support `.png` well.
    - [x] This avoids the need for an external library that is no longer maintained.
- [ ] Increase the expected size of the favicon template to 512x512 (#4449)
- [x] https://www.woltlab.com/community/thread/296627-favicon-definition-in-head-veraltet/

**Comment by TimWolla** [comment]
> * [ ]  This avoids the need for an external library that is no longer maintained.

see also: #4911 4911

**Comment by dtdesign** [comment]
The entire manifset fike is a bit dated and should be refreshed, but this makes most sense in the context of the introduction of a lightweight PWA.
