### ISSUE TITLE
Add User::isBanned() method

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4938]
This method should be used everywhere where `->banned` is currently checked, especially since the majority of locations does not also check for owner access.

see https://github.com/WoltLab/WCF/pull/4935/files#r940140082

**Comment by BurntimeX** [comment]
The check for the owner user group is intended to ensure that you do not accidentally exclude yourself from your own installation. In all other places (especially in templates), the additional check of the owner user group is not necessary.
