### ISSUE TITLE
Utilized spiderList.xml is outdated

### ISSUE THREAD

**Issue by IceQ1337** [WoltLab/WCF#5021]
The spiderList.xml at http://assets.woltlab.com/spiderlist/typhoon/list.xml that is used in the [RefreshSearchRobotsCronjob](https://github.com/WoltLab/WCF/blob/5.5/wcfsetup/install/files/lib/system/cronjob/RefreshSearchRobotsCronjob.class.php#L25) to update the list of search robots is very outdated and does not include entries from pre-5.4. Since the list is not tied to major releases, it should be updated more frequently. For example, the "serpstatbot" in version 1.0 was added in April 2021.

![Binturong294](https://user-images.githubusercontent.com/11349966/193613407-c5d8caab-33c6-4815-9685-9b27980f2a58.png)

I'd like to see the spiderList to be updated after https://github.com/WoltLab/WCF/pull/4761 has been reviewed and (hopefully) merged :)

**Comment by TimWolla** [comment]
Now updated with the version in master.
