### ISSUE TITLE
Handling of FA brand icons is not great

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#5040]
The brand icons are currently special cased in `IconFunctionTemplatePlugin`, without any reusable class. This makes it harder to statically bake them into the template to avoid the I/O of loading the icon file for every request:

```
[pid 71525] openat(AT_FDCWD, "/var/www/html/icon/font-awesome/v6/brands/facebook.svg", O_RDONLY) = 8
[pid 71525] openat(AT_FDCWD, "/var/www/html/icon/font-awesome/v6/brands/twitter.svg", O_RDONLY) = 8
[pid 71525] openat(AT_FDCWD, "/var/www/html/icon/font-awesome/v6/brands/reddit.svg", O_RDONLY) = 8
[pid 71525] openat(AT_FDCWD, "/var/www/html/icon/font-awesome/v6/brands/linkedin-in.svg", O_RDONLY) = 8
[pid 71525] openat(AT_FDCWD, "/var/www/html/icon/font-awesome/v6/brands/pinterest.svg", O_RDONLY) = 8
```

**Comment by dtdesign** [comment]
Is there any reason we don’t handle those in the icon prefilter too?

We might need to move the logic for the HTML generation elsewhere, something like this should work:

```php
$html = FontAwesomeIconBrand::fromValues($name)->toHtml($size);
```

The name was chosen to make it similar to `FontAwesomeIcon`, but avoiding `FontAweseomBrand` which would be too easy to confuse with the regular icons when auto-completing in the IDE.

Alternatively I would be fine to add a static function elsewhere that gets the job done.

**Comment by TimWolla** [comment]
> Is there any reason we don’t handle those in the icon prefilter too?

No, that was the intention of this issue: "This makes it harder to statically bake them into the template to avoid the I/O of loading the icon file for every request:".
