### ISSUE TITLE
Register custom elements automatically once the corresponding module is loaded

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#5061]
https://github.com/WoltLab/WCF/blob/c0a7a5f3acfbae395bdbe00f950e1bc062e94862/ts/WoltLabSuite/Core/Element/woltlab-core-dialog.ts#L260-L265

It should not be necessary to manually call `setup()`, instead the element should be registered automatically.

**Comment by dtdesign** [comment]
Fixed in 15397da0f65d2d37ff27b4c52bd621bf2314215c
