### ISSUE TITLE
Do not add website name to Title on every page

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5064]
According to Google, the name of the website should not be part of the title on every page. This is especially true after the update of mobile search results pages.

[Google pointed out](https://twitter.com/dannysullivan/status/1581031778885677057) that the name of the website should not be in the title of every single page. They refer to the [documentation on title links](https://developers.google.com/search/docs/appearance/title-link). There, under the item "Duplication of the site name in the <title> element", it is stated that in the case of domain-level website names, Google can remove the name of the website from the title link if it is a repetition of the name of the website that is already displayed in the search result.

![image](https://user-images.githubusercontent.com/81188/197293328-841773a8-ec68-4711-b1c6-061fe9be1c5d.png)

For a few days now, Google has been displaying the name of websites on mobile search results pages. When selecting the displayed website name, Google uses various data sources, namely the title tags, structured data, and data from the Open Graph (og_site_name). In particular, structured data from the homepage is relevant.

**Comment by cadeyrn** [comment]
While I appreciate optimizations for search engines, first and foremost the title is for real users not for search engines. It's what it displayed in the tab of the browser. I use this information very often to identify websites with an ambiguous favicon. And if Google may omit the page title anyway there is no reason to remove it for users.

**Comment by BurntimeX** [comment]
I agree with @cadeyrn and would leave this unchanged.
