### ISSUE TITLE
Add "response_mode" "form_post" to AbstractOauth2Action

### ISSUE THREAD

**Issue by Hanashi** [WoltLab/WCF#5069]
The class `AbstractOauth2Action` is currently only designed for the default `response_mode` `query`. But there are OAuth2 providers which require `response_mode` `form_post` (e.g. Sign in with Apple). Therefore I ask to change this more dynamically, so that the `response_mode` `form_post` can be used as well.

**Comment by TimWolla** [comment]
Wanted to look into Twitter first, as that is a standalone controller that is reasonably similar. While doing so, I came across cuyz/valinor#358, so putting this on hold for now.
