### ISSUE TITLE
Banreason no longer accepts template scripting

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5087]
While this was working prior to 6.0, template scripting doesn't seem to be working anymore. So even `{if LANGUAGE_USE_INFORMAL_VARIANT}xxxx{else}yyyy{/if}` is printed literally.

**Comment by TimWolla** [comment]
Which banReason are you referring to? Do you have a before and after screenshot?

**Comment by SoftCreatR** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/81188/198840151-faec0870-57a2-4be1-8450-51f31bc33398.png)

However, after a few tests, it seems that it also didn't work in 5.5, and 5.4, and it's just that no one has noticed or reported it yet, which is why I assumed it worked as intended in the previous versions.

However, it must have worked at some point, otherwise, I would very likely have noticed it myself.
