### ISSUE TITLE
Dialog display

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5093]
Dialogs are pretty broken, especially when displaying large error messages:

![image](https://user-images.githubusercontent.com/81188/198896625-c9b7198e-0143-481d-bb10-75bd9c7b122c.png)

**Comment by TimWolla** [comment]
> especially when displaying large error messages:

Fixing this is planned as part of #4878.

> Dialogs are pretty broken,

Any other situations where the dialog is “pretty broken”, since you used the phrase “especially”?

**Comment by SoftCreatR** [comment]
The only thing that comes to mind is that the dialogues are far too wide in some cases.

**Comment by TimWolla** [comment]
> are far too wide in some cases.

Do you also have an example screenshot for that?

**Comment by SoftCreatR** [comment]
Before:

![unknown](https://user-images.githubusercontent.com/81188/198980489-d70ba0f7-9e2d-40a5-a6b3-26a0d820f5c7.png)

After:

![unknown](https://user-images.githubusercontent.com/81188/198980516-9c44ffa8-f638-4dcb-aaae-769e140b1d00.png)

**Comment by TimWolla** [comment]
Okay, that is a plugin dialog. Just to confirm: Did you already migrate that one to [the new dialog API](https://docs.woltlab.com/6.0/migration/wsc55/dialogs/) or is this the legacy JavaScript?

**Comment by TimWolla** [comment]
And if you did migrate it: What type of Dialog did you use / do you have a JavaScript excerpt?

**Comment by dtdesign** [comment]
For clarification: The smaller dialog is a side-effect of the implementation of the previous dialogs, in particular how the CSS positioning worked.

Also: Please use a confirmation dialog instead, they also use a restricted width. See https://docs.woltlab.com/6.0/javascript/components_confirmation/

**Comment by SoftCreatR** [comment]
Thank you for the hint, however, the confirmation component doesn't seem to support HTML, as the dialog component does.

**Comment by dtdesign** [comment]
It does, the `.content` property is exposed as part of the underlying dialog API. See https://github.com/WoltLab/WCF/blob/014301edb90c061b9e1efb428d0b8221413ee81f/ts/WoltLabSuite/Core/Acp/Ui/Article/InlineEditor.ts#L212-L263 as an example.

Thank you for bringing this up, it appears to be missing from the doc for the confirmation API.

**Comment by SoftCreatR** [comment]
It seems to work. However, is there a specific reason for the 500px width? Because that's really tiny IMHO. What about 768px instead? So it takes the full-screen width on Tablets (portrait) and smartphones but has a decent size on bigger screens.

Depending on the amount of text, it may look very squeezed:

![image](https://user-images.githubusercontent.com/81188/199134142-94acdc4e-0907-4638-9349-58172224d780.png)

While this looks way better imho:

![image](https://user-images.githubusercontent.com/81188/199134245-b57aaa6b-bee4-4639-8de6-c56fe9a06ccd.png)

**Comment by dtdesign** [comment]
I do not think that the width is the problem, but your confirmation dialog contains too much information. I’m not blaming you though; We have been guilty of these kind of dialogs ourselves, which is why we put a lot of time into researching UI/UX principles and especially the accessibility of (confirmation) dialogs.

The new confirmation dialogs are designed to contain a full question in the title along with an optional description that provides additional context. The key is to keep these confirmation dialogs as short as possible by avoiding redundant information, they should be on point.

For comparison, this is the dialog that is shown using the code above:
![image](https://user-images.githubusercontent.com/208610/199221545-3eb8fd11-9ac0-4285-a217-466cf13a9e94.png)

**Comment by SoftCreatR** [comment]
Well then, maybe I should try to shorten the text and use linebreaks :)

**Comment by TimWolla** [comment]
> Well then, maybe I should try to shorten the text and use linebreaks :)

@SoftCreatR We’re also happy to give more specific phrasing advice and also to “review” your attempts within the [Plugin Development board](https://www.woltlab.com/community/board/76-plugin-development/) to make sure the adjustments for WoltLab Suite 6.0 proceed as smoothly as possible and also allowing developers to learn from each other. We’ve just added a 6.0 label in that board.
