### ISSUE TITLE
Bring back custom icon for seach result items

### ISSUE THREAD

**Issue by Krymonota** [WoltLab/WCF#5109]
In commit 3616f5d90ce4fb95e940a94fa2354d2fa2421de8, you have removed the custom icon for search result items. According to you, "this feature was entirely unused". This may be the case with WoltLab apps, but there are existing use cases for plugins as this feature enables customization and an improved user experience at a low cost.

With [Simple FAQ](https://www.woltlab.com/pluginstore/file/6515-simple-faq/), there's at least one plugin in the Plugin-Store that utilizes this feature: https://github.com/HanashiDev/dev.hanashi.wsc.faq/blob/ecbfcf13d51cd66640c8f479a80f25d9e17c8085/files/lib/data/faq/Question.class.php#L17

In addition, it has been considered to use this feature for products in the VieCode Shop in the future.

Of course, a generic file icon is still better than a guest user profile as in previous WSC versions, but in my opinion it would be a shame to lose this feature for no (apparent) reason. Therefore, I would advocate for reintroducing this feature.

**Comment by mutec** [comment]
@BurntimeX this is not resolved by #5461 since it's not possible to set a different icon per object (again). For example the shop ships the possibility to set a custom icon per product.
