### ISSUE TITLE
package.json not covered by release-logic

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5110]
https://github.com/WoltLab/WCF/blob/master/package.json still shows the version as `5.4.0`.
The version should get updated during every release for obvious reasons.

**Comment by TimWolla** [comment]
> The version should get updated during every release for obvious reasons.

I find that not at all obvious (apart from keeping things neat and tidy, which *is* a valid reason). The package is not published on npm and is instead consumed via a git reference. Did you encounter any specific issues with the mismatching version number?

**Comment by mutec** [comment]
So versioning isn't obvious for all parts of the software? That would mean the WSC-package is versioned as 5.5.4, but the TypeScript is still versioned as 5.5.0, but contains changes compared to 5.5.0.
However publishing the package would be another good point and makes it easier to handle changes in reqirements.

**Comment by TimWolla** [comment]
> So versioning isn't obvious for all parts of the software?

The version number in package.json only exists because it is a required field. The TypeScript files are currently meant to be consumed using a git reference which provides versioning. That's why I asked if you did encounter any specific issues with a mismatching / non-updated version number.

**Comment by mutec** [comment]
I was just struggling for whatever reason when I started migrations to WSC 6.
However staging and getting the package from somewhere would make it easier to track changes or require a specific state matching the required version in `package.xml`.

**Comment by TimWolla** [comment]
> Committing to some shared repository that would act as a source of truth would also require a user-specific access token I believe.

Ha! Deploy keys work for this, because they may be allowed push access. We're now exporting the .d.ts files in https://github.com/WoltLab/d.ts (for now only WCF, Conversations and Forum are available there; and only for master / 6.0). 

See this commit with details how to migrate:

https://github.com/WoltLab/com.woltlab.wcf.conversation/commit/ca888392e5c5836665a618f9d99040de82ee5eed

**Comment by mutec** [comment]
@TimWolla I'm pretty sure it's a stupid question, but in case the d.ts-stuff contains the api of the current project (e.g. when working on the conversations package), don't you have two differing states of available api?
I never tried it since I'm not maintaining the packages nor contributing to other packages than the Core itself, so I didn't check what happens in case the you remove some functions or classes, but the referred branch or commit still contains it. Does it automatically hide/exclude it from type hinting (since it's d.ts-stuff, no source-code at all) or might that cause being api available, that's not available?

**Comment by TimWolla** [comment]
@mutec I never explicitly tested this myself either, but we also didn't experience any obvious issues either. Generally the API surface is rather stable and it's rare that functionality is removed. Even more rare within a non-WCF package. Thus TypeScript should just merge the declarations (which will be almost completely identical) and it works as expected and with the next update of the d.ts commit version in package.json it will match up again.
