### ISSUE TITLE
Check for valid version numbers is case-sensitive

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5111]
`<excludedpackage version="6.1.0 Alpha 1">com.woltlab.wcf</excludedpackage>` is accepted
`<excludedpackage version="6.1.0 alpha 1">com.woltlab.wcf</excludedpackage>` is rejected as invalid

**Comment by TimWolla** [comment]
This is intentional to narrow down the list of possible cases that might need to be handled.

see 9fcc61e65add1d3490a7ec341c738d966563d7ee
