### ISSUE TITLE
All files must have the extension '.tpl'

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5115]
We've created an application as normal package. This application has (acp)templates. The problem is, that the installation fails (and possibly breaks the running installation) due to the fact, that we also ship .htaccess files within the template archives:

> All files must have the extension '.tpl'

Is there a way around this, except for omitting the .htaccess files?

**Comment by TimWolla** [comment]
The `.htaccess` is intended to be deployed using the “file” PIP.
