### ISSUE TITLE
Update browser related PHP functions

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5132]
The browser-related functions are fairly old. The users online list is missing a lot of more specific browsers, and the mobile detection regex is almost 8 years old, without any changes.

Here's a modern and maintained alternative from the matomo team: https://github.com/matomo-org/device-detector/blob/master/Parser/Client/Browser.php

**Comment by TimWolla** [comment]
I’d rather not include an external library for this, as contrary to an traffic analysis platform like Matomo, the parsing of user-agents effectively only used for less-important functionality (showing a “readable” browser and icon in the list of sessions). 

If some important browser is missing, feel free so send a PR adding it to `\wcf\util\UserAgent`. Likewise I'm also happy to update `isMobileBrowser()` with a properly licensed and well-sourced, but simpl-ish detection mechanism.

**Comment by SoftCreatR** [comment]
The idea was not to use an external library, but to get some inspiration :)

**Comment by TimWolla** [comment]
> but to get some inspiration :)

Not possible, Matomo’s device detector is licensed as LGPL 3.0, whereas WoltLab Suite Core is licensed as LGPL 2.1. While we may _link with_ the library, we may not simply grab logic from it, as the LGPL 3 applies then.
