### ISSUE TITLE
Dedicated BBCode-Templates

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5152]
Over the years, the problem has arisen from time to time that templates of BBCodes were missing in the ACP because it was forgotten to make them available there (e.g. https://github.com/WoltLab/WCF/pull/5151), which ultimately leads to unnecessary error messages.

In addition, it can happen that there are discrepancies in content between the templates for the frontend and the ACP, because it may have been forgotten to adjust both templates accordingly.

I would like to suggest treating templates for BBCodes differently in the future. So in the future, it should no longer be necessary to maintain the same file in two places. This saves unnecessary effort and reduces potential sources of error.

**Comment by BurntimeX** [comment]
This should ideally work similar to the email templates:

* Shared templates need to be prefixed with `shared_` and will only ever be placed in the frontend templates.
* A special template group for shared templates can be used to provide a modified variant of a `shared_*` template.
* Shared templates are never placed inside the ACP template folder.
* It must not be possible to modify shared templates within custom template groups.
