### ISSUE TITLE
Allow icon removal

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5179]
As of now, you can only set an icon for an existing fa-icon element. It would be good, if there would be a function `removeIcon` or something, that set's the element to something like `<fa-icon size="64" name=""></fa-icon>`, or another kind of placeholder, that could be re-used to execute `setIcon` on it, when needed.

**Comment by dtdesign** [comment]
Icons are a HTML element like every other, you can either remove the element from the DOM or simply hide it through `elementRef.hidden = true` if you don’t need it. An empty icon name is invalid and not good practice.

**Comment by SoftCreatR** [comment]
The problem is, that setIcon requires an existing element. So according to your explanation, it is required to generate an fa-icon element on-the-fly. Is that already possible without much effort?

**Comment by dtdesign** [comment]
You can programmatically create icons:

```ts
const icon = document.createElement("fa-icon");
icon.setIcon("user");
```

**Comment by SoftCreatR** [comment]
Makes sense. Thank you.
