### ISSUE TITLE
BBCode Custom Icon

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5182]
The description says:

> The image must be placed inside the directory wcf/icon/ or use a [FontAwesome](https://fontawesome.com/icons) icon.

But this doesn't seem to work. Or does it require a specific format, like SVG?

**Comment by dtdesign** [comment]
Please provide more details, the description is too vague. Have you checked the DOM to see what was inserted?

**Comment by TimWolla** [comment]
@SoftCreatR Ping :point_up:

**Comment by TimWolla** [comment]
@SoftCreatR Is this still current?

**Comment by SoftCreatR** [comment]
Maybe the error description was a bit inaccurate. It is about the fact that the uploaded image is not available for selection at all in the dialog. Presumably you should enter the name of the image file in the input field. However, nothing can be entered there, because a click on the input field displays the dialog.
