### ISSUE TITLE
`IconFormField` should implement `INullableFormField`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5205]
It should be possible to export the value as `null` in case no icon is selected.
However this is kind of a bug since `IconFormField::$icon` does not allow `null`: https://github.com/WoltLab/WCF/blob/fb25bc957aa4b6eec01bc22b22424fa941469599/wcfsetup/install/files/lib/system/form/builder/field/IconFormField.class.php#L116

**Comment by TimWolla** [comment]
> However this is kind of a bug since `IconFormField::$icon` does not allow `null`:

Related: #5160.

**Comment by dtdesign** [comment]
We have historically used an empty string to indicate “no icon”. Although it would be better to make this explicit using a nullable value, such a change breaks both compatibility and expectations.
