### ISSUE TITLE
User-manipulated URLs throwing avoidable errors

### ISSUE THREAD

**Issue by IceQ1337** [WoltLab/WCF#5247]
There's always a chance someone is tampering with the URLs (e.g. to achieve an SQL-Injection), but that shouldn't fill up our error log unnecessarily unless it's really serious. In most cases, an error message or at least something like an `IllegalLinkException` should probably be shown instead.

I grouped the following errors into one issue and intentionally didn't report them in the community forum.

User-manipulated URLs may throw the following errors:

`GET /members-list/?letter[%24testing]=1&pageNo=2&sortField=wbbPosts&sortOrder=DESC`
`GET /members-list/?letter[]=&pageNo=2&sortField=wbbPosts&sortOrder=DESC`
https://github.com/WoltLab/WCF/blob/b9acc61f5de26427f18a9d58a13a542e0f54939d/wcfsetup/install/files/lib/page/MembersListPage.class.php#L94

Error: `mb_strlen(): Argument #1 ($string) must be of type string, array given`

---

`GET /media/1-image-name-png/?thumbnail[]=large`
`GET /media/1-image-name-png/?thumbnail[%24testing]=1`
https://github.com/WoltLab/WCF/blob/8478882b6a45017db261ce955737e6f514921124/wcfsetup/install/files/lib/page/MediaPage.class.php#L140

Error: `Illegal offset type in isset or empty `

---

`GET /login/?url[]=https://domain.invalid/`
https://github.com/WoltLab/WCF/blob/8478882b6a45017db261ce955737e6f514921124/wcfsetup/install/files/lib/util/Url.class.php#L65

Error: `parse_url(): Argument #1 ($url) must be of type string, array given `

---

`POST /user-search/`
Input: Partially redacted. I'm happy to provide the full StackTrace.
https://github.com/WoltLab/WCF/blob/8478882b6a45017db261ce955737e6f514921124/wcfsetup/install/files/lib/system/session/SessionHandler.class.php#L547

Error: `hash_equals(): Argument #2 ($user_string) must be of type string, array given`

---

`POST /login/` / `POST /lost-password/`
Input: Regular expression containing square brackets.
https://github.com/WoltLab/WCF/blob/8478882b6a45017db261ce955737e6f514921124/wcfsetup/install/files/lib/form/LostPasswordForm.class.php#L68

Error: `Array to string conversion`

**Comment by TimWolla** [comment]
see: https://www.woltlab.com/community/thread/295844-illegal-offset-type-in-suche/?postID=1896049#post1896049

For WoltLab Suite 6.0 we've added Valinor to reliably perform this type of structural validation and are making use of it in any new PSR-15 controllers. See: https://docs.woltlab.com/6.0/migration/wsc55/libraries/#input-validation and https://docs.woltlab.com/6.0/migration/wsc55/php/#recommended-changes-for-woltlab-suite-60
