### ISSUE TITLE
Slight refresh of the header and board list.

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5324]
Hi, I come with a proposal.

**Look:**
https://i.ibb.co/0tL0C2z/image.png
or
https://i.ibb.co/ZWFrbFs/1.jpg

This change requires little work and improves the appearance of the forum.

Removing the big header and moving the logo to the small header. Possibly making the menu bar lower. In addition, refreshing the list of topics as in the screenshot. It's proposition. What do you think?

In my opinion, these are not big changes, but they improve the visual effect a lot. I would work on a better search engine. User icons are too big in my opinion.

**Comment by dtdesign** [comment]
This is the repository for WoltLab Suite Core, the underlying framework of our software suite. Please raise such suggestions in our forums instead.
