### ISSUE TITLE
Make the TemplateEngine understand nullsafe operators

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5351]
Supporting the [nullsafe operator](https://wiki.php.net/rfc/nullsafe_operator) in the template syntax would be very useful.

**Comment by TimWolla** [comment]
I didn't have the desire to use that in templates yet (and even in PHP the opportunities to use it are rare), but I can see how that would be a reasonable addition for completeness. I've added this to the 6.1 project, but a reasonably simple and well-tested PR would likely be acceptable for 6.0. Please finish up your existing PRs first, though.
