### ISSUE TITLE
Position of tooltips is broken if body height is not set to 100%

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5365]
E.G:
html, body {
    height: auto;
}
👇
![Bildschirmfoto 2023-03-17 um 13 50 02](https://user-images.githubusercontent.com/1590626/225909330-e4fbe66a-2d7b-48b1-b68c-3ec9e64ce4b6.png)

**Comment by dtdesign** [comment]
The `<html>` and `<body>` element must be full height to avoid multiple issues with absolute positioning.

**Comment by cls-design** [comment]
Nur aus Interesse, gab es hier eine Änderung bei den Tooltips? In meiner letzten Dev gab es da noch kein kein Problem, das tritt erst in meiner neusten Installation auf. Eventuell liegt es an meinen Stiländerungen. Ansonsten muss ich wohl damit leben.
