### ISSUE TITLE
Adding Dark Mode to importet styles is broken

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5368]
If you add a dark mode to importet styles, a style selection appears in the frontend but there is no complete change of the colour scheme. 

If you edit the dark palette and save it, the style in the frontend is set to dark mode, but changing to light has no effect and the style is stuck in dark mode.

**Comment by TimWolla** [comment]
> If you add a dark mode to importet styles,

This is not possible. An imported style is untainted and you cannot add a dark mode to untainted styles.

That said, I just:

- Imported this free style from Plugin Store: https://www.woltlab.com/pluginstore/file/7004-atelier/#overview
- Deleted the template group (to make sure the templates not outdated).
- Tainted the style.
- Added a dark mode.

After hitting F5 in frontend the color scheme selector appeared and was fully functional. When selecting dark mode, the style switched to the default dark scheme colors (as I didn't change any dark mode colors after adding the dark mode).

**Comment by cls-design** [comment]
Yes it works with Atilier. Looks like something in my teststyle (without any templates) cause the problem.

**Comment by cls-design** [comment]
Looks like there is an error if the style contains custom CSS.

To reproduce:

Import Atelier: https://www.woltlab.com/pluginstore/file/7004-atelier/#overview

Add darkmode
Clear the cache via maintenance

Try to switch between color-modes in frontend.

**Comment by dtdesign** [comment]
I can switch the color schema just fine. It did require me to update the outdated template of the style, but other than that the switch works as expected. The background color of the content area is still a bright whitish color, but this is a result of the author ignoring the color palette and applying the color through the custom CSS.

**Comment by dtdesign** [comment]
WSC 6.0 heavily relies on CSS variables, in fact we dropped the use of SCSS variables entirely. (They are still supported though!)

You can apply different CSS depending on the selected color scheme and that works for CSS variables too:
```
html[data-color-scheme="dark"] .my-custom-selector {
    background-color: darkblue;
}

html[data-color-scheme="light"] .my-custom-selector {
    background-color: aliceblue;
}
```

**Comment by cls-design** [comment]
How is that thought of when I want to use style variables? Suppose I want to assign $wcfContentBackground to a container. If I see this correctly I can't access the dark mode palette value via CSS? $wcfContentBackground always contains the color value of the light palette? I would then have to make the adjustments for the darkmode with fixed color values?

`html[data-color-scheme="light"] .my-custom-selector {
    background-color: $wcfContentBackground;
}

html[data-color-scheme="dark"] .my-custom-selector {
    background-color: $wcfContentBackground; <#### Dark-Mode-Color?
}`

**Comment by SoftCreatR** [comment]
Using var(--foo) instead of them.

**Comment by cls-design** [comment]
Maybe it would be a good idea to change the name in the style editor 👀

**Comment by dtdesign** [comment]
What @SoftCreatR said. In general I recommend to not use `$variables` anymore, starting with 6.0 we have shifted all our CSS to use `var(--wcfContentBackground)` and similar. I can imagine us dropping SCSS in a few years entirely, because it has become less and less useful over the years with CSS massively evolving over the years.

There is also the automatically generated special `-rgb` variant of all color variables. This is useful when creating a gradient from “solid color” to “transparent”. One cannot use the `transparent` keyword in Safari, because it defaults to `rgb(0 0 0 / 0%)`, causing an ugly gradient using black intermediate color values.

```css
--wcfContentBackground: rgba(26, 29, 33, 1);
--wcfContentBackground-rgb: 26 29 33;
```

A gradient to “transparent” can be created like this:
```css
.foo {
    background-image: linear-gradient(to right, var(--wcfContentBackground), rgb(var(--wcfContentBackground-rgb) / 0%));
}
```
