### ISSUE TITLE
Refusing to handle an archive outside of the temporary directory

### ISSUE THREAD

**Issue by JulianArrow** [WoltLab/WCF#5370]
Ich erhalte nach der Weiterleitung von install.php zu /acp/index.php?action=WCFSetup folgenden Fehler:

Code
System Information

PHP Version:

8.1.12

WoltLab Suite Core:

6.0.0 dev 1

Peak Memory Usage:

3.993/512 MiB

Request URI:

POST /wsc-coding-area-6/acp/index.php?install-package/&t=c0edf5ce9d4fa60543e6d70e142d31b8cdeca873e95978702bcb9977c2db2610-+xpwfNXsVQSg1fJ68gJS6w==

Referrer:

http://localhost/wsc-coding-area-6/acp/index.php?action=WCFSetup

User Agent:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

Error

Error Message:

Refusing to handle an archive outside of the temporary directory.

Error Type:

Exception

*/lib/system/package/PackageInstallationDispatcher.class.php:483

Stack Trace

#0 wcf\system\package\PackageInstallationDispatcher->getArchive()
*/lib/system/package/PackageInstallationNodeBuilder.class.php:87
#1 wcf\system\package\PackageInstallationNodeBuilder->buildNodes()
*/lib/acp/action/InstallPackageAction.class.php:97
#2 wcf\acp\action\InstallPackageAction->stepPrepare()
*/lib/acp/action/InstallPackageAction.class.php:74
#3 wcf\acp\action\InstallPackageAction->execute()
*/lib/action/AbstractAction.class.php:56
#4 wcf\action\AbstractAction->__run()
*/lib/system/request/Request.class.php:57
#5 wcf\system\request\Request->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/HandleValinorMappingErrors.class.php:34
#6 wcf\http\middleware\HandleValinorMappingErrors->process(Laminas\Diactoros\ServerRequest, wcf\system\request\Request)
*/lib/http/RequestHandlerMiddleware.class.php:36
#7 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/TriggerBackgroundQueue.class.php:40
#8 wcf\http\middleware\TriggerBackgroundQueue->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#9 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/JsonBody.class.php:49
#10 wcf\http\middleware\JsonBody->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#11 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/CheckForOfflineMode.class.php:38
#12 wcf\http\middleware\CheckForOfflineMode->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#13 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/CheckForExpiredAppEvaluation.class.php:56
#14 wcf\http\middleware\CheckForExpiredAppEvaluation->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#15 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/CheckForEnterpriseNonOwnerAccess.class.php:40
#16 wcf\http\middleware\CheckForEnterpriseNonOwnerAccess->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#17 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/EnforceAcpAuthentication.class.php:86
#18 wcf\http\middleware\EnforceAcpAuthentication->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#19 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/CheckUserBan.class.php:47
#20 wcf\http\middleware\CheckUserBan->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#21 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/CheckSystemEnvironment.class.php:36
#22 wcf\http\middleware\CheckSystemEnvironment->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#23 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/Xsrf.class.php:62
#24 wcf\http\middleware\Xsrf->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#25 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/CheckHttpMethod.class.php:42
#26 wcf\http\middleware\CheckHttpMethod->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#27 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/EnforceFrameOptions.class.php:32
#28 wcf\http\middleware\EnforceFrameOptions->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#29 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/EnforceNoCacheForTemporaryRedirects.class.php:36
#30 wcf\http\middleware\EnforceNoCacheForTemporaryRedirects->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#31 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/EnforceCacheControlPrivate.class.php:27
#32 wcf\http\middleware\EnforceCacheControlPrivate->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#33 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/AddAcpSecurityHeaders.class.php:39
#34 wcf\http\middleware\AddAcpSecurityHeaders->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#35 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/PreventMimeSniffing.class.php:32
#36 wcf\http\middleware\PreventMimeSniffing->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#37 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/middleware/HandleStartupErrors.class.php:32
#38 wcf\http\middleware\HandleStartupErrors->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/http/RequestHandlerMiddleware.class.php:36
#39 wcf\http\RequestHandlerMiddleware->handle(Laminas\Diactoros\ServerRequest)
*/lib/http/Pipeline.class.php:44
#40 wcf\http\Pipeline->process(Laminas\Diactoros\ServerRequest, wcf\http\RequestHandlerMiddleware)
*/lib/system/request/RequestHandler.class.php:134
#41 wcf\system\request\RequestHandler->handle('wcf', true)
*/acp/index.php:10
Weniger anzeigen

Alle Dateien und Ordner sollten Vollzugriff haben und nicht schreibgeschützt sein.

**Comment by TimWolla** [comment]
This issue is not actionable, because it lacks the necessary information to debug it. The error message is part of an intentional check:

https://github.com/WoltLab/WCF/blob/6d269e22eaa69e3fc993ab97e9ca3aaa697b96c8/wcfsetup/install/files/lib/system/package/PackageInstallationDispatcher.class.php#L483

Consider dumping both of the values that are compared within the `if()` condition. This will reveal how they are different.

**Comment by JulianArrow** [comment]
string(74) "D:\xampp\htdocs\wsc-coding-area-6/tmp/5f2304225005cff2-com.woltlab.wcf.tar"
string(38) "D:\xampp\htdocs\wsc-coding-area-6/tmp/"

**Comment by gOOvER** [comment]
> string(74) "D:\xampp\htdocs\wsc-coding-area-6/tmp/5f2304225005cff2-com.woltlab.wcf.tar" string(38) "D:\xampp\htdocs\wsc-coding-area-6/tmp/"
> 
> ```
>                 echo '<pre>';
>                 var_dump($this->archive->getArchive(), \TMP_DIR);
>                 echo '</pre>';
>                 exit;
> ```
> 
> string(74) "D:\xampp\htdocs\wsc-coding-area-6\tmp\5f2304225005cff2-com.woltlab.wcf.tar" string(38) "D:\xampp\htdocs\wsc-coding-area-6/tmp/"
> 
> ```
>                 echo '<pre>';
>                 var_dump(\realpath($this->archive->getArchive()), \TMP_DIR);
>                 echo '</pre>';
>                 exit;
> ```

xampp is sometimes a bit a bitch ;) test it on a "real" server

**Comment by TimWolla** [comment]
@JulianArrow Thank you, the cause of the issue is the differing directory separators, because `realpath()` performs a normalization.  For testing purposes you can comment out the check until the issue is properly fixed.
