### ISSUE TITLE
It is impossible to empty css-inputfield

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5377]
Debugmode on

Edit a style
Add some css to Individual CSS and SCSS
Save style
Empty Individual CSS and SCSS
Save style
Go to style overview
Edit style
Go to Individual CSS and SCSS
Previous added CSS appears again

It is only possible to edit CSS, not to delete all.

Edit:

Safari 16.2

**Comment by TimWolla** [comment]
This is referring to WoltLab Suite 6.0 (i.e. it works fine in 5.5)?

**Comment by cls-design** [comment]
Only WoltLab Suite 6.0, works fine in 5.5.
