### ISSUE TITLE
Errormessage appears in the wrong place

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5378]
Add some invalide code to "Individual CSS and SCSS (Dark Color Scheme Only)":

![Bildschirmfoto 2023-03-30 um 12 24 07](https://user-images.githubusercontent.com/1590626/228807971-266edcd7-a7c4-4606-bc75-b374bd491033.png)

Errormessage appears below "Individual CSS and SCSS"

**Comment by TimWolla** [comment]
This is not easily fixable: The SCSS fields cannot be independently validated, because the contents might depend on previous SCSS.

**Comment by cls-design** [comment]
How about an error box above it with error-codes and a hint to check all fields?

At the moment it is about searching in a field where there is no error at all. I spent some time checking code in the wrong field 😅
