### ISSUE TITLE
Adding new CMS contents broken

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5383]
After selecting the content type, no redirect is being performed to the creation form, when the 2nd language is disabled:

![image](https://user-images.githubusercontent.com/81188/229430555-f2336c39-76e0-40fc-9812-f3017f39857a.png)

**Comment by TimWolla** [comment]
It's not entirely clear from the description: This is WoltLab Suite 6.0 specific?

**Comment by SoftCreatR** [comment]
Yes.
