### ISSUE TITLE
Database PIP incorrectly checks the FOO_DIR constant

### ISSUE THREAD

**Issue by darkwood-studios** [WoltLab/WCF#5392]
The database PIP incorrectly checks the FOO_DIR constant. This should reasonably work on the basis of the uncached database information.

When I try to install a pip via `<instruction type="database" application="myapp">acp/database/install_de.myapp.app.php</instruction>`

it results in this error message:

Error Message:
Cannot execute database PIP, abbreviation 'myapp' is unknown.

Error Type:
InvalidArgumentException
*/lib/system/package/plugin/DatabasePackageInstallationPlugin.class.php:39

**Comment by TimWolla** [comment]
Note: This also affects the regular `script` PIP.
