### ISSUE TITLE
Individual CSS for Darkmode not working

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5398]
When changing the individual CSS for the dark color scheme, the following error appears:

> Der SCSS-Code enthält einen Fehler: Invalid value source "/* WCF_STYLE_CUSTOM_USER_MODIFICATIONS */ .bar { }"..

![image](https://user-images.githubusercontent.com/81188/230009304-9a7c7a20-6df5-4fbd-a4d5-555df3c3251e.png)

Steps to reproduce:

Simply enter (valid) CSS code into the 2nd individual CSS-box (the one for darkmode declarations).

**Comment by TimWolla** [comment]
Duplicate of #5378

**Comment by SoftCreatR** [comment]
@TimWolla The main problem here is something else: You can't add any CSS for dark mode at all. The wrong location of the error message was just an "extra".

**Comment by SoftCreatR** [comment]
Updated the description, and the sceenshot accordingly.

**Comment by SoftCreatR** [comment]
This doesn't seem to be fixed. The error remains.

**Comment by TimWolla** [comment]
Reopened.

**Comment by dtdesign** [comment]
This appears to still happen with the regular SCSS input. I’m not sure if this is a bug in the updated version of the SCSS parser or not.
