### ISSUE TITLE
Individual CSS ran't be removed

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5399]
When trying to clear the contents of the individual CSS field (from [this example](https://github.com/WoltLab/WCF/issues/5398)) I get a success message, and the field is empty:

![image](https://user-images.githubusercontent.com/81188/229999731-61bbfd9f-80b4-422e-b759-5c1cff9fa3cb.png)

When reloading the page (or checking the database), you can see, that it's still there:

![image](https://user-images.githubusercontent.com/81188/229999854-279098d6-d561-43d5-826f-cfa74b10a508.png)

**Comment by TimWolla** [comment]
Duplicate of #5377
