### ISSUE TITLE
Template-Event in `systemCheck` for additional checks

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5444]
n/t

**Comment by dtdesign** [comment]
Can you please explain what kind of additional checks you want to make? The controller already permits supplying additional values to be checked such as required php extensions?

**Comment by mutec** [comment]
I added a check for missing, unknown and modified files for development purposes. But when using some APIs (monitoring, sync, mail, redis, es, …), it would be nice to be able to display some kind if availability/integration-check instead of a silent fail.
