### ISSUE TITLE
Icon-Size 8 for usage in `<small>`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5446]
16 is way to big when the icon is used within `small`:
![image](https://user-images.githubusercontent.com/1749344/233793273-6c01368c-6396-4746-97d3-34aff3d80a10.png)

**Comment by dtdesign** [comment]
The icon rendering is already awful in 16px on 1080p screens, decreasing it even further makes them entirely unusable with a few exceptions that can still be deciphered.

Looking at your example, you really should not use an icon there and instead insert a proper text string to explain these values.

In general, avoid using icons unless the functionality is perfectly clear. If your icon’s meaning can only be understood by reading the tooltip (which is unavailable on mobile!) then you should not use an icon.
