### ISSUE TITLE
Autosave probably broken

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5462]
We're ofc still using WSF 5.5, but I think, that isn't the reason:

When editing a post, autosave doesn't seem to work while editing it. Instead, it creates a new key in local storage (e.g. `wsc300089190-ckeditor5-com.woltlab.wbb.postEdit-XXXX`), when either the save button, or the cancel button is clicked, after changes were made (if the content didn't change, this doesn't happen, which is an expected behavior).

EDIT:

Autosave works as designed. Just clicking the save button, or the cancel button, shouldn't trigger an autosave, but remove the key from local storage.

**Comment by dtdesign** [comment]
I cannot confirm this behavior. Accepting the saved content will not clear the storage, which is the correct behavior. Clicking “Cancel” to discard the draft properly removes the key from the `localStorage`.

Please submit a new issue if you believe that you have identified an issue.
