### ISSUE TITLE
Autosave not cleared on submit / aborting edit mode

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5497]
As mentioned in https://github.com/WoltLab/WCF/issues/5462#issuecomment-1536722941, the autosave still seems to be broken.

I am not talking about the dialog that pops up when there's unsaved content, but about the normal Submit button (and the Cancel button on quick reply).

**Comment by dtdesign** [comment]
Fixed in fe6beb2dfb2e2309b086ddcda03a786430d90a49
