### ISSUE TITLE
Make MarkAsRead optional in user menus

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5514]
Not everything providing a user menu supports marking things as read.

**Comment by TimWolla** [comment]
I was confused for a moment, but based on the other issues this is not referring to userMenu.xml, but the dropdowns in userpanel which are also called userMenu internally.

**Comment by mutec** [comment]
@TimWolla sorry, I didn't think about the userMenu-PIP when creating the issue. You're correct, I'm refering to the dropdown-area of the user menu/panel stuff.

**Comment by dtdesign** [comment]
Blocked by #5517
