### ISSUE TITLE
`null`-time in UserMenuData shows 1970-01-01 instead of hiding time information

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5515]
Not everything providing a user menu supports timestamps.

**Comment by TimWolla** [comment]
As the phrasing is a little ambiguous whether this is a bug report or feature request, I'd like to note that neither `null` or `undefined` are valid values as of now:

https://github.com/WoltLab/WCF/blob/bcd2419f71e04ef184fd95ac9dfc91eb6203ea3b/ts/WoltLabSuite/Core/Ui/User/Menu/Data/Provider.ts#L58

**Comment by dtdesign** [comment]
Can you please explain your use-case? I have a hard time imagining a component that implements a data provider for the user menu but does not have a time value, potentially a misuse of the component here?

**Comment by SoftCreatR** [comment]
The shop, and the shopping cart.

**Comment by mutec** [comment]
@dtdesign Maybe there's another way to modernize the integration. I'm not sure what the planned use case for the current implementation was meant to be, it looks like it's supposed to be used by `IUserContent`. Otherwise I didn't find an explicit hint, the descriptions are generic for "user menus", which might include everything belonging to the user-menu-area.

**Comment by dtdesign** [comment]
Blocked by #5517
