### ISSUE TITLE
CKEditor toolbar dropdowns in dialogs cause the dialog to become horizontally scrollable

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#5561]
(Dropdown referring to the second level menu, e.g. when clicking the + to insert a block)

… but when attempting to scroll, the dropdown closes. Ideally the dropdown would either respect the dialog dimensions and open to the left or it should be allowed to exceed the dialog, as it's logically an overlay above the dialog.

Would add a screenshot, but can't because hitting the screenshot key forces the dropdown to close.

**Comment by dtdesign** [comment]
Implicitly fixed through b1a03bcd7b59f1e0ca8f9a61384ca52e9e4dd29e and 10cd0f106eafc17411ead418189ddf3a90a439aa which solved a long-standing layout issue.
