### ISSUE TITLE
Search results in ACP no longer jump to the result

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5580]
For example, the time zone search only jumps to the system tab but not to the time zone setting in the system tab.

**Comment by felix-d1strict** [comment]
Hello,

it seems that the problem occurs only sporadically.
Searching for the time zone seems to work for me. The search "allowed images from external sites" does not seem to work.


https://github.com/WoltLab/WCF/assets/68828301/5fab9c44-075e-48cc-b843-9d9a38b71ab4

**Comment by cls-design** [comment]
You should always enable debug mode when testing to ensure that only current components are used.

**Comment by felix-d1strict** [comment]
Even with dev mode enabled, I get the same result as before. But as I said, with "allowed images from external sites" I can reproduce your said error.
