### ISSUE TITLE
CK-Editor is not available in ACP

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5607]
CK-Editor is not available in articles:

![Bildschirmfoto 2023-08-07 um 13 38 41](https://github.com/WoltLab/WCF/assets/1590626/3b0a1e31-b105-4f81-87e0-f9cf8785b5b8)

Konsole-error:

Failed to load resource: the server responded with a status of 404 (Not Found):

`http://…/acp/style/ckeditor5.css`

**Comment by dtdesign** [comment]
Fixed in 5d5f280e6991dca8b46bd7a34bd45bd67a8bc719
