### ISSUE TITLE
Ensure FA-metadata-files are in sync

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5630]
029adb7cce24e31afce438ba091b9290da74e597 updated to FA 6.4.2, which means that it ships e.g. `x-twitter`, but since the meta data didn't receive any updates, those new icons are not known and rejected.
It would be good to ensure the metadata files are always in sync with the actual list of available icons.

**Comment by TimWolla** [comment]
The metadata files have been updated, but the only new icons are brand icons, which are not part of the metadata:

https://github.com/WoltLab/WCF/blob/eb84933372ce0f7a5404d36a0cd761d67fcde164/extra/update-font-awesome-metadata.ts#L30-L34

**Comment by mutec** [comment]
Ah okay, I forgot using a proper integration instead of the one shipped by the WSC.
