### ISSUE TITLE
General event for info about missing PHP extensions in ACP

### ISSUE THREAD

**Issue by Hanashi** [WoltLab/WCF#5696]
As written in [this topic](https://www.woltlab.com/community/thread/302368-php-erweiterung-überprüfen-vor-app-installation/?postID=1944203#post1944203), it would be good if there would be a general event in the ACP where you can register required PHP extensions. If this PHP extension is not installed, an info should appear in the ACP on the home page.

**Comment by BurntimeX** [comment]
Closed via https://github.com/WoltLab/WCF/pull/5772
