### ISSUE TITLE
Some notes about the authentication process overhaul

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5732]
If the password-button moves down on small screens there is a small gap missing:

![Bildschirmfoto 2023-12-15 um 12 43 35](https://github.com/WoltLab/WCF/assets/1590626/822de6fe-7a28-498b-8f44-b6c94a0b5c1e)

As a suggestion, I would also change the gaps for third-party providers from:

![Bildschirmfoto 2023-12-15 um 12 43 50](https://github.com/WoltLab/WCF/assets/1590626/a849b1ff-2f26-4288-ae0d-cece4d0424c7)

to

![Bildschirmfoto 2023-12-15 um 12 45 36](https://github.com/WoltLab/WCF/assets/1590626/176f6834-2884-48af-b058-95def8983237)

**Comment by felix-d1strict** [comment]
Hello,

> If the password-button moves down on small screens there is a small gap missing:
> 
> ![Bildschirmfoto 2023-12-15 um 12 43 35](https://private-user-images.githubusercontent.com/1590626/290817874-822de6fe-7a28-498b-8f44-b6c94a0b5c1e.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTM1MjgsIm5iZiI6MTcwMjgxMzIyOCwicGF0aCI6Ii8xNTkwNjI2LzI5MDgxNzg3NC04MjJkZTZmZS03YTI4LTQ5OGItOGY0NC1iNmM5NGEwYjVjMWUuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTdUMTE0MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjA3NzUxZThkOGNkYjExOGY1MDU2NmJlMTQ0MTk4YmFkNDZmNmEzZGUzYTFlZTNlZjg0ZmRjZWQ1NGI4ZGZkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CmIi6OkG1VxLQ_CLE2Yf4nK2-vGteZcjdbBaMUEcnVI)

In my opinion, the button should still be in the same line as the password input field. Because somehow a single button (even if it perhaps has a gap at the top) looks a bit strange. Especially because there is so much whitespace available on the right.
Just as is the case here:


![Screenshot_20231217-124418](https://github.com/WoltLab/WCF/assets/68828301/e57f4c8d-d346-43a8-9a2a-b38c64e59d3f)

**Comment by eveneme** [comment]
Yes the button should be on the same line.  As for the word "oder", that's a good point.  you can still center this word.

**Comment by eveneme** [comment]
My suggestion:
![290818319-176f6834-2884-48af-b058-95def8983237 kopia](https://github.com/WoltLab/WCF/assets/85762221/384593b6-ed50-4bb7-aac0-3d2e49132d79)
