### ISSUE TITLE
Toast notifications

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5739]
Modern push notifications at the bottom of the screen providing information about important events, such as private messages, warnings, or thread replies. Currently, there is a lack of such notifications.

Examples:
![Screenshot_20231224_214841_Chrome](https://github.com/WoltLab/WCF/assets/85762221/6a741c8a-0c0f-45cf-a353-6aeb9f8ccf0c)

![Screenshot_20231224_220257_Chrome](https://github.com/WoltLab/WCF/assets/85762221/7751e23a-ec82-4e87-9f2a-f06d98455044)

**Comment by mutec** [comment]
I don't see any real push messages within your screenshot, but have a look at https://github.com/WoltLab/WCF/issues/3960

**Comment by eveneme** [comment]
I'm referring to push notifications, typically located at the bottom of screens on mobile devices or computers. They slide up from the bottom or appear on the side, providing various alerts such as warnings, private messages, etc. You can roughly see how they work on this website: https://mui.com/material-ui/react-snackbar/

**Comment by eveneme** [comment]
Examples v2"

https://tailwindui.com/components/application-ui/overlays/notifications

**Comment by BurntimeX** [comment]
see https://github.com/WoltLab/WCF/issues/6134
