### ISSUE TITLE
Modernization of forum section icons

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5752]
The modernization of forum section icons, adding a background with rounded corners. It seems to me that it looks better than it currently does.

![ezgif-1-770fb9d974](https://github.com/WoltLab/WCF/assets/85762221/caa70fda-5eee-4097-b198-5865cfb2008f)

**Comment by eveneme** [comment]
V2:
![image](https://github.com/WoltLab/WCF/assets/85762221/bbd23fd1-c9f6-4178-92d7-82ba258808bf)

It seems to me that these icons look better than they have so far. Implementing this shouldn't take much time either, and it looks nicer.

**Comment by eveneme** [comment]
@BurntimeX look https://woltlab.pl/

**Comment by BurntimeX** [comment]
Although I like the change, I don't think it would be wise to include it in the standard design. The standard design should be as simple as possible, as it is the basis for all other designs.
