### ISSUE TITLE
The message indicates a lack of permissions to download the attachment

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5758]
Currently, there is a message stating that you don't have permission to view this page. In my opinion, the notification should be, for example, in the form of a popup window informing about the lack of permissions to download the attachment, rather than redirecting to another page and indicating a lack of permissions to view this page.

**Comment by BurntimeX** [comment]
Specific error messages are indeed better from a user-friendliness point of view. However, the consistent implementation of such error messages involves a lot of effort, which is why I prefer to continue using the generic error messages.
