### ISSUE TITLE
Advanced notification system

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5759]
The notification system should be more extensive and detailed; at times, the same message is used for multiple issues. Please also refer to: https://github.com/WoltLab/WCF/issues/5739

**Comment by mutec** [comment]
Do you have examples for those duplications?

**Comment by eveneme** [comment]
For example, downloading an attachment. The message should state that you don't have permission to download this attachment. Instead, it redirects to another page and states that you don't have access to the content being viewed. In my opinion, notifications should be more detailed and accurately specified.

**Comment by BurntimeX** [comment]
There may be some spots where an individual notification makes sense. However, I don't think it makes sense to add individual notification everywhere. The effort involved would be very high and disproportionate to the benefit.

In my opinion, a "Permission Denied" error message when trying to download a file attachment is completely sufficient.

**Comment by eveneme** [comment]
In my opinion, instead of redirecting to another page and notifying about the lack of permissions, a popup window should appear, informing that there are insufficient privileges to download the attachment.

**Comment by eveneme** [comment]
Examples:
https://tailwindui.com/components/application-ui/overlays/notifications
