### ISSUE TITLE
Warn for the administrator

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5817]
It seems to me that this 'Warn' option should not be visible to oneself and the administrator.

![Screenshot_20240223_040213_Chrome](https://github.com/WoltLab/WCF/assets/85762221/3c5f4a90-2cf4-4529-99d1-f00b4cbd4d76)

**Comment by BurntimeX** [comment]
In the new user card layout in version 6.1, for the own user the option is no longer shown.
