### ISSUE TITLE
Install as an application on a mobile device

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5818]
The ability to install the forum as an application through the browser, e.g., in Android. This way, an application with the forum logo will appear on the application list, and clicking on it will display the forum in full screen. Example attached. I think it would be a good solution that would make using the forum easier and faster. What do you think?

![Screenshot_20240223_131146_One UI Home](https://github.com/WoltLab/WCF/assets/85762221/267c215b-9680-4ca6-8c30-fa9bd5e4f1b1)
![Screenshot_20240223_131153_Chrome](https://github.com/WoltLab/WCF/assets/85762221/70e655e4-d20a-405c-b519-d7d0ead9b695)

**Comment by dtdesign** [comment]
It is already possible to install the site on the home screen as a web app through your browser. WoltLab Suite 6.1 will also add support for native push notifications on all devices, removing the biggest reason for apps.
