### ISSUE TITLE
[Idea] Adding icons to Alerts/Notice

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5855]
Adding icons to notice/alerts appropriate to their content. Currently, only text is displayed, it would be nice to have an icon preceding the text for additional context.

Examples:
![image](https://github.com/WoltLab/WCF/assets/85762221/e874fcfe-3d6b-46df-8f77-606e0d998ba6)

![image](https://github.com/WoltLab/WCF/assets/85762221/4f2ce4bf-198e-4e11-9e99-560dd16357ab)

![image](https://github.com/WoltLab/WCF/assets/85762221/bb6979eb-115d-4b0f-98a5-14da8d2593c6)

**Comment by BurntimeX** [comment]
This has already been implemented for version 6.1.

See https://github.com/WoltLab/WCF/pull/5709
