### ISSUE TITLE
Improve admin notifications about new registrations

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#5857]
So far, the notification is purely informational and does not contain any information about whether the administrator still needs to do something.

The notification should be generated in two cases:
1. The user has completed the registration process (_after_ the confirmation of the email address _if_ it is required).
2. The user has completed the registration as far as possible and must be activated by the administrator.  In this case, the notification should clearly communicate that the user still needs to be activated.

The notification should also link to the user administration in the admin panel and not to the user profile.

**Comment by MenesesEvandro** [comment]
For the second example would be nice to have a shortcut like ‘approve’ or ‘deny’ right there.
