### ISSUE TITLE
[Idea] Bulk Mail - Tags

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5862]
The ability to use tags in bulk mail, such as for example: username [user_name], {member_url} - directing to user profiles. This would allow for more precise customization of mass messages for individual users. For instance, Hello, [user_name] would display the username on the forum.

**Comment by BurntimeX** [comment]
We already support the following placeholders:

- `{$username}`
- `{$email}`

**Comment by eveneme** [comment]
Great. Needs to be added to documentation. LG

**Comment by BurntimeX** [comment]
see https://github.com/WoltLab/WCF/issues/5864
