### ISSUE TITLE
[Idea] Buttons modernization - forum homepage

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5916]
Another suggestion of mine: Remove less important buttons from the homepage and move them to the background (i.e., menu), extend the 'Add Thread' button to the full width. Buttons like 'Mark All as Read,' 'Ignore Forums,' and 'RSS' should be moved to the background in my opinion, as they are not very important and don't need to be on the homepage.

Look:
![1](https://github.com/WoltLab/WCF/assets/85762221/a5e70424-1fb8-457f-bbca-0e4b3ef48209)

![2](https://github.com/WoltLab/WCF/assets/85762221/be4e4596-0a9a-491d-9949-0b17fb8d01d0)

This is a quick proposal; it can obviously be done more aesthetically.

**Comment by dtdesign** [comment]
This heavily overlaps with #6012. Furthermore the buttons used to span the entire width on mobile but apart from very small screens (like iPhone SE) it looks awful and didn’t really improve the situation. The click targets are large enough to be easily hit and fulfill WCAG ARIA 2.0 recommendations.
