### ISSUE TITLE
Reporting content and warn - issue

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5923]
The 'report content' icon should not be displayed next to your own posts or posts by administrators or moderators. Currently, it is displayed all the time, even next to your own post. The warning icon should also not be displayed to administrators or to oneself.

![Zrzut ekranu 2024-05-26 210929](https://github.com/WoltLab/WCF/assets/85762221/92749fad-7775-483c-b5bd-41c6cea9a478)

![Zrzut ekranu 2024-05-26 213057](https://github.com/WoltLab/WCF/assets/85762221/27177205-ebde-406f-b58e-0a2c0817634c)

**Comment by BurntimeX** [comment]
I don't agree with that. There are certainly reasons why you might want to report your own posts. For example, if you do not have the permission to delete but would like to have the post deleted.
