### ISSUE TITLE
Emoji picker

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#5969]
A picker for emoji as a tab below the editor to simplify the insertion of emojis (especially on non-mobile devices).

The graphics of the respective operating system should be used to display the emojis so that we do not have to rely on third-party libraries.

As emojis are somewhat redundant to the existing smiley function, they could replace the smiley function in the long term. For the time being, I prefer to set the smiley function to "off" in the default installation.

**Comment by Krymonota** [comment]
Personally, I'm a fan of [emoji-picker-element](https://www.npmjs.com/package/emoji-picker-element). You might want to take a look at this emoji picker – be it for integration or inspiration purposes 🙂

**Comment by SoftCreatR** [comment]
I hope, this will be done developer friendly, so that we are able to replace them with custom graphics, when desired. This will be interesting for those, who purchased emojione for example.
