### ISSUE TITLE
Mobile logo is not centred on login and register pages 

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5985]
https://www.woltlab.com/login/

https://www.woltlab.com/register/

.pageHeader {
column-gap: 10px; 
}

causes an offset of 30px to the left

**Comment by eveneme** [comment]
6.1.0 RC1

![Screenshot_20241010_223614_Chrome](https://github.com/user-attachments/assets/e152fd2d-f91d-4c7c-a49a-8f887134cbe1)
