### ISSUE TITLE
[6.1] Unable to find template '__devtoolsProjectRequiredPackagesFormField'

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5996]
The template was removed in da53a42182daa5c329b4f1c5c728598727bd1090 but it's still in use (https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/form/builder/field/devtools/project/DevtoolsProjectRequiredPackagesFormField.class.php#L24)

So editing a devtools project raises this error:

```
Unable to find template '__devtoolsProjectRequiredPackagesFormField'
```

**Comment by dtdesign** [comment]
@Cyperghost This does not cause the templates to be redeployed though. You need to add a remark in the `package.xml` that we need to deploy all ACP templates for beta 2.
