### ISSUE TITLE
Add WebP image embed support

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#6001]
With the software now supporting WebP uploads, it would be highly beneficial to extend this capability to include embedding WebP images. This would enhance functionality, allowing users to include WebP files in attachments and other embedded content formats.

**Comment by dtdesign** [comment]
@SoftCreatR Can you please explain what do you mean with “embedding WebP images”? You can upload and insert those images in messages just fine?

**Comment by SoftCreatR** [comment]
Whoops 🤭
