### ISSUE TITLE
6.0 / 6.1 - Style editor "Advanced settings" tab jumps to the wrong input-field

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#6046]
When you click on ‘Advanced Settings’ tab, the content jumps to the beginning of ‘SCSS Variables Override’ instead of displaying the top of the page. Tested on Chrome and Safari.

**Comment by dtdesign** [comment]
@cls-design I can’t reproduce this issue based on the description nor did I found any situation that matches the described behavior. Please provide step-by-step instructions here,

**Comment by cls-design** [comment]
I can reproduce it this way:

Unprotected styles:

Edit Style -> Tab -> Advanced Settings -> Jumps to  "SCSS Variables Override"

Protected styles:

Edit Style -> Tab -> Advanced Settings -> Sub-Tab "Preset Declarations" -> Jumps to "SCSS Variables Override (Read only)"

----
Edit:

![Dec-02-2024 17-38-40](https://github.com/user-attachments/assets/c825b091-b5f7-4b6a-95d5-ab9edef0ec13)

**Comment by dtdesign** [comment]
Thank you. I was testing this with the default style (which is protected) and it only occurs when accessing the sub tab.
